with product_aliases(
    source_priority,
    source,
    match_type,
    pattern,
    product_code,
    option_type
) as (
    values
        (1, 'nav', 'regex', '^ICE NGAS HH SWG DLY DAY-[0-9]+$', 'HHD', null),
        (2, 'nav', 'exact', 'ICE NGAS HH SWING DAILY', 'HHD', null),
        (3, 'nav', 'exact', 'NATURAL GAS', 'NG', null),
        (4, 'nav', 'exact', 'GLOBEX NATURAL GAS LD', 'HH', null),
        (5, 'nav', 'exact', 'NYMEX HENRY HUB FINANCIAL LDO', 'HH', null),
        (6, 'nav', 'exact', 'NYMEX HENRY HUB NATURAL GAS', 'HP', null),
        (7, 'nav', 'exact', 'HENRY PENULTIMATE NATURAL GAS', 'HP', null),
        (8, 'nav', 'exact', 'NATURAL GAS LD1 FUTURE', 'H', null),
        (9, 'nav', 'exact', 'HENRY HUB NATURAL GAS', 'H', null),
        (10, 'nav', 'exact', 'ICE PHH', 'PHH', null),
        (11, 'nav', 'exact', 'ICE PHE', 'PHE', 'option'),
        (12, 'nav', 'exact', 'ICE HH EQ', 'PHE', 'option'),
        (13, 'nav', 'exact', 'ICE NGAS PEN HENRY HUB', 'PHE', 'option'),
        (14, 'nav', 'exact', 'NYM EUR NATURAL GAS', 'LN', 'option'),
        (15, 'nav', 'exact', 'NATURAL GAS CLEARPORT', 'LN', 'option'),
        (16, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 1', 'LN1', 'option'),
        (17, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 2', 'LN2', 'option'),
        (18, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 3', 'LN3', 'option'),
        (19, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 4', 'LN4', 'option'),
        (20, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 5', 'LN5', 'option'),
        (21, 'nav', 'exact', 'NATURAL GAS 3M CSO', 'G3', 'option'),
        (22, 'nav', 'exact', 'NATURAL GAS FINANCIAL 1M SO', 'G4', 'option'),
        (23, 'nav', 'exact', 'NATURAL GAS 1M CSO', 'G4', 'option'),
        (24, 'nav', 'exact', 'ICE PJM WH RTD', 'PDP', null),
        (25, 'nav', 'exact', 'ICE PWA', 'PWA', null),
        (26, 'nav', 'exact', 'ICE PJMWHPKDAY', 'PDA', null),
        (27, 'nav', 'exact', 'ICE PJL', 'PJL', null),
        (28, 'nav', 'exact', 'ICE PDA', 'PDA', null),
        (29, 'nav', 'exact', 'ICE PJL DAILY', 'PJL', null),
        (30, 'nav', 'regex', '^ICE (PJM MINI|MINIPJMRT|PJM WHREAL TYM PK MINI)([-_][0-9]+)?$', 'PMI', null),
        (31, 'nav', 'exact', 'ICE PJM WHRT PEAK OPT_4096', 'P1X', 'option'),
        (32, 'nav', 'regex', '^ICE PJM OFF PK[-_][0-9]+$', 'OPJ', null),
        (33, 'nav', 'exact', 'ICE ERA', 'ERA', null),
        (34, 'nav', 'exact', 'ERCOT N 345 KV RT PEAK DLY', 'ERN', null),
        (35, 'nav', 'exact', 'ICE END', 'END', null),
        (36, 'nav', 'regex', '^ICE ERCOT NORTH 345KV 7X8[-_][0-9]+$', 'ECI', null),
        (37, 'nav', 'regex', '^(ISO ENG MASS HUB D-PK-[0-9]+|ICE NEPOOL PK MNTH-[0-9]+)$', 'NEP', null),
        (38, 'nav', 'regex', '^ICE SP 15 PEAK([_-][0-9]+)?$', 'SPM', null),
        (39, 'nav', 'regex', '^ICE NP 15 PEAK([_-][0-9]+)?$', 'NPM', null),
        (40, 'nav', 'regex', '^ICE MID-C PEAK([_-][0-9]+)?$', 'MDC', null),
        (41, 'nav', 'exact', 'AB NIT BASIS FUTURE', 'AEC', null),
        (42, 'nav', 'exact', 'ICE ALQCTYGTSW', 'ALQ', null),
        (43, 'nav', 'exact', 'ICE CIG ROCKIES BASIS', 'CRI', null),
        (44, 'nav', 'exact', 'ICE CHICAGO BASIS FUT', 'DGD', null),
        (45, 'nav', 'exact', 'ICE EASTERN GAS SOUTH BASIS FU', 'DOM', null),
        (46, 'nav', 'exact', 'ICE HSC BASIS', 'HXS', null),
        (47, 'nav', 'exact', 'NGPL TXOK BASIS FUTURE', 'NTO', null),
        (48, 'nav', 'exact', 'ICE NGAS NYM NWP RK', 'NWR', null),
        (49, 'nav', 'exact', 'ICE NGAS NYM PG&E', 'PGE', null),
        (50, 'nav', 'exact', 'ICE TETCO SWP', 'TMT', null),
        (51, 'nav', 'exact', 'ICE TRANSCO STATION 85 ZONE 4', 'TRZ', null),
        (52, 'nav', 'exact', 'ICE TCOZN4BASI', 'TRZ', null),
        (53, 'nav', 'exact', 'ICE SDP', 'SDP', null)
),

FINAL as (
    select * from product_aliases
)

select *
from FINAL
