with product_catalog(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
) as (
    values
        ('HHD', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('NG', 'Gas', 'Henry Hub', null, 'NG', 'NYME'),
        ('HH', 'Gas', 'Henry Hub', null, 'IW', 'NYME'),
        ('HP', 'Gas', 'Henry Hub', null, 'ZA', 'NYME'),
        ('H', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('PHH', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('PHE', 'Gas', 'Henry Hub', 'NG', null, 'IFED'),
        ('LN', 'Gas', 'Henry Hub', 'NG', 'NG', 'NYME'),
        ('LN1', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN2', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN3', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN4', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN5', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('JN1', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('KN2', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('KN3', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('KN4', 'Gas', 'Henry Hub', 'NG', 'HZI', 'NYME'),
        ('G3', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('G4', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('PDP', 'Power', 'PJM', null, null, 'IFED'),
        ('PWA', 'Power', 'PJM', null, null, 'IFED'),
        ('DDP', 'Power', 'PJM', null, null, 'IFED'),
        ('PDA', 'Power', 'PJM', null, null, 'IFED'),
        ('PJL', 'Power', 'PJM', null, null, 'IFED'),
        ('PMI', 'Power', 'PJM', 'PMI', null, 'IFED'),
        ('P1X', 'Power', 'PJM', 'PMI', null, 'IFED'),
        ('OPJ', 'Power', 'PJM', null, null, 'IFED'),
        ('ODP', 'Power', 'PJM', null, null, 'IFED'),
        ('ERA', 'Power', 'ERCOT', null, null, 'IFED'),
        ('ERN', 'Power', 'ERCOT', null, null, 'IFED'),
        ('END', 'Power', 'ERCOT', null, null, 'IFED'),
        ('ECI', 'Power', 'ERCOT', null, null, 'IFED'),
        ('NEZ', 'Power', 'NEPOOL', null, null, 'IFED'),
        ('NEP', 'Power', 'NEPOOL', null, null, 'IFED'),
        ('SPM', 'Power', 'CAISO', null, null, 'IFED'),
        ('SDP', 'Power', 'CAISO', null, null, 'IFED'),
        ('NPM', 'Power', 'CAISO', null, null, 'IFED'),
        ('MDC', 'Power', 'Mid-C', null, null, 'IFED'),
        ('AEC', 'Basis', 'AECO', null, null, 'IFED'),
        ('ALQ', 'Basis', 'Algonquin', null, null, 'IFED'),
        ('CRI', 'Basis', 'CIG Rockies', null, null, 'IFED'),
        ('DGD', 'Basis', 'Chicago', null, null, 'IFED'),
        ('DOM', 'Basis', 'Eastern Gas South', null, null, 'IFED'),
        ('HXS', 'Basis', 'Houston Ship Channel', null, null, 'IFED'),
        ('UCS', 'Basis', 'Houston Ship Channel', null, null, 'IFED'),
        ('NTO', 'Basis', 'NGPL TXOK', null, null, 'IFED'),
        ('NWR', 'Basis', 'Northwest Rockies', null, null, 'IFED'),
        ('PGE', 'Basis', 'PG&E Citygate', null, null, 'IFED'),
        ('TMT', 'Basis', 'Tetco M3', null, null, 'IFED'),
        ('TRZ', 'Basis', 'Transco Zone 4', null, null, 'IFED')
)

select * from product_catalog
