-- Generated by python -m backend.scrapes.positions_and_trades.sql_generator.
-- Source of truth: backend/scrapes/positions_and_trades/rules/*.json.
-- Do not edit directly. Update the rule JSON and regenerate this file.
--
-- Purpose: read-only latest MUFG Clear Street trade extract.
-- How to read: CTEs are numbered in dependency order; the final SELECT keeps
-- the legacy export shape.
-- Debugging tip: replace the final SELECT with SELECT * FROM any named CTE to
-- inspect that stage in a SQL editor.
-- Persistence: this script does not create, update, insert, or delete rows.
-- File: clear_street_trades_mufg_latest.sql

with
-- -----------------------------------------------------------------------------
-- CTE 01 - params
-- Optional SQL-editor filters. Leave all values null for the production-style latest extract.
params as (
    select
        null::date as trade_date_filter,
        null::text as account_number_filter,
        null::text as product_search
),
-- -----------------------------------------------------------------------------
-- CTE 02 - product_catalog
-- Embedded product definitions compiled from rules/product_definitions.json.
product_catalog(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
) as (
    values
        ('HHD', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('NG', 'Gas', 'Henry Hub', null, 'NG', 'NYME'),
        ('HH', 'Gas', 'Henry Hub', null, 'IW', 'NYME'),
        ('HP', 'Gas', 'Henry Hub', null, 'ZA', 'NYME'),
        ('H', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('PHH', 'Gas', 'Henry Hub', null, null, 'IFED'),
        ('PHE', 'Gas', 'Henry Hub', 'NG', null, 'IFED'),
        ('LN', 'Gas', 'Henry Hub', 'NG', 'NG', 'NYME'),
        ('LN1', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN2', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN3', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN4', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('LN5', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
        ('KN4', 'Gas', 'Henry Hub', 'NG', 'HZI', 'NYME'),
        ('G3', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('G4', 'Gas', 'Henry Hub', 'NG', null, 'NYME'),
        ('PDP', 'Power', 'PJM', null, null, 'IFED'),
        ('PWA', 'Power', 'PJM', null, null, 'IFED'),
        ('DDP', 'Power', 'PJM', null, null, 'IFED'),
        ('PDA', 'Power', 'PJM', null, null, 'IFED'),
        ('PJL', 'Power', 'PJM', null, null, 'IFED'),
        ('PMI', 'Power', 'PJM', 'PMI', null, 'IFED'),
        ('P1X', 'Power', 'PJM', 'PMI', null, 'IFED'),
        ('OPJ', 'Power', 'PJM', null, null, 'IFED'),
        ('ODP', 'Power', 'PJM', null, null, 'IFED'),
        ('ERA', 'Power', 'ERCOT', null, null, 'IFED'),
        ('ERN', 'Power', 'ERCOT', null, null, 'IFED'),
        ('ECI', 'Power', 'ERCOT', null, null, 'IFED'),
        ('NEZ', 'Power', 'NEPOOL', null, null, 'IFED'),
        ('NEP', 'Power', 'NEPOOL', null, null, 'IFED'),
        ('SPM', 'Power', 'CAISO', null, null, 'IFED'),
        ('NPM', 'Power', 'CAISO', null, null, 'IFED'),
        ('MDC', 'Power', 'Mid-C', null, null, 'IFED'),
        ('AEC', 'Basis', 'AECO', null, null, 'IFED'),
        ('ALQ', 'Basis', 'Algonquin', null, null, 'IFED'),
        ('CRI', 'Basis', 'CIG Rockies', null, null, 'IFED'),
        ('DGD', 'Basis', 'Chicago', null, null, 'IFED'),
        ('DOM', 'Basis', 'Eastern Gas South', null, null, 'IFED'),
        ('HXS', 'Basis', 'Houston Ship Channel', null, null, 'IFED'),
        ('UCS', 'Basis', 'Houston Ship Channel', null, null, 'IFED'),
        ('NTO', 'Basis', 'NGPL TXOK', null, null, 'IFED'),
        ('NWR', 'Basis', 'Northwest Rockies', null, null, 'IFED'),
        ('PGE', 'Basis', 'PG&E Citygate', null, null, 'IFED'),
        ('TMT', 'Basis', 'Tetco M3', null, null, 'IFED'),
        ('TRZ', 'Basis', 'Transco Zone 4', null, null, 'IFED')
),
-- -----------------------------------------------------------------------------
-- CTE 03 - product_aliases
-- Source-specific product description aliases compiled from rules/product_aliases.json.
product_aliases(
    priority,
    source,
    match_type,
    pattern,
    product_code,
    option_type
) as (
    values
        (94, 'clear_street', 'exact', 'PMI-PJM WESTERN HUB REAL-TIME PEAK MINI FIXED PRICE FUTURE', 'PMI', 'future'),
        (95, 'clear_street', 'exact', 'PMI-OPTION ON PJM WESTERN HUB REAL-TIME PEAK MINI FIXED PRICE FUTURE', 'P1X', 'option'),
        (96, 'clear_street', 'exact', 'PWA-PJM WESTERN HUB REAL-TIME PEAK DAILY MINI FIXED PRICE FUTURE', 'PWA', 'future'),
        (97, 'clear_street', 'exact', 'H-HENRY LD1 FIXED PRICE FUTURE', 'H', 'future'),
        (98, 'clear_street', 'exact', 'SPM-CAISO SP-15 DAY-AHEAD PEAK FIXED PRICE FUTURE', 'SPM', 'future'),
        (99, 'clear_street', 'exact', 'ALQ-ALGONQUIN CITYGATES BASIS FUTURE', 'ALQ', 'future'),
        (100, 'clear_street', 'exact', 'PGE-PG&E CITYGATE BASIS FUTURE', 'PGE', 'future'),
        (101, 'clear_street', 'exact', 'PDP-PJM WESTERN HUB REAL-TIME PEAK DAILY FIXED PRICE FUTURE', 'PDP', 'future'),
        (102, 'clear_street', 'exact', 'PHE-OPTION ON HENRY PENULTIMATE FIXED PRICE FUTURE', 'PHE', 'option'),
        (103, 'clear_street', 'exact', 'CRI-CIG ROCKIES BASIS FUTURE', 'CRI', 'future')
),
-- -----------------------------------------------------------------------------
-- CTE 04 - source_trades
-- Raw Clear Street rows with optional params filters applied.
source_trades as (
    select
        t.*
    from clear_street.eod_transactions as t
    cross join params as p
    where
        (
            p.trade_date_filter is null
            or t.trade_date_from_sftp = to_char(p.trade_date_filter, 'YYYYMMDD')
            or t.trade_date = to_char(p.trade_date_filter, 'YYYYMMDD')
        )
        and (
            p.account_number_filter is null
            or t.account_number = p.account_number_filter
        )
        and (
            p.product_search is null
            or upper(coalesce(t.futures_code, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.exch_comm_cd, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.symbol, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.security_description, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.instrument_description, '')) like '%' || upper(p.product_search) || '%'
        )
),
-- -----------------------------------------------------------------------------
-- CTE 05 - prepared_trades
-- Chooses the best source product description before normalization.
prepared_trades as (
    select
        t.*,
        coalesce(
            nullif(trim(t.security_description), ''),
            nullif(trim(t.instrument_description), ''),
            nullif(trim(t.symbol), '')
        ) as rule_product
    from source_trades as t
),
-- -----------------------------------------------------------------------------
-- CTE 06 - normalized_base
-- Normalizes product text, exchange code, contract month, option side, strike, exchange name, and cash-adjustment detection.
normalized_base as (
    select
        p.*,
        nullif(
            upper(regexp_replace(coalesce(p.rule_product, ''), '[[:space:]]+', ' ', 'g')),
            ''
        ) as rule_product_norm,
        upper(
            coalesce(
                nullif(trim(p.futures_code), ''),
                nullif(trim(p.exch_comm_cd), '')
            )
        ) as rule_exchange_code,
        case
            when p.contract_year_month is not null
                and p.contract_year_month <> 0
                and lpad(p.contract_year_month::text, 6, '0') ~ '^(19|20|21)[0-9]{2}(0[1-9]|1[0-2])$'
            then lpad(p.contract_year_month::text, 6, '0')
        end as contract_yyyymm,
        case
            when p.prompt_day between 1 and 31 then p.prompt_day
        end as contract_day,
        case upper(nullif(trim(p.put_call), ''))
            when 'CALL' then 'C'
            when 'C' then 'C'
            when 'PUT' then 'P'
            when 'P' then 'P'
        end as put_call_code,
        case
            when p.strike_price is not null and p.strike_price <> 0
            then round(p.strike_price::numeric, 3)::double precision
        end as strike_price_normalized,
        upper(nullif(trim(p.security_type_code), '')) as security_type_code_norm,
        upper(nullif(trim(p.instr_type), '')) as instr_type_norm,
        case upper(nullif(trim(p.exchange_name), ''))
            when 'NYM' then 'NYME'
            when 'NYME' then 'NYME'
            when 'IFE' then 'IFED'
            when 'IPE' then 'IFED'
            when 'IFED' then 'IFED'
        end as exchange_name_normalized,
        (
            coalesce(p.quantity, 0) = 0
            and coalesce(p.contract_year_month, 0) = 0
            and upper(coalesce(p.security_description, '')) = 'UNITED STATES DOLLAR'
            and upper(coalesce(p.instrument_description, '')) like 'RESID ADJ%'
        ) as is_non_product_cash_adjustment
    from prepared_trades as p
),
-- -----------------------------------------------------------------------------
-- CTE 07 - normalized_trades
-- Adds contract year/month display fields and option detection.
normalized_trades as (
    select
        b.*,
        case
            when b.contract_yyyymm is not null
            then left(b.contract_yyyymm, 4)::integer
        end as contract_year,
        case
            when b.contract_yyyymm is not null
            then right(b.contract_yyyymm, 2)::integer
        end as contract_month_number,
        case
            when b.contract_yyyymm is not null
            then left(b.contract_yyyymm, 4) || '-' || right(b.contract_yyyymm, 2)
        end as contract_month,
        (
            b.put_call_code is not null
            or b.security_type_code_norm in ('O', 'OPT', 'OPTION')
            or b.security_type_code_norm like '%OPTION%'
            or b.instr_type_norm in ('O', 'OPT', 'OPTION')
            or b.instr_type_norm like '%OPTION%'
        ) as is_option
    from normalized_base as b
),
-- -----------------------------------------------------------------------------
-- CTE 08 - contract_trades
-- Adds futures month codes and daily contract keys.
contract_trades as (
    select
        n.*,
        case contract_month_number
        when 1 then 'F'
        when 2 then 'G'
        when 3 then 'H'
        when 4 then 'J'
        when 5 then 'K'
        when 6 then 'M'
        when 7 then 'N'
        when 8 then 'Q'
        when 9 then 'U'
        when 10 then 'V'
        when 11 then 'X'
        when 12 then 'Z'
    end as futures_month_code,
        case
            when n.contract_yyyymm is not null and n.contract_day is not null
            then n.contract_yyyymm || lpad(n.contract_day::text, 2, '0')
        end as contract_yyyymmdd
    from normalized_trades as n
),
-- -----------------------------------------------------------------------------
-- CTE 09 - product_matches
-- Resolves explicit product codes first, then falls back to the highest-priority source alias.
product_matches as (
    select
        c.*,
        explicit_catalog.product_code as explicit_product_code,
        explicit_catalog.product_family as explicit_product_family,
        explicit_catalog.market_name as explicit_market_name,
        explicit_catalog.underlying_product_code as explicit_underlying_product_code,
        explicit_catalog.bbg_exchange_code as explicit_bbg_exchange_code,
        explicit_catalog.default_exchange_name as explicit_default_exchange_name,
        alias_match.alias_product_code,
        alias_match.alias_product_family,
        alias_match.alias_market_name,
        alias_match.alias_underlying_product_code,
        alias_match.alias_bbg_exchange_code,
        alias_match.alias_default_exchange_name,
        alias_match.alias_priority,
        alias_match.alias_match_type,
        alias_match.alias_pattern
    from contract_trades as c
    left join product_catalog as explicit_catalog
        on explicit_catalog.product_code = c.rule_exchange_code
    left join lateral (
        select
            catalog.product_code as alias_product_code,
            catalog.product_family as alias_product_family,
            catalog.market_name as alias_market_name,
            catalog.underlying_product_code as alias_underlying_product_code,
            catalog.bbg_exchange_code as alias_bbg_exchange_code,
            catalog.default_exchange_name as alias_default_exchange_name,
            alias.priority as alias_priority,
            alias.match_type as alias_match_type,
            alias.pattern as alias_pattern
        from product_aliases as alias
        join product_catalog as catalog
            on catalog.product_code = alias.product_code
        where
            explicit_catalog.product_code is null
            and c.rule_product_norm is not null
            and (
                alias.option_type is null
                or alias.option_type = case when c.is_option then 'option' else 'future' end
            )
            and (
                (
                    alias.match_type = 'exact'
                    and c.rule_product_norm = alias.pattern
                )
                or (
                    alias.match_type = 'regex'
                    and c.rule_product_norm ~* alias.pattern
                )
            )
        order by alias.priority
        limit 1
    ) as alias_match on true
),
-- -----------------------------------------------------------------------------
-- CTE 10 - trades_with_rules
-- Produces canonical product fields and rule_status values for SQL-editor validation.
trades_with_rules as (
    select
        m.*,
        coalesce(m.explicit_product_code, m.alias_product_code) as product_code,
        coalesce(m.explicit_product_family, m.alias_product_family) as product_family,
        coalesce(m.explicit_market_name, m.alias_market_name) as market_name,
        case
            when m.is_option
            then coalesce(
                m.explicit_underlying_product_code,
                m.alias_underlying_product_code
            )
        end as underlying_product_code,
        coalesce(m.explicit_bbg_exchange_code, m.alias_bbg_exchange_code)
            as bbg_exchange_code,
        coalesce(
            m.exchange_name_normalized,
            m.explicit_default_exchange_name,
            m.alias_default_exchange_name
        ) as rule_exchange_name,
        case
            when m.is_non_product_cash_adjustment
            then 'non_product_cash_adjustment'
            when coalesce(m.explicit_product_code, m.alias_product_code) is null
            then 'unresolved_product'
            when m.contract_yyyymm is null
            then 'missing_contract_yyyymm'
            when m.is_option and m.put_call_code is null
            then 'option_missing_put_call'
            when m.is_option and m.strike_price_normalized is null
            then 'option_missing_strike'
            else 'ok'
        end as rule_status,
        case
            when m.explicit_product_code is not null then 'explicit'
            when m.alias_product_code is not null then 'alias'
        end as rule_match_source,
        m.alias_priority as rule_match_priority,
        m.alias_match_type as rule_match_type,
        m.alias_pattern as rule_match_pattern,
        case
            when m.futures_month_code is not null and m.contract_year is not null
            then m.futures_month_code || right(m.contract_year::text, 1)
        end as futures_month_code_y,
        case
            when m.futures_month_code is not null and m.contract_year is not null
            then m.futures_month_code || right(m.contract_year::text, 2)
        end as futures_month_code_yy
    from product_matches as m
),
-- -----------------------------------------------------------------------------
-- CTE 11 - trades_with_export_base
-- Formats strike text once and derives ICE codes before CME/BBG codes reuse those normalized fields.
trades_with_export_base as (
    select
        trades_with_rules.*,
        trim(
            trailing '.'
            from trim(
                trailing '0'
                from to_char(strike_price_normalized, 'FM999999999.999')
            )
        ) as strike_text,
        case
            when rule_exchange_name = 'IFED' and product_code = 'HHD'
            then product_code || ' B0-IUS'
            when product_code in ('PDP', 'PWA', 'DDP')
            then product_code || ' D0-IUS'
            when
                rule_exchange_name = 'IFED'
                and is_option
                and put_call_code is not null
                and strike_price_normalized is not null
                and futures_month_code_yy is not null
            then product_code || ' ' || futures_month_code_yy || put_call_code
                || round(strike_price_normalized)::integer::text || '-IUS'
            when
                rule_exchange_name = 'IFED'
                and not is_option
                and contract_day is null
                and futures_month_code_yy is not null
            then product_code || ' ' || futures_month_code_yy || '-IUS'
        end as ice_product_code
    from trades_with_rules
),
-- -----------------------------------------------------------------------------
-- CTE 12 - trades_with_export_codes
-- Adds CME and Bloomberg product codes from normalized contract, option, strike, and product metadata.
trades_with_export_codes as (
    select
        trades_with_export_base.*,
        case
            when product_code in ('HP', 'PHH', 'HH', 'H', 'NG') and contract_yyyymm is not null
            then '1|G|XNYM:F:NG:' || contract_yyyymm
            when
                product_code in ('LN', 'PHE')
                and contract_yyyymm is not null
                and put_call_code is not null
                and strike_price_normalized is not null
            then '1|G|XNYM:O:LN:' || contract_yyyymm || ':' || put_call_code || ':' || strike_text
            when
                (
                    product_code in ('LN1', 'LN2', 'LN3', 'LN4', 'LN5')
                    or product_code = 'KN4'
                )
                and contract_yyyymm is not null
                and put_call_code is not null
                and strike_price_normalized is not null
            then '1|G|XNYM:O:KN' || substring(product_code from 3) || ':'
                || contract_yyyymm || ':' || put_call_code || ':' || strike_text
            when product_code in ('G3', 'G4')
            then 'CAL_SPREAD_CME_EXCEL_CODE'
        end as cme_product_code,
        case
            when product_code = 'HP' and bbg_exchange_code = 'ZA' and futures_month_code_y is not null
            then bbg_exchange_code || futures_month_code_y || ' COMDTY'
            when product_code = 'HH' and bbg_exchange_code = 'IW' and futures_month_code_y is not null
            then bbg_exchange_code || futures_month_code_y || ' COMDTY'
            when product_code = 'NG' and bbg_exchange_code = 'NG' and futures_month_code_yy is not null
            then bbg_exchange_code || futures_month_code_yy || ' COMDTY'
            when
                product_code in ('LN', 'PHE')
                and bbg_exchange_code = 'NG'
                and futures_month_code_y is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_y || put_call_code || ' '
                || strike_text || ' COMDTY'
            when
                product_code in ('LN1', 'LN2', 'LN3', 'LN4', 'LN5')
                and futures_month_code_yy is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_yy || put_call_code
                || substring(product_code from 3) || ' ' || strike_text || ' COMB'
            when
                product_code = 'KN4'
                and futures_month_code_yy is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_yy || put_call_code
                || substring(product_code from 3) || ' ' || strike_text || ' Comdty'
        end as bbg_product_code
    from trades_with_export_base
),
-- -----------------------------------------------------------------------------
-- CTE 13 - latest_sftp_date
-- Finds the newest available Clear Street SFTP trade date after the optional params filter.
latest_sftp_date as (
    select max(trade_date_from_sftp) as trade_date_from_sftp
    from source_trades
)
-- -----------------------------------------------------------------------------
-- Final select - legacy MUFG export shape
-- Keeps the raw Clear Street columns first, then appends generated fields needed by the outbound file.
select
    -- Raw Clear Street transaction columns, kept in legacy extract order.
    record_id,
    firm,
    organization,
    account_number,
    account_type,
    currency_symbol,
    rr,
    trade_date,
    buy_sell,
    quantity,
    exchange,
    futures_code,
    symbol,
    contract_year_month,
    prompt_day,
    strike_price,
    put_call,
    security_description,
    trade_price,
    printable_price,
    trade_type,
    order_number,
    security_type_code,
    cusip,
    comment_code,
    give_in_out_code,
    give_in_out_firm_num,
    spread_code,
    open_close_code,
    trace_num_or_unique_identifier,
    round_turn_half_turn_account,
    executing_broker,
    opposing_broker,
    oppos_firm,
    commission,
    comm_act_type,
    fee_amt_1,
    fee_1_atype,
    fee_amt_2,
    fee_2_atype,
    fee_amt_3,
    fee_3_atype,
    brokerage,
    brkrage_atype,
    give_io_charge,
    give_io_atype,
    other_charges,
    other_atype,
    wire_charge,
    wire_chg_atype,
    fee_type_6,
    fee_type_6_atype,
    date,
    case
        when nullif(trim(option_exp_date), '') is null then null
        when trim(option_exp_date) < '0001-01-01' then null
        else option_exp_date
    end as option_exp_date,
    last_trd_date,
    net_amount,
    traded_exchg,
    sub_exchange,
    exchange_name,
    exch_comm_cd,
    multiplication_factor,
    subaccount,
    instr_type,
    cash_settled,
    instrument_description,
    fee_amt_4,
    fee_4_atype,
    fee_amt_5,
    fee_5_atype,
    fee_amt_7,
    fee_7_atype,
    fee_amt_8,
    fee_8_atype,
    fee_amt_9,
    fee_9_atype,
    fee_amt_10,
    fee_10_atype,
    fee_amt_11,
    fee_11_atype,
    fee_amt_12,
    fee_12_atype,
    fee_amt_13,
    fee_13_atype,
    clearing_time_hhmmss,
    settlement_price,
    broker,
    isin,
    mic,

    -- Generated fields used by downstream review/export workflows.
    to_date(trades_with_export_codes.trade_date_from_sftp, 'YYYYMMDD') as sftp_date,
    sftp_upload_timestamp::timestamp as sftp_upload_timestamp,
    'New' as trade_status,
    product_family as product_code_grouping,
    market_name as product_code_region,
    underlying_product_code as product_code_underlying,
    ice_product_code,
    cme_product_code,
    bbg_product_code
from trades_with_export_codes
join latest_sftp_date
    on latest_sftp_date.trade_date_from_sftp = trades_with_export_codes.trade_date_from_sftp
-- MUFG give-in/out firms from the legacy extract.
where give_in_out_firm_num in ('ADU', '905')
order by
    sftp_date desc,
    sftp_upload_timestamp desc,
    product_code_grouping,
    product_code_region;
