"""PJM Data Miner 2 feed contracts used by generic scrapes."""

from __future__ import annotations

from backend.scrapes.power.pjm.data_miner_feed import DataMinerFeedConfig
from backend.scrapes.power.pjm.pricing_filters import DEFAULT_PRICING_NODE_TYPES


FEED_CONFIGS: dict[str, DataMinerFeedConfig] = {
    "act_sch_interchange": DataMinerFeedConfig(
        feed_name="act_sch_interchange",
        display_name="Actual/Schedule Summary Report",
        category="Imports and Exports",
        posting_frequency="Weekly",
        retention_time="Indefinitely",
        columns=(
            "actual_flow",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "inadv_flow",
            "sched_flow",
            "tie_line",
        ),
        primary_key=("datetime_beginning_utc", "tie_line"),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
        ),
        numeric_columns=("actual_flow", "inadv_flow", "sched_flow"),
        text_columns=("tie_line",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=14,
    ),
    "agg_definitions": DataMinerFeedConfig(
        feed_name="agg_definitions",
        display_name="Fixed Weighted Average Aggregate Definitions",
        category="LMP Model",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "agg_pnode_id",
            "terminate_date_ept",
            "agg_pnode_name",
            "bus_pnode_factor",
            "bus_pnode_id",
            "bus_pnode_name",
            "effective_date_ept",
        ),
        primary_key=("agg_pnode_id", "bus_pnode_id", "effective_date_ept"),
        date_columns=("terminate_date_ept", "effective_date_ept"),
        numeric_columns=("agg_pnode_id", "bus_pnode_factor", "bus_pnode_id"),
        text_columns=("agg_pnode_name", "bus_pnode_name"),
        static_params={"terminate_date_ept": "12/31/9999 exact"},
        sql_data_types={
            "agg_pnode_id": "BIGINT",
            "bus_pnode_id": "BIGINT",
            "bus_pnode_factor": "DOUBLE PRECISION",
        },
    ),
    "ancillary_services": DataMinerFeedConfig(
        feed_name="ancillary_services",
        display_name="Real-Time Ancillary Service Hourly LMPs",
        category="Locational Marginal Prices",
        posting_frequency="Daily on Business Days",
        retention_time="Indefinitely",
        columns=(
            "ancillary_service",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "row_is_current",
            "unit",
            "value",
            "version_nbr",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "ancillary_service",
            "row_is_current",
            "version_nbr",
        ),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("value", "version_nbr"),
        bool_columns=("row_is_current",),
        text_columns=("ancillary_service", "unit"),
        datetime_filter_field="datetime_beginning_ept",
        static_params={"row_is_current": "1"},
        default_lookback_days=10,
        default_end_time="23:00",
    ),
    "da_interface_flows_and_limits": DataMinerFeedConfig(
        feed_name="da_interface_flows_and_limits",
        display_name="Day Ahead Interface Flows and Limits",
        category="Imports and Exports",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "flow_mw",
            "interface_limit_name",
            "limit_mw",
        ),
        primary_key=("datetime_beginning_utc", "interface_limit_name"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("flow_mw", "limit_mw"),
        text_columns=("interface_limit_name",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=7,
        default_lookahead_days=1,
        default_end_time="23:00",
    ),
    "da_marginal_value": DataMinerFeedConfig(
        feed_name="da_marginal_value",
        display_name="Day-Ahead Marginal Value",
        category="Constraints",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "contingency_facility",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "monitored_facility",
            "shadow_price",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "monitored_facility",
            "contingency_facility",
        ),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
        ),
        numeric_columns=("shadow_price",),
        text_columns=("contingency_facility", "monitored_facility"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
        default_lookahead_days=1,
        default_end_time="23:00",
    ),
    "da_transconstraints": DataMinerFeedConfig(
        feed_name="da_transconstraints",
        display_name="Day-Ahead Transmission Constraints",
        category="Constraints",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "contingency_facility",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "day_ahead_congestion_event",
            "duration",
            "monitored_facility",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "day_ahead_congestion_event",
            "monitored_facility",
            "contingency_facility",
        ),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
        ),
        numeric_columns=("duration",),
        text_columns=(
            "contingency_facility",
            "day_ahead_congestion_event",
            "monitored_facility",
        ),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
        default_lookahead_days=1,
        default_end_time="23:00",
    ),
    "day_gen_capacity": DataMinerFeedConfig(
        feed_name="day_gen_capacity",
        display_name="Daily Generation Capacity",
        category="Generation",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "bid_datetime_beginning_ept",
            "bid_datetime_beginning_utc",
            "eco_max",
            "emerg_max",
            "total_committed",
        ),
        primary_key=("bid_datetime_beginning_utc",),
        datetime_columns=("bid_datetime_beginning_ept", "bid_datetime_beginning_utc"),
        numeric_columns=("eco_max", "emerg_max", "total_committed"),
        datetime_filter_field="bid_datetime_beginning_ept",
        default_lookback_days=10,
        default_end_time="23:00",
    ),
    "dispatched_reserves": DataMinerFeedConfig(
        feed_name="dispatched_reserves",
        display_name="Dispatched Reserves",
        category="Ancillary Services",
        posting_frequency="Every 5 minutes",
        retention_time="30 days",
        columns=(
            "area",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "market_clearing_price",
            "reliability_requirement",
            "reserve_quantity",
            "reserve_requirement",
            "reserve_type",
            "shortage_indicator",
            "extended_requirement",
            "mw_adjustment",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "area",
            "reserve_type",
        ),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=(
            "market_clearing_price",
            "reliability_requirement",
            "reserve_quantity",
            "reserve_requirement",
            "extended_requirement",
            "mw_adjustment",
        ),
        bool_columns=("shortage_indicator",),
        text_columns=("area", "reserve_type"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=2,
    ),
    "five_min_solar_generation": DataMinerFeedConfig(
        feed_name="five_min_solar_generation",
        display_name="Five Minute Solar Generation",
        category="Generation",
        posting_frequency="Every 5 minutes",
        retention_time="30 days",
        columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "solar_generation_mw",
        ),
        primary_key=("datetime_beginning_utc",),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("solar_generation_mw",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=2,
    ),
    "load_frcstd_hist": DataMinerFeedConfig(
        feed_name="load_frcstd_hist",
        display_name="Historical Load Forecasts",
        category="Load Forecast",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "evaluated_at_ept",
            "evaluated_at_utc",
            "forecast_area",
            "forecast_hour_beginning_ept",
            "forecast_hour_beginning_utc",
            "forecast_load_mw",
        ),
        primary_key=(
            "evaluated_at_utc",
            "evaluated_at_ept",
            "forecast_hour_beginning_utc",
            "forecast_hour_beginning_ept",
            "forecast_area",
        ),
        datetime_columns=(
            "evaluated_at_ept",
            "evaluated_at_utc",
            "forecast_hour_beginning_ept",
            "forecast_hour_beginning_utc",
        ),
        numeric_columns=("forecast_load_mw",),
        text_columns=("forecast_area",),
        datetime_filter_field="forecast_hour_beginning_ept",
        default_lookback_days=10,
        default_lookahead_days=7,
        default_end_time="23:00",
    ),
    "hrl_load_metered": DataMinerFeedConfig(
        feed_name="hrl_load_metered",
        display_name="Hourly Load: Metered",
        category="Load",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "is_verified",
            "load_area",
            "mkt_region",
            "mw",
            "nerc_region",
            "zone",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "nerc_region",
            "mkt_region",
            "zone",
            "load_area",
            "is_verified",
        ),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("mw",),
        bool_columns=("is_verified",),
        text_columns=("load_area", "mkt_region", "nerc_region", "zone"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
        default_end_time="23:00",
    ),
    "hrl_load_prelim": DataMinerFeedConfig(
        feed_name="hrl_load_prelim",
        display_name="Hourly Load: Preliminary",
        category="Load",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "load_area",
            "prelim_load_avg_hourly",
        ),
        primary_key=("datetime_beginning_utc", "load_area"),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
        ),
        numeric_columns=("prelim_load_avg_hourly",),
        text_columns=("load_area",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
        default_end_time="23:00",
    ),
    "hrl_dmd_bids": DataMinerFeedConfig(
        feed_name="hrl_dmd_bids",
        display_name="Hourly Demand Bid Data",
        category="Bid and Offer Data",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "hrly_da_demand_bid",
            "area",
        ),
        primary_key=("datetime_beginning_utc", "datetime_beginning_ept", "area"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("hrly_da_demand_bid",),
        text_columns=("area",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=7,
        default_lookahead_days=1,
        default_end_time="23:00",
    ),
    "frcstd_gen_outages": DataMinerFeedConfig(
        feed_name="frcstd_gen_outages",
        display_name="Forecasted Generation Outages",
        category="Generation",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "forecast_date",
            "forecast_execution_date_ept",
            "forecast_gen_outage_mw_other",
            "forecast_gen_outage_mw_rto",
            "forecast_gen_outage_mw_west",
        ),
        primary_key=("forecast_execution_date_ept", "forecast_date"),
        date_columns=("forecast_date", "forecast_execution_date_ept"),
        numeric_columns=(
            "forecast_gen_outage_mw_other",
            "forecast_gen_outage_mw_rto",
            "forecast_gen_outage_mw_west",
        ),
        datetime_filter_field="forecast_execution_date_ept",
        default_lookback_days=10,
        default_lookahead_days=7,
    ),
    "rt_dispatch_reserves": DataMinerFeedConfig(
        feed_name="rt_dispatch_reserves",
        display_name="Real-Time Dispatched Reserves",
        category="Ancillary Services",
        posting_frequency="Daily On Business Days",
        retention_time="Indefinitely",
        columns=(
            "area",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "deficit_mw",
            "extended_reqmt_mw",
            "mkt_day",
            "reliability_reqmt_mw",
            "reserve_reqmt_mw",
            "reserve_type",
            "total_reserve_mw",
            "additional_extended_reqmt_mw",
        ),
        primary_key=(
            "mkt_day",
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "area",
            "reserve_type",
        ),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        date_columns=("mkt_day",),
        numeric_columns=(
            "deficit_mw",
            "extended_reqmt_mw",
            "reliability_reqmt_mw",
            "reserve_reqmt_mw",
            "total_reserve_mw",
            "additional_extended_reqmt_mw",
        ),
        text_columns=("area", "reserve_type"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
    ),
    "reserve_market_results": DataMinerFeedConfig(
        feed_name="reserve_market_results",
        display_name="Real-Time Ancillary Service Market Results",
        category="Ancillary Services",
        posting_frequency="Daily on Business Days",
        retention_time="Indefinitely",
        columns=(
            "as_mw",
            "as_req_mw",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "dsr_as_mw",
            "ircmwt2",
            "locale",
            "mcp",
            "mcp_capped",
            "nsr_mw",
            "reg_ccp",
            "reg_pcp",
            "regd_mw",
            "service",
            "ss_mw",
            "tier1_mw",
            "total_mw",
        ),
        primary_key=("datetime_beginning_utc", "locale", "service"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=(
            "as_mw",
            "as_req_mw",
            "dsr_as_mw",
            "ircmwt2",
            "mcp",
            "mcp_capped",
            "nsr_mw",
            "reg_ccp",
            "reg_pcp",
            "regd_mw",
            "ss_mw",
            "tier1_mw",
            "total_mw",
        ),
        text_columns=("locale", "service"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
    ),
    "rt_default_mv_override": DataMinerFeedConfig(
        feed_name="rt_default_mv_override",
        display_name="Real-Time Default Marginal Value Override",
        category="Constraints",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "constraint_name",
            "contingency_description",
            "default_transmission_constraint_penalty_factor",
            "effective_day",
            "posted_day",
            "terminate_day",
        ),
        primary_key=("constraint_name", "contingency_description", "effective_day"),
        date_columns=("effective_day", "posted_day", "terminate_day"),
        numeric_columns=("default_transmission_constraint_penalty_factor",),
        text_columns=("constraint_name", "contingency_description"),
        datetime_filter_field="posted_day",
        default_lookback_days=10,
    ),
    "rt_marginal_value": DataMinerFeedConfig(
        feed_name="rt_marginal_value",
        display_name="Real-Time Marginal Value",
        category="Constraints",
        posting_frequency="Daily on Business Days",
        retention_time="Indefinitely",
        columns=(
            "contingency_facility",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "monitored_facility",
            "shadow_price",
            "limit_control_percentage",
            "transmission_constraint_penalty_factor",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "monitored_facility",
            "contingency_facility",
        ),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
        ),
        numeric_columns=(
            "shadow_price",
            "limit_control_percentage",
            "transmission_constraint_penalty_factor",
        ),
        text_columns=("contingency_facility", "monitored_facility"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
    ),
    "rt_short_term_mv_override": DataMinerFeedConfig(
        feed_name="rt_short_term_mv_override",
        display_name="Real-Time Short-Term Marginal Value Override",
        category="Constraints",
        posting_frequency="Hourly",
        retention_time="7 years",
        columns=(
            "constraint_name",
            "contingency_description",
            "effective_datetime_ept",
            "effective_datetime_utc",
            "posted_day",
            "short_term_transmission_constraint_penalty_factor",
            "terminate_datetime_ept",
            "terminate_datetime_utc",
        ),
        primary_key=(
            "constraint_name",
            "contingency_description",
            "effective_datetime_utc",
        ),
        datetime_columns=(
            "effective_datetime_ept",
            "effective_datetime_utc",
            "terminate_datetime_ept",
            "terminate_datetime_utc",
        ),
        date_columns=("posted_day",),
        numeric_columns=("short_term_transmission_constraint_penalty_factor",),
        text_columns=("constraint_name", "contingency_description"),
        datetime_filter_field="posted_day",
        default_lookback_days=3,
    ),
    "rt_unverified_hrl_lmps": DataMinerFeedConfig(
        feed_name="rt_unverified_hrl_lmps",
        display_name="Real-Time Unverified Hourly LMPs",
        category="Locational Marginal Prices",
        posting_frequency="Hourly",
        retention_time="30 days",
        columns=(
            "congestion_price_rt",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "marginal_loss_price_rt",
            "pnode_name",
            "total_lmp_rt",
            "type",
        ),
        primary_key=("datetime_beginning_utc", "pnode_name", "type"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=(
            "congestion_price_rt",
            "marginal_loss_price_rt",
            "total_lmp_rt",
        ),
        text_columns=("pnode_name", "type"),
        datetime_filter_field="datetime_beginning_ept",
        pricing_node_types=DEFAULT_PRICING_NODE_TYPES,
        default_lookback_days=2,
        default_end_time="23:00",
    ),
    "load_frcstd_7_day": DataMinerFeedConfig(
        feed_name="load_frcstd_7_day",
        display_name="Seven-Day Load Forecast",
        category="Load Forecast",
        posting_frequency="Hourly",
        retention_time="None",
        columns=(
            "evaluated_at_datetime_ept",
            "evaluated_at_datetime_utc",
            "forecast_area",
            "forecast_datetime_beginning_ept",
            "forecast_datetime_beginning_utc",
            "forecast_datetime_ending_ept",
            "forecast_datetime_ending_utc",
            "forecast_load_mw",
        ),
        primary_key=(
            "evaluated_at_datetime_utc",
            "forecast_datetime_beginning_utc",
            "forecast_area",
        ),
        datetime_columns=(
            "evaluated_at_datetime_ept",
            "evaluated_at_datetime_utc",
            "forecast_datetime_beginning_ept",
            "forecast_datetime_beginning_utc",
            "forecast_datetime_ending_ept",
            "forecast_datetime_ending_utc",
        ),
        numeric_columns=("forecast_load_mw",),
        text_columns=("forecast_area",),
        default_lookback_days=0,
        default_lookahead_days=0,
        hot_retention_days=90,
        hot_retention_column="evaluated_at_datetime_utc",
    ),
    "ops_sum_frcst_peak_area": DataMinerFeedConfig(
        feed_name="ops_sum_frcst_peak_area",
        display_name="Operations Summary - Projected Area Statistics at Peak",
        category="System Information",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "area",
            "generated_at_ept",
            "internal_scheduled_capacity",
            "pjm_load_forecast",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
            "unscheduled_steam_capacity",
        ),
        primary_key=(
            "projected_peak_datetime_utc",
            "generated_at_ept",
            "area",
        ),
        datetime_columns=(
            "generated_at_ept",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
        ),
        numeric_columns=(
            "internal_scheduled_capacity",
            "pjm_load_forecast",
            "unscheduled_steam_capacity",
        ),
        text_columns=("area",),
        datetime_filter_field="projected_peak_datetime_ept",
        default_lookback_days=3,
        default_end_time="23:59",
    ),
    "ops_sum_frcst_peak_rto": DataMinerFeedConfig(
        feed_name="ops_sum_frcst_peak_rto",
        display_name="Operations Summary - Projected RTO Statistics at Peak",
        category="System Information",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "area",
            "capacity_adjustments",
            "generated_at_ept",
            "internal_scheduled_capacity",
            "load_forecast",
            "operating_reserve",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
            "scheduled_tie_flow_total",
            "total_scheduled_capacity",
            "unscheduled_steam_capacity",
        ),
        primary_key=(
            "projected_peak_datetime_utc",
            "generated_at_ept",
            "area",
        ),
        datetime_columns=(
            "generated_at_ept",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
        ),
        numeric_columns=(
            "capacity_adjustments",
            "internal_scheduled_capacity",
            "load_forecast",
            "operating_reserve",
            "scheduled_tie_flow_total",
            "total_scheduled_capacity",
            "unscheduled_steam_capacity",
        ),
        text_columns=("area",),
        datetime_filter_field="projected_peak_datetime_ept",
        default_lookback_days=3,
        default_end_time="23:59",
    ),
    "ops_sum_prev_period": DataMinerFeedConfig(
        feed_name="ops_sum_prev_period",
        display_name="Operations Summary - Actual Operational Statistics",
        category="System Information",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "actual_load",
            "area",
            "area_load_forecast",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "dispatch_rate",
            "generated_at_ept",
        ),
        primary_key=(
            "datetime_beginning_utc",
            "generated_at_ept",
            "area",
        ),
        datetime_columns=(
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "datetime_ending_ept",
            "datetime_ending_utc",
            "generated_at_ept",
        ),
        numeric_columns=(
            "actual_load",
            "area_load_forecast",
            "dispatch_rate",
        ),
        text_columns=("area",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=3,
        default_lookahead_days=-1,
        default_end_time="23:00",
    ),
    "ops_sum_prjctd_tie_flow": DataMinerFeedConfig(
        feed_name="ops_sum_prjctd_tie_flow",
        display_name="Operations Summary - Projected Scheduled Tie Flow",
        category="System Information",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "generated_at_ept",
            "interface",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
            "scheduled_tie_flow",
        ),
        primary_key=(
            "projected_peak_datetime_utc",
            "generated_at_ept",
            "interface",
        ),
        datetime_columns=(
            "generated_at_ept",
            "projected_peak_datetime_ept",
            "projected_peak_datetime_utc",
        ),
        numeric_columns=("scheduled_tie_flow",),
        text_columns=("interface",),
        datetime_filter_field="projected_peak_datetime_ept",
        default_lookback_days=3,
        default_end_time="23:59",
    ),
    "hourly_solar_power_forecast": DataMinerFeedConfig(
        feed_name="hourly_solar_power_forecast",
        display_name="Hourly Solar Power Forecast",
        category="Generation",
        posting_frequency="Every 10 minutes",
        retention_time="30 days",
        columns=(
            "evaluated_at_utc",
            "evaluated_at_ept",
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "datetime_ending_utc",
            "datetime_ending_ept",
            "solar_forecast_mwh",
            "solar_forecast_btm_mwh",
        ),
        primary_key=(
            "evaluated_at_utc",
            "datetime_beginning_utc",
        ),
        datetime_columns=(
            "evaluated_at_utc",
            "evaluated_at_ept",
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "datetime_ending_utc",
            "datetime_ending_ept",
        ),
        numeric_columns=("solar_forecast_mwh", "solar_forecast_btm_mwh"),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=0,
        default_lookahead_days=2,
        default_end_time="23:00",
        hot_retention_days=90,
        hot_retention_column="evaluated_at_utc",
    ),
    "hourly_wind_power_forecast": DataMinerFeedConfig(
        feed_name="hourly_wind_power_forecast",
        display_name="Hourly Wind Power Forecast",
        category="Generation",
        posting_frequency="Every 10 minutes",
        retention_time="30 days",
        columns=(
            "evaluated_at_utc",
            "evaluated_at_ept",
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "datetime_ending_utc",
            "datetime_ending_ept",
            "wind_forecast_mwh",
        ),
        primary_key=(
            "evaluated_at_utc",
            "datetime_beginning_utc",
        ),
        datetime_columns=(
            "evaluated_at_utc",
            "evaluated_at_ept",
            "datetime_beginning_utc",
            "datetime_beginning_ept",
            "datetime_ending_utc",
            "datetime_ending_ept",
        ),
        numeric_columns=("wind_forecast_mwh",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=0,
        default_lookahead_days=2,
        default_end_time="23:00",
        hot_retention_days=90,
        hot_retention_column="evaluated_at_utc",
    ),
    "gen_outages_by_type": DataMinerFeedConfig(
        feed_name="gen_outages_by_type",
        display_name="Generation Outage for Seven Days by Type",
        category="Generation",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "forced_outages_mw",
            "forecast_date",
            "forecast_execution_date_ept",
            "maintenance_outages_mw",
            "planned_outages_mw",
            "region",
            "total_outages_mw",
        ),
        primary_key=("forecast_execution_date_ept", "forecast_date", "region"),
        date_columns=("forecast_date", "forecast_execution_date_ept"),
        numeric_columns=(
            "forced_outages_mw",
            "maintenance_outages_mw",
            "planned_outages_mw",
            "total_outages_mw",
        ),
        text_columns=("region",),
        datetime_filter_field="forecast_execution_date_ept",
        default_lookback_days=10,
        default_lookahead_days=7,
    ),
    "solar_gen": DataMinerFeedConfig(
        feed_name="solar_gen",
        display_name="Solar Generation",
        category="Generation",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "area",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "solar_generation_mw",
        ),
        primary_key=("datetime_beginning_utc", "area"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("solar_generation_mw",),
        text_columns=("area",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
    ),
    "wind_gen": DataMinerFeedConfig(
        feed_name="wind_gen",
        display_name="Wind Generation",
        category="Generation",
        posting_frequency="Daily",
        retention_time="Indefinitely",
        columns=(
            "area",
            "datetime_beginning_ept",
            "datetime_beginning_utc",
            "wind_generation_mw",
        ),
        primary_key=("datetime_beginning_utc", "area"),
        datetime_columns=("datetime_beginning_ept", "datetime_beginning_utc"),
        numeric_columns=("wind_generation_mw",),
        text_columns=("area",),
        datetime_filter_field="datetime_beginning_ept",
        default_lookback_days=10,
    ),
}
