with product_aliases(
    source_priority,
    source,
    match_type,
    pattern,
    product_code,
    option_type,
    marex_product
) as (
    values
        (1, 'nav', 'regex', '^ICE NGAS HH SWG DLY DAY-[0-9]+$', 'HHD', null, 'HENRY SWING'),
        (2, 'nav', 'exact', 'ICE NGAS HH SWING DAILY', 'HHD', null, 'HENRY SWING'),
        (3, 'nav', 'exact', 'NATURAL GAS', 'NG', null, 'NAT GAS'),
        (4, 'nav', 'exact', 'GLOBEX NATURAL GAS LD', 'HH', null, 'NAT GAS LAST DAY FINAN'),
        (5, 'nav', 'exact', 'NYMEX HENRY HUB FINANCIAL LDO', 'HH', null, 'NAT GAS LAST DAY FINAN'),
        (6, 'nav', 'exact', 'NYMEX HENRY HUB NATURAL GAS', 'HP', null, 'HENRY HUB FINANCIAL'),
        (7, 'nav', 'exact', 'HENRY PENULTIMATE NATURAL GAS', 'HP', null, 'HENRY HUB FINANCIAL'),
        (8, 'nav', 'exact', 'NATURAL GAS LD1 FUTURE', 'H', null, 'HENRY LD1 FIXED'),
        (9, 'nav', 'exact', 'HENRY HUB NATURAL GAS', 'H', null, 'HENRY LD1 FIXED'),
        (10, 'nav', 'exact', 'ICE PHH', 'PHH', null, 'HENRY PENULT FIXED'),
        (11, 'nav', 'exact', 'ICE PHE', 'PHE', 'option', 'HENRY PENULT FIXED'),
        (12, 'nav', 'exact', 'ICE HH EQ', 'PHE', 'option', 'HENRY PENULT FIXED'),
        (13, 'nav', 'exact', 'ICE NGAS PEN HENRY HUB', 'PHE', 'option', 'HENRY PENULT FIXED'),
        (14, 'nav', 'exact', 'NYM EUR NATURAL GAS', 'LN', 'option', 'EUR NAT GAS'),
        (15, 'nav', 'exact', 'NATURAL GAS CLEARPORT', 'LN', 'option', 'EUR NAT GAS'),
        (16, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 1', 'LN1', 'option', 'NAT GAS FIN WKLY WK1'),
        (17, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 2', 'LN2', 'option', 'NAT GAS FIN WKLY WK2'),
        (18, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 3', 'LN3', 'option', 'NAT GAS FIN WKLY WK3'),
        (19, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 4', 'LN4', 'option', 'NAT GAS FIN WKLY WK4'),
        (20, 'nav', 'exact', 'NATURAL GAS FINANCIAL WEEK 5', 'LN5', 'option', 'NAT GAS FIN WKLY WK5'),
        (21, 'nav', 'exact', 'NATURAL GAS 3M CSO', 'G3', 'option', 'NAT GAS CAL SPRD FIN 3MO'),
        (22, 'nav', 'exact', 'NATURAL GAS FINANCIAL 1M SO', 'G4', 'option', 'NAT GAS FINAN 1 MNTH SPRD'),
        (23, 'nav', 'exact', 'NATURAL GAS 1M CSO', 'G4', 'option', 'NAT GAS FINAN 1 MNTH SPRD'),
        (24, 'nav', 'exact', 'ICE PJM WH RTD', 'PDP', null, 'PJM WH REAL T PEAK DAILY'),
        (25, 'nav', 'exact', 'ICE PWA', 'PWA', null, 'PJM W HUB RT PEAK DAILY'),
        (26, 'nav', 'exact', 'ICE PJMWHPKDAY', 'PDA', null, 'PJM WEST DAY AHEAD PK DA'),
        (27, 'nav', 'exact', 'ICE PJL', 'PJL', null, 'PJM WST HUB D APDM FP FU'),
        (28, 'nav', 'exact', 'ICE PDA', 'PDA', null, 'PJM WEST DAY AHEAD PK DA'),
        (29, 'nav', 'exact', 'ICE PJL DAILY', 'PJL', null, 'PJM WST HUB D APDM FP FU'),
        (30, 'nav', 'regex', '^ICE (PJM MINI|MINIPJMRT|PJM WHREAL TYM PK MINI)([-_][0-9]+)?$', 'PMI', null, 'PJM WST HUB REAL PEAK FIXED'),
        (31, 'nav', 'exact', 'ICE PJM WHRT PEAK OPT_4096', 'P1X', 'option', 'PJM WEST HUB RT'),
        (32, 'nav', 'regex', '^ICE PJM OFF PK[-_][0-9]+$', 'OPJ', null, 'PJM WST HUB REAL OFF PEAK FIXED'),
        (33, 'nav', 'exact', 'ICE ERA', 'ERA', null, 'EMINI ERCOT 345RT PK DAILY'),
        (34, 'nav', 'exact', 'ERCOT N 345 KV RT PEAK DLY', 'ERN', null, 'ERCOT NORTH PEAK FIXED'),
        (35, 'nav', 'exact', 'ICE END', 'END', null, null),
        (36, 'nav', 'regex', '^ICE ERCOT NORTH 345KV 7X8[-_][0-9]+$', 'ECI', null, 'ERCT NORTH 345KVRT 7x8 FXD'),
        (37, 'nav', 'regex', '^(ISO ENG MASS HUB D-PK-[0-9]+|ICE NEPOOL PK MNTH-[0-9]+)$', 'NEP', null, 'ISO MASS HUB PEAK FIXED'),
        (38, 'nav', 'regex', '^ICE SP 15 PEAK([_-][0-9]+)?$', 'SPM', null, 'CAISO SP15 PEAK FIXED'),
        (39, 'nav', 'regex', '^ICE NP 15 PEAK([_-][0-9]+)?$', 'NPM', null, 'CAISO NP15 PEAK FIXED'),
        (40, 'nav', 'regex', '^ICE MID-C PEAK([_-][0-9]+)?$', 'MDC', null, 'MID C FIN PEAK ELEC'),
        (41, 'nav', 'exact', 'AB NIT BASIS FUTURE', 'AEC', null, 'AB NIT BASIS'),
        (42, 'nav', 'exact', 'ICE ALQCTYGTSW', 'ALQ', null, 'ALGONQUIN CITYGATES BASIS'),
        (43, 'nav', 'exact', 'ICE CIG ROCKIES BASIS', 'CRI', null, 'CIG ROCKIES BASIS'),
        (44, 'nav', 'exact', 'ICE CHICAGO BASIS FUT', 'DGD', null, 'CHICAGO BASIS'),
        (45, 'nav', 'exact', 'ICE EASTERN GAS SOUTH BASIS FU', 'DOM', null, 'DOMINION SOUTH BASIS'),
        (46, 'nav', 'exact', 'ICE HSC BASIS', 'HXS', null, 'HSC BASIS'),
        (47, 'nav', 'exact', 'NGPL TXOK BASIS FUTURE', 'NTO', null, 'NGPL TXOK BASIS'),
        (48, 'nav', 'exact', 'ICE NGAS NYM NWP RK', 'NWR', null, 'NAT GAS B/S FERC;ROCKIES'),
        (49, 'nav', 'exact', 'ICE NGAS NYM PG&E', 'PGE', null, 'PG&E CITYGATE BASIS'),
        (50, 'nav', 'exact', 'ICE TETCO SWP', 'TMT', null, 'TETCO M3 BASIS'),
        (51, 'nav', 'exact', 'ICE TRANSCO STATION 85 ZONE 4', 'TRZ', null, 'TRANSCO 85 Z4 BASIS'),
        (52, 'nav', 'exact', 'ICE TCOZN4BASI', 'TRZ', null, 'TRANSCO 85 Z4 BASIS'),
        (53, 'nav', 'exact', 'ICE SDP', 'SDP', null, null)
),

FINAL as (
    select * from product_aliases
)

select *
from FINAL
