-- Source-table DDL for Meteologica Western Hub ECMWF ENS DA price forecast.
--
-- This file is disabled as a dbt model in dbt_project.yml. It is retained as
-- operator reference SQL only. Read-only dbt credentials cannot run this.
-- Apply it manually with the helios_admin role before scheduling
-- backend.orchestration.power.pjm.meteologica_da_price_forecast.

CREATE TABLE IF NOT EXISTS meteologica.usa_pjm_western_hub_da_power_price_forecast_ecmwf_ens_hourly (
    content_id INTEGER NOT NULL,
    content_name VARCHAR NOT NULL,
    update_id VARCHAR NOT NULL,
    issue_date TIMESTAMPTZ,
    forecast_period_start TIMESTAMP NOT NULL,
    forecast_period_end TIMESTAMP,
    utc_offset_from VARCHAR,
    utc_offset_to VARCHAR,
    average_price DOUBLE PRECISION,
    bottom_price DOUBLE PRECISION,
    top_price DOUBLE PRECISION,
    ens_00_price DOUBLE PRECISION,
    ens_01_price DOUBLE PRECISION,
    ens_02_price DOUBLE PRECISION,
    ens_03_price DOUBLE PRECISION,
    ens_04_price DOUBLE PRECISION,
    ens_05_price DOUBLE PRECISION,
    ens_06_price DOUBLE PRECISION,
    ens_07_price DOUBLE PRECISION,
    ens_08_price DOUBLE PRECISION,
    ens_09_price DOUBLE PRECISION,
    ens_10_price DOUBLE PRECISION,
    ens_11_price DOUBLE PRECISION,
    ens_12_price DOUBLE PRECISION,
    ens_13_price DOUBLE PRECISION,
    ens_14_price DOUBLE PRECISION,
    ens_15_price DOUBLE PRECISION,
    ens_16_price DOUBLE PRECISION,
    ens_17_price DOUBLE PRECISION,
    ens_18_price DOUBLE PRECISION,
    ens_19_price DOUBLE PRECISION,
    ens_20_price DOUBLE PRECISION,
    ens_21_price DOUBLE PRECISION,
    ens_22_price DOUBLE PRECISION,
    ens_23_price DOUBLE PRECISION,
    ens_24_price DOUBLE PRECISION,
    ens_25_price DOUBLE PRECISION,
    ens_26_price DOUBLE PRECISION,
    ens_27_price DOUBLE PRECISION,
    ens_28_price DOUBLE PRECISION,
    ens_29_price DOUBLE PRECISION,
    ens_30_price DOUBLE PRECISION,
    ens_31_price DOUBLE PRECISION,
    ens_32_price DOUBLE PRECISION,
    ens_33_price DOUBLE PRECISION,
    ens_34_price DOUBLE PRECISION,
    ens_35_price DOUBLE PRECISION,
    ens_36_price DOUBLE PRECISION,
    ens_37_price DOUBLE PRECISION,
    ens_38_price DOUBLE PRECISION,
    ens_39_price DOUBLE PRECISION,
    ens_40_price DOUBLE PRECISION,
    ens_41_price DOUBLE PRECISION,
    ens_42_price DOUBLE PRECISION,
    ens_43_price DOUBLE PRECISION,
    ens_44_price DOUBLE PRECISION,
    ens_45_price DOUBLE PRECISION,
    ens_46_price DOUBLE PRECISION,
    ens_47_price DOUBLE PRECISION,
    ens_48_price DOUBLE PRECISION,
    ens_49_price DOUBLE PRECISION,
    ens_50_price DOUBLE PRECISION,
    source_timezone VARCHAR,
    source_unit VARCHAR,
    scrape_run_at_utc TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (content_id, update_id, forecast_period_start)
);
