/*
Criterion watchlists.

Source system: Criterion Snowflake PRODUCTION.PIPELINES. The frontend reads
plant nominations and plant-point metadata from:

- PRODUCTION.PIPELINES.METADATA
- PRODUCTION.PIPELINES.NOMINATION_POINTS

Postgres stores only app-owned saved selections.

Primary grain:
- helioscta_app.criterion_watchlists: one row per shared saved Criterion
  watchlist. watchlist_type identifies the workflow, for example
  pjm_power_plants.
- helioscta_app.criterion_watchlist_items: one row per watchlist x entity_type
  x Criterion source table x source_key membership.

For nomination_point items, source_key is tsp_short || '|' || metadata_id.
tsp_short and metadata_id are retained as typed join keys for Snowflake
validation and filtering. display_snapshot and source_attrs are non-canonical
Criterion metadata snapshots for UI display and audit context.

Saved item membership is canonical. filter_config is retained only for UI
defaults and staging filter context, not as the selected item set.
*/

CREATE SCHEMA IF NOT EXISTS helioscta_app;

DO $$
BEGIN
  IF to_regclass('helioscta_app.criterion_watchlists') IS NULL
     AND to_regclass('helioscta_app.criterion_power_plant_watchlists') IS NOT NULL THEN
    ALTER TABLE helioscta_app.criterion_power_plant_watchlists
      RENAME TO criterion_watchlists;
  END IF;

  IF to_regclass('helioscta_app.criterion_watchlist_items') IS NULL
     AND to_regclass('helioscta_app.criterion_power_plant_watchlist_points') IS NOT NULL THEN
    ALTER TABLE helioscta_app.criterion_power_plant_watchlist_points
      RENAME TO criterion_watchlist_items;
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS helioscta_app.criterion_watchlists (
  watchlist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  display_name text NOT NULL,
  watchlist_type text NOT NULL DEFAULT 'pjm_power_plants',
  source_system text NOT NULL DEFAULT 'criterion',
  filter_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT chk_criterion_watchlists_slug_nonempty
    CHECK (length(trim(slug)) > 0),
  CONSTRAINT chk_criterion_watchlists_display_name_nonempty
    CHECK (length(trim(display_name)) > 0),
  CONSTRAINT chk_criterion_watchlists_type_nonempty
    CHECK (length(trim(watchlist_type)) > 0),
  CONSTRAINT chk_criterion_watchlists_source_system_nonempty
    CHECK (length(trim(source_system)) > 0),
  CONSTRAINT chk_criterion_watchlists_filter_config_object
    CHECK (jsonb_typeof(filter_config) = 'object')
);

ALTER TABLE helioscta_app.criterion_watchlists
  ADD COLUMN IF NOT EXISTS watchlist_type text,
  ADD COLUMN IF NOT EXISTS source_system text;

UPDATE helioscta_app.criterion_watchlists
SET watchlist_type = 'pjm_power_plants'
WHERE watchlist_type IS NULL
   OR length(trim(watchlist_type)) = 0;

UPDATE helioscta_app.criterion_watchlists
SET source_system = 'criterion'
WHERE source_system IS NULL
   OR length(trim(source_system)) = 0;

ALTER TABLE helioscta_app.criterion_watchlists
  ALTER COLUMN watchlist_type SET DEFAULT 'pjm_power_plants',
  ALTER COLUMN watchlist_type SET NOT NULL,
  ALTER COLUMN source_system SET DEFAULT 'criterion',
  ALTER COLUMN source_system SET NOT NULL;

ALTER TABLE helioscta_app.criterion_watchlists
  DROP CONSTRAINT IF EXISTS chk_criterion_power_plant_watchlists_slug_nonempty,
  DROP CONSTRAINT IF EXISTS chk_criterion_power_plant_watchlists_display_name_nonempty,
  DROP CONSTRAINT IF EXISTS chk_criterion_power_plant_watchlists_filter_config_object;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
      AND conname = 'chk_criterion_watchlists_slug_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlists
      ADD CONSTRAINT chk_criterion_watchlists_slug_nonempty
      CHECK (length(trim(slug)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
      AND conname = 'chk_criterion_watchlists_display_name_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlists
      ADD CONSTRAINT chk_criterion_watchlists_display_name_nonempty
      CHECK (length(trim(display_name)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
      AND conname = 'chk_criterion_watchlists_type_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlists
      ADD CONSTRAINT chk_criterion_watchlists_type_nonempty
      CHECK (length(trim(watchlist_type)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
      AND conname = 'chk_criterion_watchlists_source_system_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlists
      ADD CONSTRAINT chk_criterion_watchlists_source_system_nonempty
      CHECK (length(trim(source_system)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
      AND conname = 'chk_criterion_watchlists_filter_config_object'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlists
      ADD CONSTRAINT chk_criterion_watchlists_filter_config_object
      CHECK (jsonb_typeof(filter_config) = 'object');
  END IF;
END;
$$;

DO $$
DECLARE
  current_pk text;
BEGIN
  SELECT conname
  INTO current_pk
  FROM pg_constraint
  WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
    AND contype = 'p';

  IF current_pk IS NOT NULL
     AND current_pk <> 'criterion_watchlists_pkey'
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conrelid = 'helioscta_app.criterion_watchlists'::regclass
         AND conname = 'criterion_watchlists_pkey'
     ) THEN
    EXECUTE format(
      'ALTER TABLE helioscta_app.criterion_watchlists RENAME CONSTRAINT %I TO criterion_watchlists_pkey',
      current_pk
    );
  END IF;
END;
$$;

DROP INDEX IF EXISTS helioscta_app.uq_criterion_power_plant_watchlists_active_slug;
DROP INDEX IF EXISTS helioscta_app.idx_criterion_power_plant_watchlists_active_name;

CREATE UNIQUE INDEX IF NOT EXISTS uq_criterion_watchlists_active_type_slug
  ON helioscta_app.criterion_watchlists (watchlist_type, slug)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_criterion_watchlists_type_active_name
  ON helioscta_app.criterion_watchlists (watchlist_type, is_active, display_name);

CREATE TABLE IF NOT EXISTS helioscta_app.criterion_watchlist_items (
  watchlist_id integer NOT NULL,
  entity_type text NOT NULL DEFAULT 'nomination_point',
  source_table text NOT NULL DEFAULT 'PRODUCTION.PIPELINES.NOMINATION_POINTS',
  source_key text NOT NULL,
  tsp_short text,
  metadata_id text,
  display_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_attrs jsonb NOT NULL DEFAULT '{}'::jsonb,
  display_name_override text,
  sort_order integer,
  created_by varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT criterion_watchlist_items_pkey
    PRIMARY KEY (watchlist_id, entity_type, source_table, source_key),
  CONSTRAINT fk_criterion_watchlist_items_watchlist
    FOREIGN KEY (watchlist_id)
    REFERENCES helioscta_app.criterion_watchlists (watchlist_id)
    ON DELETE CASCADE,
  CONSTRAINT chk_criterion_watchlist_items_entity_type_nonempty
    CHECK (length(trim(entity_type)) > 0),
  CONSTRAINT chk_criterion_watchlist_items_source_table_nonempty
    CHECK (length(trim(source_table)) > 0),
  CONSTRAINT chk_criterion_watchlist_items_source_key_nonempty
    CHECK (length(trim(source_key)) > 0),
  CONSTRAINT chk_criterion_watchlist_items_display_snapshot_object
    CHECK (jsonb_typeof(display_snapshot) = 'object'),
  CONSTRAINT chk_criterion_watchlist_items_source_attrs_object
    CHECK (jsonb_typeof(source_attrs) = 'object'),
  CONSTRAINT chk_criterion_watchlist_items_nomination_key
    CHECK (
      entity_type <> 'nomination_point'
      OR (
        tsp_short IS NOT NULL
        AND length(trim(tsp_short)) > 0
        AND metadata_id IS NOT NULL
        AND length(trim(metadata_id)) > 0
      )
    )
);

ALTER TABLE helioscta_app.criterion_watchlist_items
  ADD COLUMN IF NOT EXISTS entity_type text,
  ADD COLUMN IF NOT EXISTS source_key text,
  ADD COLUMN IF NOT EXISTS display_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS source_attrs jsonb;

UPDATE helioscta_app.criterion_watchlist_items
SET entity_type = 'nomination_point'
WHERE entity_type IS NULL
   OR length(trim(entity_type)) = 0;

UPDATE helioscta_app.criterion_watchlist_items
SET source_key = tsp_short || '|' || metadata_id
WHERE (source_key IS NULL OR length(trim(source_key)) = 0)
  AND tsp_short IS NOT NULL
  AND metadata_id IS NOT NULL;

DO $$
DECLARE
  has_legacy_snapshot_columns boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'helioscta_app'
      AND table_name = 'criterion_watchlist_items'
      AND column_name = 'state_abb'
  )
  INTO has_legacy_snapshot_columns;

  IF has_legacy_snapshot_columns THEN
    UPDATE helioscta_app.criterion_watchlist_items
    SET display_snapshot = CASE
          WHEN display_snapshot IS NULL OR display_snapshot = '{}'::jsonb THEN
            jsonb_strip_nulls(
              jsonb_build_object(
                'state', state_abb,
                'pipeline', pipeline_name,
                'location', location_name,
                'locationId', location_id,
                'county', county_name,
                'connectingEntity', connecting_entity
              )
            )
          ELSE display_snapshot
        END,
        source_attrs = CASE
          WHEN source_attrs IS NULL OR source_attrs = '{}'::jsonb THEN
            jsonb_strip_nulls(
              jsonb_build_object(
                'categoryShort', category_short,
                'locQtiShort', loc_qti_short,
                'recDelSign', rec_del_sign
              )
            )
          ELSE source_attrs
        END;
  END IF;
END;
$$;

UPDATE helioscta_app.criterion_watchlist_items
SET display_snapshot = '{}'::jsonb
WHERE display_snapshot IS NULL;

UPDATE helioscta_app.criterion_watchlist_items
SET source_attrs = '{}'::jsonb
WHERE source_attrs IS NULL;

ALTER TABLE helioscta_app.criterion_watchlist_items
  ALTER COLUMN entity_type SET DEFAULT 'nomination_point',
  ALTER COLUMN entity_type SET NOT NULL,
  ALTER COLUMN source_key SET NOT NULL,
  ALTER COLUMN display_snapshot SET DEFAULT '{}'::jsonb,
  ALTER COLUMN display_snapshot SET NOT NULL,
  ALTER COLUMN source_attrs SET DEFAULT '{}'::jsonb,
  ALTER COLUMN source_attrs SET NOT NULL;

ALTER TABLE helioscta_app.criterion_watchlist_items
  DROP CONSTRAINT IF EXISTS criterion_power_plant_watchlist_points_pkey,
  DROP CONSTRAINT IF EXISTS criterion_power_plant_watchlist_points_watchlist_id_fkey,
  DROP CONSTRAINT IF EXISTS chk_criterion_pp_watchlist_points_source_nonempty,
  DROP CONSTRAINT IF EXISTS chk_criterion_pp_watchlist_points_tsp_nonempty,
  DROP CONSTRAINT IF EXISTS chk_criterion_pp_watchlist_points_metadata_nonempty,
  DROP CONSTRAINT IF EXISTS chk_criterion_pp_watchlist_points_rec_del_sign;

DO $$
DECLARE
  current_pk text;
BEGIN
  SELECT conname
  INTO current_pk
  FROM pg_constraint
  WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
    AND contype = 'p';

  IF current_pk IS NOT NULL AND current_pk <> 'criterion_watchlist_items_pkey' THEN
    EXECUTE format(
      'ALTER TABLE helioscta_app.criterion_watchlist_items DROP CONSTRAINT %I',
      current_pk
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'criterion_watchlist_items_pkey'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT criterion_watchlist_items_pkey
      PRIMARY KEY (watchlist_id, entity_type, source_table, source_key);
  END IF;
END;
$$;

ALTER TABLE helioscta_app.criterion_watchlist_items
  ALTER COLUMN tsp_short DROP NOT NULL,
  ALTER COLUMN metadata_id DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'fk_criterion_watchlist_items_watchlist'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT fk_criterion_watchlist_items_watchlist
      FOREIGN KEY (watchlist_id)
      REFERENCES helioscta_app.criterion_watchlists (watchlist_id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_entity_type_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_entity_type_nonempty
      CHECK (length(trim(entity_type)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_source_table_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_source_table_nonempty
      CHECK (length(trim(source_table)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_source_key_nonempty'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_source_key_nonempty
      CHECK (length(trim(source_key)) > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_display_snapshot_object'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_display_snapshot_object
      CHECK (jsonb_typeof(display_snapshot) = 'object');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_source_attrs_object'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_source_attrs_object
      CHECK (jsonb_typeof(source_attrs) = 'object');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'helioscta_app.criterion_watchlist_items'::regclass
      AND conname = 'chk_criterion_watchlist_items_nomination_key'
  ) THEN
    ALTER TABLE helioscta_app.criterion_watchlist_items
      ADD CONSTRAINT chk_criterion_watchlist_items_nomination_key
      CHECK (
        entity_type <> 'nomination_point'
        OR (
          tsp_short IS NOT NULL
          AND length(trim(tsp_short)) > 0
          AND metadata_id IS NOT NULL
          AND length(trim(metadata_id)) > 0
        )
      );
  END IF;
END;
$$;

ALTER TABLE helioscta_app.criterion_watchlist_items
  DROP COLUMN IF EXISTS state_abb,
  DROP COLUMN IF EXISTS pipeline_name,
  DROP COLUMN IF EXISTS location_name,
  DROP COLUMN IF EXISTS location_id,
  DROP COLUMN IF EXISTS county_name,
  DROP COLUMN IF EXISTS connecting_entity,
  DROP COLUMN IF EXISTS category_short,
  DROP COLUMN IF EXISTS loc_qti_short,
  DROP COLUMN IF EXISTS rec_del_sign;

DROP INDEX IF EXISTS helioscta_app.idx_criterion_power_plant_watchlist_points_source_key;
DROP INDEX IF EXISTS helioscta_app.idx_criterion_power_plant_watchlist_points_sort;
DROP INDEX IF EXISTS helioscta_app.idx_criterion_power_plant_watchlist_points_state;

CREATE INDEX IF NOT EXISTS idx_criterion_watchlist_items_source_key
  ON helioscta_app.criterion_watchlist_items
    (entity_type, source_table, source_key);

CREATE INDEX IF NOT EXISTS idx_criterion_watchlist_items_nomination_key
  ON helioscta_app.criterion_watchlist_items
    (source_table, tsp_short, metadata_id)
  WHERE entity_type = 'nomination_point';

CREATE INDEX IF NOT EXISTS idx_criterion_watchlist_items_sort
  ON helioscta_app.criterion_watchlist_items
    (
      watchlist_id,
      sort_order,
      (display_snapshot ->> 'state'),
      (display_snapshot ->> 'pipeline'),
      (display_snapshot ->> 'location')
    );

CREATE INDEX IF NOT EXISTS idx_criterion_watchlist_items_state
  ON helioscta_app.criterion_watchlist_items
    ((display_snapshot ->> 'state'), (display_snapshot ->> 'pipeline'))
  WHERE entity_type = 'nomination_point';

DROP TRIGGER IF EXISTS trg_touch_criterion_power_plant_watchlist_updated_at
  ON helioscta_app.criterion_watchlist_items;
DROP TRIGGER IF EXISTS trg_touch_criterion_watchlist_updated_at
  ON helioscta_app.criterion_watchlist_items;

CREATE OR REPLACE FUNCTION helioscta_app.touch_criterion_watchlist_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_watchlist_id integer;
BEGIN
  target_watchlist_id := COALESCE(NEW.watchlist_id, OLD.watchlist_id);

  UPDATE helioscta_app.criterion_watchlists
  SET updated_at = now()
  WHERE watchlist_id = target_watchlist_id;

  RETURN NULL;
END;
$$;

CREATE TRIGGER trg_touch_criterion_watchlist_updated_at
AFTER INSERT OR UPDATE OR DELETE
ON helioscta_app.criterion_watchlist_items
FOR EACH ROW
EXECUTE FUNCTION helioscta_app.touch_criterion_watchlist_updated_at();

DROP FUNCTION IF EXISTS helioscta_app.touch_criterion_power_plant_watchlist_updated_at();
