name: helioscta_platform
version: "0.1.0"
config-version: 2

profile: helioscta_platform

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  helioscta_platform:
    setup:
      +schema: setup
      +materialized: ephemeral
      schemas:
        +enabled: false
    ops:
      +schema: ops
      +materialized: ephemeral
      table_ops_api_fetch_log:
        +enabled: false
      table_ops_data_availability_events:
        +enabled: false
      index_ops_api_fetch_log:
        +enabled: false
      index_ops_data_availability_events:
        +enabled: false
    power:
      +schema: power
      +materialized: ephemeral
      pjm:
        +materialized: ephemeral
        da_hrl_lmps:
          +materialized: ephemeral
          table_pjm_da_hrl_lmps:
            +enabled: false
          index_pjm_da_hrl_lmps:
            +enabled: false
        rt_hrl_lmps:
          +materialized: ephemeral
          table_pjm_rt_hrl_lmps:
            +enabled: false
          index_pjm_rt_hrl_lmps:
            +enabled: false
        unverified_five_min_lmps:
          +materialized: ephemeral
          table_pjm_unverified_five_min_lmps:
            +enabled: false
          index_pjm_unverified_five_min_lmps:
            +enabled: false
        rt_fivemin_mnt_lmps:
          +materialized: ephemeral
          table_pjm_rt_fivemin_mnt_lmps:
            +enabled: false
          index_pjm_rt_fivemin_mnt_lmps:
            +enabled: false
tests:
  helioscta_platform:
    +store_failures: false
