/*
Genscape nominations watchlists.

Source system: frontend app-owned selections over WoodMac/Genscape
GenscapeDataFeed.natgas location_role_id values.

Primary grain:
- helioscta_app.genscape_noms_watchlists: one row per saved watchlist.
- helioscta_app.genscape_noms_watchlist_roles: one row per watchlist x
  location_role_id membership.

The parent location_role_ids array is retained for compatibility with existing
frontend report consumers. The child table is the normalized audit/edit surface;
its trigger keeps the array synchronized for add/remove workflows.
*/

CREATE SCHEMA IF NOT EXISTS helioscta_app;

CREATE TABLE IF NOT EXISTS helioscta_app.genscape_noms_watchlists (
  watchlist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  display_name text NOT NULL,
  location_role_ids integer[] NOT NULL DEFAULT '{}'::integer[],
  sign_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT chk_genscape_noms_watchlists_slug_nonempty
    CHECK (length(trim(slug)) > 0),
  CONSTRAINT chk_genscape_noms_watchlists_display_name_nonempty
    CHECK (length(trim(display_name)) > 0),
  CONSTRAINT chk_genscape_noms_watchlists_sign_overrides_object
    CHECK (jsonb_typeof(sign_overrides) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_genscape_noms_watchlists_active_slug
  ON helioscta_app.genscape_noms_watchlists (slug)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_genscape_noms_watchlists_active_name
  ON helioscta_app.genscape_noms_watchlists (is_active, display_name);

CREATE TABLE IF NOT EXISTS helioscta_app.genscape_noms_watchlist_roles (
  watchlist_id integer NOT NULL
    REFERENCES helioscta_app.genscape_noms_watchlists (watchlist_id)
    ON DELETE CASCADE,
  location_role_id integer NOT NULL,
  created_by varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (watchlist_id, location_role_id)
);

CREATE INDEX IF NOT EXISTS idx_genscape_noms_watchlist_roles_role_id
  ON helioscta_app.genscape_noms_watchlist_roles (location_role_id);

CREATE OR REPLACE FUNCTION helioscta_app.sync_genscape_noms_watchlist_role_array()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_watchlist_id integer;
BEGIN
  target_watchlist_id := COALESCE(NEW.watchlist_id, OLD.watchlist_id);

  UPDATE helioscta_app.genscape_noms_watchlists AS wl
  SET location_role_ids = COALESCE(
        (
          SELECT array_agg(wlr.location_role_id ORDER BY wlr.location_role_id)
          FROM helioscta_app.genscape_noms_watchlist_roles AS wlr
          WHERE wlr.watchlist_id = target_watchlist_id
        ),
        '{}'::integer[]
      ),
      sign_overrides = COALESCE(
        (
          SELECT jsonb_object_agg(key, value)
          FROM jsonb_each(wl.sign_overrides)
          WHERE key IN (
            SELECT wlr.location_role_id::text
            FROM helioscta_app.genscape_noms_watchlist_roles AS wlr
            WHERE wlr.watchlist_id = target_watchlist_id
          )
        ),
        '{}'::jsonb
      ),
      updated_at = now()
  WHERE wl.watchlist_id = target_watchlist_id;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_genscape_noms_watchlist_role_array
  ON helioscta_app.genscape_noms_watchlist_roles;

CREATE TRIGGER trg_sync_genscape_noms_watchlist_role_array
AFTER INSERT OR UPDATE OR DELETE
ON helioscta_app.genscape_noms_watchlist_roles
FOR EACH ROW
EXECUTE FUNCTION helioscta_app.sync_genscape_noms_watchlist_role_array();
