-- Generated by npm run sql:nav-positions.
-- SQL writer: frontend/scripts/generate-nav-position-sql.py.
-- Source of truth: frontend/lib/positionsAndTrades/rules/*.json.
-- Do not edit this file directly. Update the JSON rules and regenerate.

with params as (
  select
    NULL::date as requested_nav_date,
    NULL::text as fund_filter,
    NULL::text as account_group_filter,
    NULL::text as product_search,
    NULL::text as product_family_filter,
    NULL::text as market_name_filter,
    NULL::text as product_code_filter,
    NULL::text as rule_status_filter
),
product_catalog as (
  select *
  from (
    values
    ('HHD', 'Gas', 'Henry Hub', NULL, NULL, 'IFED'),
    ('NG', 'Gas', 'Henry Hub', NULL, 'NG', 'NYME'),
    ('HH', 'Gas', 'Henry Hub', NULL, 'IW', 'NYME'),
    ('HP', 'Gas', 'Henry Hub', NULL, 'ZA', 'NYME'),
    ('H', 'Gas', 'Henry Hub', NULL, NULL, 'IFED'),
    ('PHH', 'Gas', 'Henry Hub', NULL, NULL, 'IFED'),
    ('PHE', 'Gas', 'Henry Hub', 'NG', NULL, 'IFED'),
    ('LN', 'Gas', 'Henry Hub', 'NG', 'NG', 'NYME'),
    ('LN1', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
    ('LN2', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
    ('LN3', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
    ('LN4', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
    ('LN5', 'Gas', 'Henry Hub', 'NG', 'NGW', 'NYME'),
    ('KN4', 'Gas', 'Henry Hub', 'NG', 'HZI', 'NYME'),
    ('G3', 'Gas', 'Henry Hub', 'NG', NULL, 'NYME'),
    ('G4', 'Gas', 'Henry Hub', 'NG', NULL, 'NYME'),
    ('PDP', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('PWA', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('DDP', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('PDA', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('PJL', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('PMI', 'Power', 'PJM', 'PMI', NULL, 'IFED'),
    ('P1X', 'Power', 'PJM', 'PMI', NULL, 'IFED'),
    ('OPJ', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('ODP', 'Power', 'PJM', NULL, NULL, 'IFED'),
    ('ERA', 'Power', 'ERCOT', NULL, NULL, 'IFED'),
    ('ERN', 'Power', 'ERCOT', NULL, NULL, 'IFED'),
    ('ECI', 'Power', 'ERCOT', NULL, NULL, 'IFED'),
    ('NEZ', 'Power', 'NEPOOL', NULL, NULL, 'IFED'),
    ('NEP', 'Power', 'NEPOOL', NULL, NULL, 'IFED'),
    ('SPM', 'Power', 'CAISO', NULL, NULL, 'IFED'),
    ('NPM', 'Power', 'CAISO', NULL, NULL, 'IFED'),
    ('MDC', 'Power', 'Mid-C', NULL, NULL, 'IFED'),
    ('AEC', 'Basis', 'AECO', NULL, NULL, 'IFED'),
    ('ALQ', 'Basis', 'Algonquin', NULL, NULL, 'IFED'),
    ('CRI', 'Basis', 'CIG Rockies', NULL, NULL, 'IFED'),
    ('DGD', 'Basis', 'Chicago', NULL, NULL, 'IFED'),
    ('DOM', 'Basis', 'Eastern Gas South', NULL, NULL, 'IFED'),
    ('HXS', 'Basis', 'Houston Ship Channel', NULL, NULL, 'IFED'),
    ('UCS', 'Basis', 'Houston Ship Channel', NULL, NULL, 'IFED'),
    ('NTO', 'Basis', 'NGPL TXOK', NULL, NULL, 'IFED'),
    ('NWR', 'Basis', 'Northwest Rockies', NULL, NULL, 'IFED'),
    ('PGE', 'Basis', 'PG&E Citygate', NULL, NULL, 'IFED'),
    ('TMT', 'Basis', 'Tetco M3', NULL, NULL, 'IFED'),
    ('TRZ', 'Basis', 'Transco Zone 4', NULL, NULL, 'IFED')
  ) as t(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
  )
),
product_aliases as (
  select *
  from (
    values
    (1, 'regex', '^ICE NGAS HH SWG DLY DAY-[0-9]+$', 'HHD', NULL),
    (2, 'exact', 'ICE NGAS HH SWING DAILY', 'HHD', NULL),
    (3, 'exact', 'NATURAL GAS', 'NG', NULL),
    (4, 'exact', 'GLOBEX NATURAL GAS LD', 'HH', NULL),
    (5, 'exact', 'NYMEX HENRY HUB FINANCIAL LDO', 'HH', NULL),
    (6, 'exact', 'NYMEX HENRY HUB NATURAL GAS', 'HP', NULL),
    (7, 'exact', 'HENRY PENULTIMATE NATURAL GAS', 'HP', NULL),
    (8, 'exact', 'NATURAL GAS LD1 FUTURE', 'H', NULL),
    (9, 'exact', 'HENRY HUB NATURAL GAS', 'H', NULL),
    (10, 'exact', 'ICE PHH', 'PHH', NULL),
    (11, 'exact', 'ICE PHE', 'PHE', 'option'),
    (12, 'exact', 'ICE HH EQ', 'PHE', 'option'),
    (13, 'exact', 'ICE NGAS PEN HENRY HUB', 'PHE', 'option'),
    (14, 'exact', 'NYM EUR NATURAL GAS', 'LN', 'option'),
    (15, 'exact', 'NATURAL GAS CLEARPORT', 'LN', 'option'),
    (16, 'exact', 'NATURAL GAS FINANCIAL WEEK 1', 'LN1', 'option'),
    (17, 'exact', 'NATURAL GAS FINANCIAL WEEK 2', 'LN2', 'option'),
    (18, 'exact', 'NATURAL GAS FINANCIAL WEEK 3', 'LN3', 'option'),
    (19, 'exact', 'NATURAL GAS FINANCIAL WEEK 4', 'LN4', 'option'),
    (20, 'exact', 'NATURAL GAS FINANCIAL WEEK 5', 'LN5', 'option'),
    (21, 'exact', 'NATURAL GAS 3M CSO', 'G3', 'option'),
    (22, 'exact', 'NATURAL GAS FINANCIAL 1M SO', 'G4', 'option'),
    (23, 'exact', 'NATURAL GAS 1M CSO', 'G4', 'option'),
    (24, 'exact', 'ICE PJM WH RTD', 'PDP', NULL),
    (25, 'exact', 'ICE PWA', 'PWA', NULL),
    (26, 'exact', 'ICE PJMWHPKDAY', 'PDA', NULL),
    (27, 'exact', 'ICE PJL', 'PJL', NULL),
    (28, 'regex', '^ICE (PJM MINI|MINIPJMRT|PJM WHREAL TYM PK MINI)([-_][0-9]+)?$', 'PMI', NULL),
    (29, 'exact', 'ICE PJM WHRT PEAK OPT_4096', 'P1X', 'option'),
    (30, 'regex', '^ICE PJM OFF PK[-_][0-9]+$', 'OPJ', NULL),
    (31, 'exact', 'ICE ERA', 'ERA', NULL),
    (32, 'exact', 'ERCOT N 345 KV RT PEAK DLY', 'ERN', NULL),
    (33, 'regex', '^ICE ERCOT NORTH 345KV 7X8[-_][0-9]+$', 'ECI', NULL),
    (34, 'regex', '^(ISO ENG MASS HUB D-PK-[0-9]+|ICE NEPOOL PK MNTH-[0-9]+)$', 'NEP', NULL),
    (35, 'regex', '^ICE SP 15 PEAK([_-][0-9]+)?$', 'SPM', NULL),
    (36, 'regex', '^ICE NP 15 PEAK([_-][0-9]+)?$', 'NPM', NULL),
    (37, 'regex', '^ICE MID-C PEAK([_-][0-9]+)?$', 'MDC', NULL),
    (38, 'exact', 'AB NIT BASIS FUTURE', 'AEC', NULL),
    (39, 'exact', 'ICE ALQCTYGTSW', 'ALQ', NULL),
    (40, 'exact', 'ICE CIG ROCKIES BASIS', 'CRI', NULL),
    (41, 'exact', 'ICE CHICAGO BASIS FUT', 'DGD', NULL),
    (42, 'exact', 'ICE EASTERN GAS SOUTH BASIS FU', 'DOM', NULL),
    (43, 'exact', 'ICE HSC BASIS', 'HXS', NULL),
    (44, 'exact', 'NGPL TXOK BASIS FUTURE', 'NTO', NULL),
    (45, 'exact', 'ICE NGAS NYM NWP RK', 'NWR', NULL),
    (46, 'exact', 'ICE NGAS NYM PG&E', 'PGE', NULL),
    (47, 'exact', 'ICE TETCO SWP', 'TMT', NULL),
    (48, 'exact', 'ICE TRANSCO STATION 85 ZONE 4', 'TRZ', NULL),
    (49, 'exact', 'ICE TCOZN4BASI', 'TRZ', NULL)
  ) as t(
    priority,
    match_type,
    pattern,
    product_code,
    option_type
  )
),
source_positions as (
  select p.*
  from nav.positions p
  cross join params
  where (params.fund_filter is null or p.fund_code = params.fund_filter)
    and (params.requested_nav_date is null or p.nav_date = params.requested_nav_date)
),
latest_nav_by_fund as (
  select
    source_positions.fund_code,
    coalesce((select requested_nav_date from params), max(source_positions.nav_date)) as nav_date
  from source_positions
  group by source_positions.fund_code
),
latest_upload_by_fund as (
  select
    source_positions.fund_code,
    source_positions.nav_date,
    max(source_positions.sftp_upload_timestamp) as sftp_upload_timestamp
  from source_positions
  inner join latest_nav_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
  group by source_positions.fund_code, source_positions.nav_date
),
latest_positions as (
  select source_positions.*
  from source_positions
  inner join latest_upload_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
   and latest.sftp_upload_timestamp = source_positions.sftp_upload_timestamp
),
normalized_positions as (
  select
    latest_positions.*,
    upper(regexp_replace(coalesce(latest_positions.product, ''), '[[:space:]]+', ' ', 'g')) as product_norm,
    (
      upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'PUT', 'C', 'P')
      or upper(coalesce(latest_positions.type, '')) like '%OPTION%'
    ) as is_option,
    case
      when upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'C') then 'C'
      when upper(coalesce(latest_positions.call_put, '')) in ('PUT', 'P') then 'P'
      else null
    end as put_call,
    case
      when latest_positions.month_year ~ '^\s*\d{1,2}/\d{1,2}/\d{4}\s*$'
        then to_char(to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'), 'YYYYMM')
      when upper(trim(coalesce(latest_positions.month_year, ''))) ~ '^[A-Z]{3}\d{2}$'
        then to_char(to_date(upper(trim(latest_positions.month_year)), 'MONYY'), 'YYYYMM')
      else null
    end as contract_yyyymm,
    case
      when latest_positions.month_year ~ '^\s*\d{1,2}/\d{1,2}/\d{4}\s*$'
        then extract(day from to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'))::integer
      else null
    end as contract_day
  from latest_positions
),
rule_matches as (
  select
    normalized_positions.*,
    matched_alias.priority as rule_priority,
    matched_alias.match_type as rule_match_type,
    matched_alias.pattern as rule_pattern,
    matched_alias.product_code as matched_product_code
  from normalized_positions
  left join lateral (
    select product_aliases.*
    from product_aliases
    where (
        (product_aliases.match_type = 'exact' and normalized_positions.product_norm = product_aliases.pattern)
        or (product_aliases.match_type = 'regex' and normalized_positions.product_norm ~* product_aliases.pattern)
      )
      and (
        product_aliases.option_type is null
        or product_aliases.option_type = case when normalized_positions.is_option then 'option' else 'future' end
      )
    order by product_aliases.priority
    limit 1
  ) matched_alias on true
),
positions_with_rules as (
  select
    rule_matches.fund_code,
    rule_matches.source_legal_entity,
    rule_matches.source_file_name,
    rule_matches.source_file_row_number,
    rule_matches.nav_date,
    rule_matches.sftp_upload_timestamp,
    rule_matches.broker_name,
    rule_matches.account_group,
    rule_matches.account,
    rule_matches.trade_date,
    rule_matches.product_id_internal,
    rule_matches.product,
    rule_matches.type,
    rule_matches.month_year,
    rule_matches.client_symbol,
    rule_matches.strike_price,
    rule_matches.call_put,
    rule_matches.product_currency_1,
    rule_matches.long_short,
    rule_matches.quantity_1,
    rule_matches.counter_currency_ccy2,
    rule_matches.ccy2_long_short,
    rule_matches.ccy2_quantity_2,
    rule_matches.trade_price,
    rule_matches.multiplier_and_tick_value,
    rule_matches.cost_in_native_currency,
    rule_matches.open_exchange_rate,
    rule_matches.cost_in_base_currency,
    rule_matches.market_settlement_price,
    rule_matches.market_value_in_native_currency,
    rule_matches.close_exchange_rate,
    rule_matches.market_value_in_base_currency,
    rule_matches.sector,
    rule_matches.sub_sector,
    rule_matches.country,
    rule_matches.exchange_name,
    rule_matches.source_1_symbol,
    rule_matches.source_3_symbol,
    rule_matches.one_chicago_symbol,
    rule_matches.fas_level,
    rule_matches.option_style,
    rule_matches.created_at,
    rule_matches.updated_at,
    catalog.product_code,
    catalog.product_family,
    catalog.market_name,
    case when rule_matches.is_option then catalog.underlying_product_code else null end as underlying_product_code,
    catalog.bbg_exchange_code,
    catalog.default_exchange_name,
    rule_matches.contract_yyyymm,
    rule_matches.contract_day,
    rule_matches.put_call,
    case
      when rule_matches.strike_price is null then null
      else round(rule_matches.strike_price::numeric, 3)::double precision
    end as strike_price_normalized,
    case
      when catalog.product_code is null then 'unresolved_product'
      when coalesce(trim(rule_matches.month_year), '') <> '' and rule_matches.contract_yyyymm is null then 'unparsed_contract'
      when rule_matches.is_option and rule_matches.put_call is null then 'option_missing_put_call'
      when rule_matches.is_option and rule_matches.strike_price is null then 'option_missing_strike'
      else 'ok'
    end as rule_status,
    rule_matches.rule_priority,
    rule_matches.rule_match_type,
    rule_matches.rule_pattern
  from rule_matches
  left join product_catalog catalog
    on catalog.product_code = rule_matches.matched_product_code
),
filtered_positions as (
  select positions_with_rules.*
  from positions_with_rules
  cross join params
  where (params.account_group_filter is null or positions_with_rules.account_group = params.account_group_filter)
    and (params.product_family_filter is null or positions_with_rules.product_family = params.product_family_filter)
    and (params.market_name_filter is null or positions_with_rules.market_name = params.market_name_filter)
    and (params.product_code_filter is null or positions_with_rules.product_code = params.product_code_filter)
    and (params.rule_status_filter is null or positions_with_rules.rule_status = params.rule_status_filter)
    and (
      params.product_search is null
      or positions_with_rules.product ilike '%' || params.product_search || '%'
      or positions_with_rules.product_code ilike '%' || params.product_search || '%'
      or positions_with_rules.product_family ilike '%' || params.product_search || '%'
      or positions_with_rules.market_name ilike '%' || params.product_search || '%'
      or positions_with_rules.product_id_internal ilike '%' || params.product_search || '%'
      or positions_with_rules.client_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_1_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_3_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.account ilike '%' || params.product_search || '%'
    )
),
final as (
  select
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    min(source_file_name) as example_source_file_name,
    min(source_file_row_number) as example_source_file_row_number
  from filtered_positions
  where rule_status is distinct from 'ok'
     or product_code is null
     or (coalesce(trim(month_year), '') <> '' and contract_yyyymm is null)
  group by
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day
)
select * from final;
