from __future__ import annotations

import html
from typing import Any

BRAND_NAME = "HeliosCTA Alerts"
EMAIL_WIDTH = 680

TONE_COLORS = {
    "info": ("#2563eb", "#eff6ff", "#1e3a8a"),
    "success": ("#0f766e", "#ecfdf5", "#064e3b"),
    "warning": ("#b45309", "#fffbeb", "#78350f"),
    "failure": ("#b91c1c", "#fef2f2", "#7f1d1d"),
}


def render_email(
    *,
    title: str,
    preheader: str,
    status_label: str,
    status_tone: str = "info",
    intro: str,
    facts: list[tuple[str, Any]],
    sections: list[dict[str, Any]] | None = None,
    footer: str | None = None,
) -> str:
    """Render a conservative table-based HTML email for Outlook/Graph."""
    accent, tone_bg, tone_text = _tone(status_tone)
    section_html = "".join(_render_section(section) for section in sections or [])
    footer_text = footer or "Generated by HeliosCTA backend notifications."

    return f"""<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{_esc(title)}</title>
  </head>
  <body style="margin:0; padding:0; background-color:#f3f4f6; color:#111827; font-family:Arial, Helvetica, sans-serif;">
    <div style="display:none; max-height:0; overflow:hidden; opacity:0; color:transparent;">{_esc(preheader)}</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color:#f3f4f6; margin:0; padding:24px 0;">
      <tr>
        <td align="center" style="padding:0 12px;">
          <table role="presentation" width="{EMAIL_WIDTH}" cellspacing="0" cellpadding="0" border="0" style="width:{EMAIL_WIDTH}px; max-width:100%; background-color:#ffffff; border:1px solid #e5e7eb;">
            <tr>
              <td style="padding:18px 24px; background-color:#111827; color:#ffffff;">
                <div style="font-size:12px; line-height:16px; letter-spacing:0.08em; text-transform:uppercase; color:#cbd5e1;">{_esc(BRAND_NAME)}</div>
                <div style="font-size:22px; line-height:28px; font-weight:700; margin-top:6px;">{_esc(title)}</div>
              </td>
            </tr>
            <tr>
              <td style="padding:20px 24px 0 24px;">
                <table role="presentation" cellspacing="0" cellpadding="0" border="0">
                  <tr>
                    <td style="padding:6px 10px; background-color:{tone_bg}; color:{tone_text}; border-left:4px solid {accent}; font-size:13px; line-height:18px; font-weight:700;">
                      {_esc(status_label)}
                    </td>
                  </tr>
                </table>
                <p style="margin:16px 0 0 0; color:#374151; font-size:14px; line-height:21px;">{_esc(intro)}</p>
              </td>
            </tr>
            <tr>
              <td style="padding:18px 24px 0 24px;">
                {_render_facts(facts)}
              </td>
            </tr>
            {section_html}
            <tr>
              <td style="padding:18px 24px 22px 24px;">
                <p style="margin:0; color:#6b7280; font-size:12px; line-height:18px;">{_esc(footer_text)}</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>"""


def text_section(title: str, text: str) -> dict[str, Any]:
    return {"title": title, "html": _paragraph(text)}


def bullet_section(title: str, items: list[str], *, tone: str | None = None) -> dict[str, Any]:
    item_html = "".join(
        f"<li style=\"margin:0 0 6px 0;\">{_esc(item)}</li>" for item in items
    )
    if not item_html:
        item_html = "<li style=\"margin:0;\">None.</li>"
    content = (
        f"<ul style=\"margin:0; padding-left:18px; color:#374151; font-size:14px; line-height:21px;\">"
        f"{item_html}</ul>"
    )
    return {"title": title, "html": _wrap_tone(content, tone) if tone else content}


def link_section(title: str, *, label: str, url: str) -> dict[str, Any]:
    href = _esc(url)
    content = (
        f"<a href=\"{href}\" style=\"display:inline-block; padding:9px 12px; "
        "background-color:#111827; color:#ffffff; text-decoration:none; "
        "font-size:13px; line-height:18px; font-weight:700;\">"
        f"{_esc(label)}</a>"
    )
    return {"title": title, "html": content}


def product_warning_section(
    *,
    products: list[dict[str, Any]],
    product_count: int,
    max_products: int = 8,
) -> dict[str, Any]:
    if not products:
        return text_section("Affected Source Products", "No source product details supplied.")

    rows = []
    for product in products[:max_products]:
        row_count = int(product.get("row_count") or 0)
        product_name = str(product.get("product") or "unknown")
        details = _product_detail_text(product)
        rows.append(
            "<tr>"
            f"<td style=\"padding:8px 10px; border-bottom:1px solid #e5e7eb; font-size:13px; line-height:18px; font-weight:700; color:#111827;\">{_esc(product_name)}</td>"
            f"<td style=\"padding:8px 10px; border-bottom:1px solid #e5e7eb; font-size:13px; line-height:18px; color:#374151;\">{row_count:,}</td>"
            f"<td style=\"padding:8px 10px; border-bottom:1px solid #e5e7eb; font-size:13px; line-height:18px; color:#374151;\">{_esc(details)}</td>"
            "</tr>"
        )
    hidden_count = max(0, product_count - len(products[:max_products]))
    if hidden_count:
        rows.append(
            "<tr>"
            f"<td colspan=\"3\" style=\"padding:8px 10px; font-size:13px; line-height:18px; color:#6b7280;\">... and {hidden_count:,} more source products</td>"
            "</tr>"
        )

    table_html = (
        "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"border:1px solid #e5e7eb; border-collapse:collapse;\">"
        "<tr>"
        "<th align=\"left\" style=\"padding:8px 10px; background-color:#f9fafb; border-bottom:1px solid #e5e7eb; font-size:12px; line-height:16px; color:#6b7280;\">Product</th>"
        "<th align=\"left\" style=\"padding:8px 10px; background-color:#f9fafb; border-bottom:1px solid #e5e7eb; font-size:12px; line-height:16px; color:#6b7280;\">Rows</th>"
        "<th align=\"left\" style=\"padding:8px 10px; background-color:#f9fafb; border-bottom:1px solid #e5e7eb; font-size:12px; line-height:16px; color:#6b7280;\">Identifiers</th>"
        "</tr>"
        + "".join(rows)
        + "</table>"
    )
    return {"title": "Affected Source Products", "html": table_html}


def _render_facts(facts: list[tuple[str, Any]]) -> str:
    rows = []
    for label, value in facts:
        rows.append(
            "<tr>"
            f"<td style=\"padding:8px 10px; width:38%; background-color:#f9fafb; border-bottom:1px solid #e5e7eb; color:#6b7280; font-size:12px; line-height:16px; font-weight:700; text-transform:uppercase;\">{_esc(label)}</td>"
            f"<td style=\"padding:8px 10px; border-bottom:1px solid #e5e7eb; color:#111827; font-size:14px; line-height:20px;\">{_esc(_format_value(value))}</td>"
            "</tr>"
        )
    return (
        "<table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"border:1px solid #e5e7eb; border-collapse:collapse;\">"
        + "".join(rows)
        + "</table>"
    )


def _render_section(section: dict[str, Any]) -> str:
    title = str(section.get("title") or "")
    content = str(section.get("html") or "")
    return (
        "<tr><td style=\"padding:18px 24px 0 24px;\">"
        f"<h2 style=\"margin:0 0 8px 0; color:#111827; font-size:15px; line-height:20px;\">{_esc(title)}</h2>"
        f"{content}"
        "</td></tr>"
    )


def _paragraph(text: str) -> str:
    return (
        f"<p style=\"margin:0; color:#374151; font-size:14px; line-height:21px;\">"
        f"{_esc(text)}</p>"
    )


def _wrap_tone(content: str, tone: str | None) -> str:
    accent, tone_bg, _tone_text = _tone(tone or "info")
    return (
        f"<div style=\"padding:12px; background-color:{tone_bg}; border-left:4px solid {accent};\">"
        f"{content}</div>"
    )


def _product_detail_text(product: dict[str, Any]) -> str:
    source_fields = product.get("source_fields")
    if not isinstance(source_fields, dict):
        source_fields = {}
    parts: list[str] = []
    for label, key in [
        ("futures", "futures_code"),
        ("exch", "exch_comm_cd"),
        ("exchange", "exchange_name"),
        ("symbol", "symbol"),
    ]:
        value = source_fields.get(key)
        if value:
            parts.append(f"{label} {value}")
    months = _coerce_string_list(product.get("contract_year_months"))
    if months:
        parts.append("months " + ", ".join(months[:4]))
    statuses = _coerce_string_list(product.get("trade_statuses"))
    if statuses:
        parts.append("statuses " + ", ".join(statuses[:4]))
    return "; ".join(parts) or "not supplied"


def _coerce_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _tone(name: str) -> tuple[str, str, str]:
    return TONE_COLORS.get(name, TONE_COLORS["info"])


def _format_value(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def _esc(value: Any) -> str:
    return html.escape(str(value), quote=True)
