from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any


SCRIPT_PATH = Path(__file__).resolve()
FRONTEND_ROOT = SCRIPT_PATH.parents[1]
SQL_ROOT = FRONTEND_ROOT / "sql" / "nav-positions"
MANIFEST_PATH = SQL_ROOT / "rules_manifest.json"
RULES_ROOT = FRONTEND_ROOT / "lib" / "positionsAndTrades" / "rules"
PRODUCT_DEFINITIONS_PATH = RULES_ROOT / "product_definitions.json"
PRODUCT_ALIASES_PATH = RULES_ROOT / "product_aliases.json"


def load_rule_json(path: Path) -> list[dict[str, Any]]:
    return json.loads(path.read_text(encoding="utf-8"))


def build_manifest() -> dict[str, Any]:
    product_definitions = load_rule_json(PRODUCT_DEFINITIONS_PATH)
    product_aliases = load_rule_json(PRODUCT_ALIASES_PATH)
    nav_aliases = [
        alias
        for alias in product_aliases
        if alias["source"] in {"nav", "any"}
    ]

    return {
        "ruleSource": [
            "frontend/lib/positionsAndTrades/rules/product_definitions.json",
            "frontend/lib/positionsAndTrades/rules/product_aliases.json",
        ],
        "generatedSqlBuilder": "frontend/scripts/generate-nav-position-sql.py",
        "productDefinitionCount": len(product_definitions),
        "productAliasCount": len(product_aliases),
        "navAliasCount": len(nav_aliases),
        "productDefinitions": product_definitions,
        "productAliases": product_aliases,
        "navAliases": nav_aliases,
    }


def write_manifest(manifest: dict[str, Any]) -> None:
    SQL_ROOT.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {MANIFEST_PATH.relative_to(FRONTEND_ROOT)}")


def sql_text(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def values_rows(rows: list[list[str]]) -> str:
    return ",\n".join(f"    ({', '.join(row)})" for row in rows)


def product_catalog_values(manifest: dict[str, Any]) -> str:
    rows = []
    for product in manifest["productDefinitions"]:
        rows.append(
            [
                sql_text(product["exchangeCode"]),
                sql_text(product["ruleGroup"]),
                sql_text(product["ruleRegion"]),
                sql_text(product["exchangeCodeUnderlying"]),
                sql_text(product["bbgExchangeCode"]),
                sql_text(product["defaultExchangeName"]),
            ]
        )
    return values_rows(rows)


def nav_alias_values(manifest: dict[str, Any]) -> str:
    rows = []
    for priority, alias in enumerate(manifest["navAliases"], start=1):
        rows.append(
            [
                str(priority),
                sql_text(alias["matchType"]),
                sql_text(alias["pattern"]),
                sql_text(alias["exchangeCode"]),
                sql_text(alias.get("optionType")),
            ]
        )
    return values_rows(rows)


def generated_sql(sql: str) -> str:
    return f"""-- Generated by npm run sql:nav-positions.
-- SQL writer: frontend/scripts/generate-nav-position-sql.py.
-- Source of truth: frontend/lib/positionsAndTrades/rules/*.json.
-- Do not edit this file directly. Update the JSON rules and regenerate.

{sql.strip()}
"""


def positions_with_rules_cte(manifest: dict[str, Any]) -> str:
    return f"""with params as (
  select
    NULL::date as requested_nav_date,
    NULL::text as fund_filter,
    NULL::text as account_group_filter,
    NULL::text as product_search,
    NULL::text as product_family_filter,
    NULL::text as market_name_filter,
    NULL::text as product_code_filter,
    NULL::text as rule_status_filter
),
product_catalog as (
  select *
  from (
    values
{product_catalog_values(manifest)}
  ) as t(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
  )
),
product_aliases as (
  select *
  from (
    values
{nav_alias_values(manifest)}
  ) as t(
    priority,
    match_type,
    pattern,
    product_code,
    option_type
  )
),
source_positions as (
  select p.*
  from nav.positions p
  cross join params
  where (params.fund_filter is null or p.fund_code = params.fund_filter)
    and (params.requested_nav_date is null or p.nav_date = params.requested_nav_date)
),
latest_nav_by_fund as (
  select
    source_positions.fund_code,
    coalesce((select requested_nav_date from params), max(source_positions.nav_date)) as nav_date
  from source_positions
  group by source_positions.fund_code
),
latest_upload_by_fund as (
  select
    source_positions.fund_code,
    source_positions.nav_date,
    max(source_positions.sftp_upload_timestamp) as sftp_upload_timestamp
  from source_positions
  inner join latest_nav_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
  group by source_positions.fund_code, source_positions.nav_date
),
latest_positions as (
  select source_positions.*
  from source_positions
  inner join latest_upload_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
   and latest.sftp_upload_timestamp = source_positions.sftp_upload_timestamp
),
normalized_positions as (
  select
    latest_positions.*,
    upper(regexp_replace(coalesce(latest_positions.product, ''), '[[:space:]]+', ' ', 'g')) as product_norm,
    (
      upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'PUT', 'C', 'P')
      or upper(coalesce(latest_positions.type, '')) like '%OPTION%'
    ) as is_option,
    case
      when upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'C') then 'C'
      when upper(coalesce(latest_positions.call_put, '')) in ('PUT', 'P') then 'P'
      else null
    end as put_call,
    case
      when latest_positions.month_year ~ '^\\s*\\d{{1,2}}/\\d{{1,2}}/\\d{{4}}\\s*$'
        then to_char(to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'), 'YYYYMM')
      when upper(trim(coalesce(latest_positions.month_year, ''))) ~ '^[A-Z]{{3}}\\d{{2}}$'
        then to_char(to_date(upper(trim(latest_positions.month_year)), 'MONYY'), 'YYYYMM')
      else null
    end as contract_yyyymm,
    case
      when latest_positions.month_year ~ '^\\s*\\d{{1,2}}/\\d{{1,2}}/\\d{{4}}\\s*$'
        then extract(day from to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'))::integer
      else null
    end as contract_day
  from latest_positions
),
rule_matches as (
  select
    normalized_positions.*,
    matched_alias.priority as rule_priority,
    matched_alias.match_type as rule_match_type,
    matched_alias.pattern as rule_pattern,
    matched_alias.product_code as matched_product_code
  from normalized_positions
  left join lateral (
    select product_aliases.*
    from product_aliases
    where (
        (product_aliases.match_type = 'exact' and normalized_positions.product_norm = product_aliases.pattern)
        or (product_aliases.match_type = 'regex' and normalized_positions.product_norm ~* product_aliases.pattern)
      )
      and (
        product_aliases.option_type is null
        or product_aliases.option_type = case when normalized_positions.is_option then 'option' else 'future' end
      )
    order by product_aliases.priority
    limit 1
  ) matched_alias on true
),
positions_with_rules as (
  select
    rule_matches.fund_code,
    rule_matches.source_legal_entity,
    rule_matches.source_file_name,
    rule_matches.source_file_row_number,
    rule_matches.nav_date,
    rule_matches.sftp_upload_timestamp,
    rule_matches.broker_name,
    rule_matches.account_group,
    rule_matches.account,
    rule_matches.trade_date,
    rule_matches.product_id_internal,
    rule_matches.product,
    rule_matches.type,
    rule_matches.month_year,
    rule_matches.client_symbol,
    rule_matches.strike_price,
    rule_matches.call_put,
    rule_matches.product_currency_1,
    rule_matches.long_short,
    rule_matches.quantity_1,
    rule_matches.counter_currency_ccy2,
    rule_matches.ccy2_long_short,
    rule_matches.ccy2_quantity_2,
    rule_matches.trade_price,
    rule_matches.multiplier_and_tick_value,
    rule_matches.cost_in_native_currency,
    rule_matches.open_exchange_rate,
    rule_matches.cost_in_base_currency,
    rule_matches.market_settlement_price,
    rule_matches.market_value_in_native_currency,
    rule_matches.close_exchange_rate,
    rule_matches.market_value_in_base_currency,
    rule_matches.sector,
    rule_matches.sub_sector,
    rule_matches.country,
    rule_matches.exchange_name,
    rule_matches.source_1_symbol,
    rule_matches.source_3_symbol,
    rule_matches.one_chicago_symbol,
    rule_matches.fas_level,
    rule_matches.option_style,
    rule_matches.created_at,
    rule_matches.updated_at,
    catalog.product_code,
    catalog.product_family,
    catalog.market_name,
    case when rule_matches.is_option then catalog.underlying_product_code else null end as underlying_product_code,
    catalog.bbg_exchange_code,
    catalog.default_exchange_name,
    rule_matches.contract_yyyymm,
    rule_matches.contract_day,
    rule_matches.put_call,
    case
      when rule_matches.strike_price is null then null
      else round(rule_matches.strike_price::numeric, 3)::double precision
    end as strike_price_normalized,
    case
      when catalog.product_code is null then 'unresolved_product'
      when coalesce(trim(rule_matches.month_year), '') <> '' and rule_matches.contract_yyyymm is null then 'unparsed_contract'
      when rule_matches.is_option and rule_matches.put_call is null then 'option_missing_put_call'
      when rule_matches.is_option and rule_matches.strike_price is null then 'option_missing_strike'
      else 'ok'
    end as rule_status,
    rule_matches.rule_priority,
    rule_matches.rule_match_type,
    rule_matches.rule_pattern
  from rule_matches
  left join product_catalog catalog
    on catalog.product_code = rule_matches.matched_product_code
),
filtered_positions as (
  select positions_with_rules.*
  from positions_with_rules
  cross join params
  where (params.account_group_filter is null or positions_with_rules.account_group = params.account_group_filter)
    and (params.product_family_filter is null or positions_with_rules.product_family = params.product_family_filter)
    and (params.market_name_filter is null or positions_with_rules.market_name = params.market_name_filter)
    and (params.product_code_filter is null or positions_with_rules.product_code = params.product_code_filter)
    and (params.rule_status_filter is null or positions_with_rules.rule_status = params.rule_status_filter)
    and (
      params.product_search is null
      or positions_with_rules.product ilike '%' || params.product_search || '%'
      or positions_with_rules.product_code ilike '%' || params.product_search || '%'
      or positions_with_rules.product_family ilike '%' || params.product_search || '%'
      or positions_with_rules.market_name ilike '%' || params.product_search || '%'
      or positions_with_rules.product_id_internal ilike '%' || params.product_search || '%'
      or positions_with_rules.client_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_1_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_3_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.account ilike '%' || params.product_search || '%'
    )
)"""


def grouping_columns(alias: str = "") -> list[str]:
    prefix = f"{alias}." if alias else ""
    return [
        f"{prefix}product_code",
        f"{prefix}product_family",
        f"{prefix}market_name",
        f"{prefix}underlying_product_code",
        f"{prefix}contract_yyyymm",
        f"{prefix}contract_day",
        f"{prefix}put_call",
        f"{prefix}strike_price_normalized",
    ]


def group_by_grouping_columns(alias: str = "") -> str:
    return ",\n    ".join(grouping_columns(alias))


def build_grouped_latest_sql(manifest: dict[str, Any]) -> str:
    group_cols = group_by_grouping_columns()
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
final as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    {group_cols},
    string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
    string_agg(distinct account_group, ', ' order by account_group) filter (
      where account_group is not null and account_group <> ''
    ) as account_groups,
    count(distinct fund_code)::integer as fund_count,
    count(distinct account_group)::integer as account_group_count,
    count(distinct account)::integer as account_count,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(quantity_1, 0))::double precision as net_quantity,
    sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base,
    (
      sum(case when trade_price is not null then trade_price * abs(coalesce(quantity_1, 0)) else 0 end)
      / nullif(sum(case when trade_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
    )::double precision as avg_trade_price,
    (
      sum(case when market_settlement_price is not null then market_settlement_price * abs(coalesce(quantity_1, 0)) else 0 end)
      / nullif(sum(case when market_settlement_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
    )::double precision as avg_settlement_price
  from filtered_positions
  group by
    {group_cols}
)
select * from final;""")


def build_grouped_with_raw_examples_sql(manifest: dict[str, Any]) -> str:
    group_cols = group_by_grouping_columns()
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
final as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    {group_cols},
    string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
    string_agg(distinct account_group, ', ' order by account_group) filter (
      where account_group is not null and account_group <> ''
    ) as account_groups,
    count(distinct fund_code)::integer as fund_count,
    count(distinct account_group)::integer as account_group_count,
    count(distinct account)::integer as account_count,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    string_agg(distinct product, ' | ' order by product) filter (
      where product is not null and product <> ''
    ) as raw_products,
    string_agg(distinct type, ' | ' order by type) filter (
      where type is not null and type <> ''
    ) as raw_types,
    string_agg(distinct month_year, ' | ' order by month_year) filter (
      where month_year is not null and month_year <> ''
    ) as raw_month_years,
    string_agg(distinct product_id_internal, ' | ' order by product_id_internal) filter (
      where product_id_internal is not null and product_id_internal <> ''
    ) as raw_product_ids_internal,
    string_agg(distinct client_symbol, ' | ' order by client_symbol) filter (
      where client_symbol is not null and client_symbol <> ''
    ) as raw_client_symbols,
    string_agg(distinct source_1_symbol, ' | ' order by source_1_symbol) filter (
      where source_1_symbol is not null and source_1_symbol <> ''
    ) as raw_source_1_symbols,
    string_agg(distinct source_3_symbol, ' | ' order by source_3_symbol) filter (
      where source_3_symbol is not null and source_3_symbol <> ''
    ) as raw_source_3_symbols,
    string_agg(distinct exchange_name, ' | ' order by exchange_name) filter (
      where exchange_name is not null and exchange_name <> ''
    ) as raw_exchange_names,
    string_agg(distinct call_put, ' | ' order by call_put) filter (
      where call_put is not null and call_put <> ''
    ) as raw_call_puts,
    string_agg(distinct strike_price::text, ' | ' order by strike_price::text) filter (
      where strike_price is not null
    ) as raw_strike_prices,
    string_agg(distinct rule_match_type, ' | ' order by rule_match_type) filter (
      where rule_match_type is not null and rule_match_type <> ''
    ) as rule_match_types,
    string_agg(distinct rule_pattern, ' | ' order by rule_pattern) filter (
      where rule_pattern is not null and rule_pattern <> ''
    ) as rule_patterns,
    string_agg(distinct source_file_name, ' | ' order by source_file_name) filter (
      where source_file_name is not null and source_file_name <> ''
    ) as source_file_names,
    (array_agg(source_file_name order by source_file_name, source_file_row_number))[1] as example_source_file_name,
    (array_agg(source_file_row_number order by source_file_name, source_file_row_number))[1] as example_source_file_row_number,
    min(account_group) as example_account_group,
    min(account) as example_account
  from filtered_positions
  group by
    {group_cols}
)
select * from final;""")


def build_account_breakout_sql(manifest: dict[str, Any]) -> str:
    group_cols = group_by_grouping_columns()
    account_group_cols = group_by_grouping_columns("account_grouped")
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
account_grouped as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    {group_cols},
    fund_code,
    account_group,
    account,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_account,
    sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity_account,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base_account,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base_account,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base_account
  from filtered_positions
  group by
    {group_cols},
    fund_code,
    account_group,
    account
),
final as (
  select
    account_grouped.*,
    (
      sum(qty_account) over (
        partition by
          {account_group_cols}
      )
    )::double precision as qty_total
  from account_grouped
)
select * from final;""")


def build_rule_exceptions_sql(manifest: dict[str, Any]) -> str:
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
final as (
  select
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    min(source_file_name) as example_source_file_name,
    min(source_file_row_number) as example_source_file_row_number
  from filtered_positions
  where rule_status is distinct from 'ok'
     or product_code is null
     or (coalesce(trim(month_year), '') <> '' and contract_yyyymm is null)
  group by
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day
)
select * from final;""")


def build_grouped_vs_raw_totals_sql(manifest: dict[str, Any]) -> str:
    group_cols = group_by_grouping_columns()
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
grouped as (
  select
    {group_cols},
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
  from filtered_positions
  group by
    {group_cols}
),
grouped_totals as (
  select
    count(*)::integer as grouped_row_count,
    sum(row_count)::integer as grouped_source_row_count,
    sum(qty_total)::double precision as qty_total,
    sum(qty_agr)::double precision as qty_agr,
    sum(qty_moross)::double precision as qty_moross,
    sum(qty_pnt)::double precision as qty_pnt,
    sum(qty_titan)::double precision as qty_titan,
    sum(cost_base)::double precision as cost_base,
    sum(market_value_base)::double precision as market_value_base,
    sum(unrealized_pnl_base)::double precision as unrealized_pnl_base
  from grouped
),
raw_totals as (
  select
    count(*)::integer as raw_row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
  from filtered_positions
),
final as (
  select
    grouped_totals.grouped_row_count,
    raw_totals.raw_row_count,
    grouped_totals.grouped_source_row_count,
    grouped_totals.grouped_source_row_count - raw_totals.raw_row_count as row_count_diff,
    grouped_totals.qty_total - raw_totals.qty_total as qty_total_diff,
    grouped_totals.qty_agr - raw_totals.qty_agr as qty_agr_diff,
    grouped_totals.qty_moross - raw_totals.qty_moross as qty_moross_diff,
    grouped_totals.qty_pnt - raw_totals.qty_pnt as qty_pnt_diff,
    grouped_totals.qty_titan - raw_totals.qty_titan as qty_titan_diff,
    grouped_totals.cost_base - raw_totals.cost_base as cost_base_diff,
    grouped_totals.market_value_base - raw_totals.market_value_base as market_value_base_diff,
    grouped_totals.unrealized_pnl_base - raw_totals.unrealized_pnl_base as unrealized_pnl_base_diff
  from grouped_totals
  cross join raw_totals
)
select * from final;""")


def build_raw_rows_for_group_sql(manifest: dict[str, Any]) -> str:
    return generated_sql(f"""{positions_with_rules_cte(manifest)},
final as (
  select
    fund_code,
    source_legal_entity,
    source_file_name,
    source_file_row_number,
    nav_date,
    sftp_upload_timestamp,
    broker_name,
    account_group,
    account,
    trade_date,
    product_id_internal,
    product,
    type,
    month_year,
    client_symbol,
    strike_price,
    call_put,
    product_currency_1,
    long_short,
    quantity_1,
    counter_currency_ccy2,
    ccy2_long_short,
    ccy2_quantity_2,
    trade_price,
    multiplier_and_tick_value,
    cost_in_base_currency,
    market_settlement_price,
    market_value_in_base_currency,
    exchange_name,
    source_1_symbol,
    source_3_symbol,
    option_style,
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    contract_yyyymm,
    contract_day,
    put_call,
    strike_price_normalized,
    rule_status,
    rule_priority,
    rule_match_type,
    rule_pattern
  from filtered_positions
)
select * from final;""")


def generated_files(manifest: dict[str, Any]) -> dict[Path, str]:
    return {
        SQL_ROOT / "marts" / "grouped_latest.sql": build_grouped_latest_sql(manifest),
        SQL_ROOT / "marts" / "grouped_with_raw_examples.sql": build_grouped_with_raw_examples_sql(manifest),
        SQL_ROOT / "marts" / "account_breakout.sql": build_account_breakout_sql(manifest),
        SQL_ROOT / "checks" / "rule_exceptions.sql": build_rule_exceptions_sql(manifest),
        SQL_ROOT / "checks" / "grouped_vs_raw_totals.sql": build_grouped_vs_raw_totals_sql(manifest),
        SQL_ROOT / "drilldowns" / "raw_rows_for_group.sql": build_raw_rows_for_group_sql(manifest),
    }


def remove_generated_sql_dirs() -> None:
    for dirname in ["marts", "checks", "drilldowns", "grouped"]:
        shutil.rmtree(SQL_ROOT / dirname, ignore_errors=True)


def write_sql_files(manifest: dict[str, Any]) -> None:
    remove_generated_sql_dirs()
    for path, sql in generated_files(manifest).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(sql, encoding="utf-8")
        print(f"wrote {path.relative_to(FRONTEND_ROOT)}")


def main() -> int:
    manifest = build_manifest()
    write_manifest(manifest)
    write_sql_files(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
