from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


SCRIPT_PATH = Path(__file__).resolve()
FRONTEND_ROOT = SCRIPT_PATH.parents[1]
REPO_ROOT = FRONTEND_ROOT.parent
SQL_ROOT = FRONTEND_ROOT / "sql" / "nav-positions"
MANIFEST_PATH = SQL_ROOT / "rules_manifest.json"

EXPECTED_SQL_FILES = [
    SQL_ROOT / "marts" / "grouped_latest.sql",
    SQL_ROOT / "marts" / "grouped_with_raw_examples.sql",
    SQL_ROOT / "marts" / "account_breakout.sql",
    SQL_ROOT / "checks" / "rule_exceptions.sql",
    SQL_ROOT / "checks" / "grouped_vs_raw_totals.sql",
    SQL_ROOT / "drilldowns" / "raw_rows_for_group.sql",
]

DERIVED_SOURCE_COLUMNS = [
    "product_code",
    "product_group",
    "product_region",
    "underlying_product_code",
    "contract_yyyymm",
    "contract_day",
    "put_call",
    "normalized_strike_price",
    "normalization_status",
]


def npm_command() -> str:
    return "npm.cmd" if os.name == "nt" else "npm"


def run_generator() -> None:
    subprocess.run(
        [npm_command(), "run", "sql:nav-positions"],
        cwd=FRONTEND_ROOT,
        check=True,
    )


def load_backend_db():
    sys.path.insert(0, str(REPO_ROOT))
    from backend.utils import db  # noqa: PLC0415

    return db


def load_sql(path: Path) -> str:
    sql = path.read_text(encoding="utf-8").rstrip()
    if sql.endswith(";"):
        sql = sql[:-1].rstrip()
    return sql


def fetch_one(db: Any, sql: str) -> dict[str, Any]:
    rows = db.execute_sql(sql, fetch=True)
    if not rows:
        raise RuntimeError("Expected one row but query returned no rows.")
    return rows[0]


def count_sql_rows(db: Any, path: Path) -> int:
    sql = load_sql(path)
    row = fetch_one(db, f"select count(*)::int as row_count from ({sql}) checked")
    return int(row["row_count"])


def validate_generated_files() -> list[str]:
    failures: list[str] = []

    for path in EXPECTED_SQL_FILES:
        if not path.exists():
            failures.append(f"missing generated SQL file: {path}")
            continue

        content = path.read_text(encoding="utf-8")
        if not content.startswith("-- Generated by npm run sql:nav-positions."):
            failures.append(f"missing generated header: {path}")
        if "positions_with_rules as (" not in content:
            failures.append(f"missing positions_with_rules CTE: {path}")
        if "select * from final;" not in content.lower():
            failures.append(f"missing select * from final: {path}")

    if not MANIFEST_PATH.exists():
        failures.append(f"missing rule manifest: {MANIFEST_PATH}")

    return failures


def load_manifest() -> dict[str, Any]:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def validate_manifest(manifest: dict[str, Any]) -> list[str]:
    failures: list[str] = []
    if manifest.get("productDefinitionCount", 0) <= 0:
        failures.append("rule manifest has no product definitions")
    if manifest.get("productAliasCount", 0) <= 0:
        failures.append("rule manifest has no product aliases")
    if manifest.get("navAliasCount", 0) <= 0:
        failures.append("rule manifest has no NAV aliases")
    if len(manifest.get("productDefinitions", [])) != manifest.get("productDefinitionCount"):
        failures.append("product definition count does not match manifest payload")
    if len(manifest.get("productAliases", [])) != manifest.get("productAliasCount"):
        failures.append("product alias count does not match manifest payload")
    if len(manifest.get("navAliases", [])) != manifest.get("navAliasCount"):
        failures.append("NAV alias count does not match manifest payload")
    return failures


def validate_db_results(db: Any) -> tuple[list[str], dict[str, Any]]:
    failures: list[str] = []
    results: dict[str, Any] = {}

    row_counts = {
        path.relative_to(SQL_ROOT).as_posix(): count_sql_rows(db, path)
        for path in EXPECTED_SQL_FILES
    }
    results["row_counts"] = row_counts

    exception_count = row_counts["checks/rule_exceptions.sql"]
    if exception_count != 0:
        failures.append(f"rule exceptions returned {exception_count} rows")

    totals_sql = load_sql(SQL_ROOT / "checks" / "grouped_vs_raw_totals.sql")
    totals = fetch_one(db, f"select * from ({totals_sql}) checked")
    results["grouped_vs_raw_totals"] = totals

    exact_zero_columns = ["row_count_diff"]
    quantity_columns = [
        "qty_total_diff",
        "qty_agr_diff",
        "qty_moross_diff",
        "qty_pnt_diff",
        "qty_titan_diff",
    ]
    valuation_columns = [
        "cost_base_diff",
        "market_value_base_diff",
        "unrealized_pnl_base_diff",
    ]

    for column in exact_zero_columns:
        if int(totals[column]) != 0:
            failures.append(f"{column} expected 0, got {totals[column]}")

    for column in quantity_columns:
        if abs(float(totals[column] or 0)) > 1e-9:
            failures.append(f"{column} expected near 0, got {totals[column]}")

    for column in valuation_columns:
        if abs(float(totals[column] or 0)) > 1e-4:
            failures.append(f"{column} expected within 1e-4, got {totals[column]}")

    derived_column_sql = f"""
      select column_name
      from information_schema.columns
      where table_schema = 'nav'
        and table_name = 'positions'
        and column_name in ({", ".join(repr(column) for column in DERIVED_SOURCE_COLUMNS)})
      order by column_name;
    """
    derived_columns = db.execute_sql(derived_column_sql, fetch=True)
    results["derived_source_columns"] = [
        row["column_name"] for row in derived_columns
    ]
    if derived_columns:
        failures.append(
            "nav.positions still has derived columns: "
            + ", ".join(row["column_name"] for row in derived_columns)
        )

    return failures, results


def main() -> int:
    print("Regenerating NAV position SQL with Python from JSON rules...")
    run_generator()

    failures = validate_generated_files()
    manifest: dict[str, Any] = {}
    if MANIFEST_PATH.exists():
        manifest = load_manifest()
        failures.extend(validate_manifest(manifest))

    print(
        "Rule manifest: "
        f"{manifest.get('productDefinitionCount', 0)} product definitions, "
        f"{manifest.get('productAliasCount', 0)} total aliases, "
        f"{manifest.get('navAliasCount', 0)} NAV aliases"
    )

    print("Running generated SQL against Postgres...")
    db = load_backend_db()
    db_failures, results = validate_db_results(db)
    failures.extend(db_failures)

    print("Generated SQL row counts:")
    for relative_path, row_count in results.get("row_counts", {}).items():
        print(f"  {relative_path}: {row_count:,}")

    totals = results.get("grouped_vs_raw_totals", {})
    if totals:
        print("Grouped vs raw totals:")
        for key, value in totals.items():
            print(f"  {key}: {value}")

    derived_columns = results.get("derived_source_columns", [])
    print(
        "Derived columns in nav.positions: "
        + (", ".join(derived_columns) if derived_columns else "none")
    )

    if failures:
        print("Verification failed:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print("Verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
