-- Source-table DDL for clear_street.eod_transactions.
--
-- This file is reference/operator SQL only. It is outside dbt model-paths and
-- should not be run by dbt. Read-only dbt credentials cannot run this.
-- Apply it manually with the helios_admin role before running
-- backend.scrapes.clear_street.transactions or
-- backend.orchestration.clear_street.transactions.
--
-- Source system: Clear Street SFTP Helios_Transactions_*.csv files.
-- Grain: trade_date_from_sftp x sftp_upload_timestamp x row_number_for_trades.
-- Safe rerun: backend upserts by the primary key, preserving distinct Clear
-- Street uploads for the same trade date.

CREATE TABLE IF NOT EXISTS clear_street.eod_transactions (
    trade_date_from_sftp VARCHAR NOT NULL,
    sftp_upload_timestamp TIMESTAMPTZ NOT NULL,
    row_number_for_trades INTEGER NOT NULL,
    record_id VARCHAR,
    firm VARCHAR,
    organization VARCHAR,
    account_number VARCHAR,
    account_type VARCHAR,
    currency_symbol VARCHAR,
    rr VARCHAR,
    trade_date VARCHAR,
    buy_sell VARCHAR,
    quantity INTEGER,
    exchange VARCHAR,
    futures_code VARCHAR,
    symbol VARCHAR,
    contract_year_month INTEGER,
    prompt_day INTEGER,
    strike_price DOUBLE PRECISION,
    put_call VARCHAR,
    security_description VARCHAR,
    trade_price DOUBLE PRECISION,
    printable_price VARCHAR,
    trade_type VARCHAR,
    order_number VARCHAR,
    security_type_code VARCHAR,
    cusip VARCHAR,
    comment_code VARCHAR,
    give_in_out_code VARCHAR,
    give_in_out_firm_num VARCHAR,
    spread_code VARCHAR,
    open_close_code VARCHAR,
    trace_num_or_unique_identifier VARCHAR,
    round_turn_half_turn_account VARCHAR,
    executing_broker VARCHAR,
    opposing_broker VARCHAR,
    oppos_firm VARCHAR,
    commission DOUBLE PRECISION,
    comm_act_type VARCHAR,
    fee_amt_1 DOUBLE PRECISION,
    fee_1_atype VARCHAR,
    fee_amt_2 DOUBLE PRECISION,
    fee_2_atype VARCHAR,
    fee_amt_3 DOUBLE PRECISION,
    fee_3_atype VARCHAR,
    brokerage DOUBLE PRECISION,
    brkrage_atype VARCHAR,
    give_io_charge DOUBLE PRECISION,
    give_io_atype VARCHAR,
    other_charges DOUBLE PRECISION,
    other_atype VARCHAR,
    wire_charge DOUBLE PRECISION,
    wire_chg_atype VARCHAR,
    fee_type_6 DOUBLE PRECISION,
    fee_type_6_atype VARCHAR,
    date VARCHAR,
    option_exp_date VARCHAR,
    last_trd_date VARCHAR,
    net_amount VARCHAR,
    traded_exchg VARCHAR,
    sub_exchange VARCHAR,
    exchange_name VARCHAR,
    exch_comm_cd VARCHAR,
    multiplication_factor VARCHAR,
    subaccount VARCHAR,
    instr_type VARCHAR,
    cash_settled VARCHAR,
    instrument_description VARCHAR,
    fee_amt_4 DOUBLE PRECISION,
    fee_4_atype VARCHAR,
    fee_amt_5 DOUBLE PRECISION,
    fee_5_atype VARCHAR,
    fee_amt_7 DOUBLE PRECISION,
    fee_7_atype VARCHAR,
    fee_amt_8 DOUBLE PRECISION,
    fee_8_atype VARCHAR,
    fee_amt_9 DOUBLE PRECISION,
    fee_9_atype VARCHAR,
    fee_amt_10 DOUBLE PRECISION,
    fee_10_atype VARCHAR,
    fee_amt_11 DOUBLE PRECISION,
    fee_11_atype VARCHAR,
    fee_amt_12 DOUBLE PRECISION,
    fee_12_atype VARCHAR,
    fee_amt_13 DOUBLE PRECISION,
    fee_13_atype VARCHAR,
    clearing_time_hhmmss VARCHAR,
    settlement_price DOUBLE PRECISION,
    broker VARCHAR,
    isin VARCHAR,
    mic VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (
        trade_date_from_sftp,
        sftp_upload_timestamp,
        row_number_for_trades
    )
);
