-- Table DDL for ops.api_fetch_log.
--
-- This file is disabled as a dbt model in dbt_project.yml. It is retained as
-- operator reference SQL only. Read-only dbt credentials cannot run this.
-- Apply it manually with the helios_admin role before scheduling scrapes that
-- write API fetch telemetry.

CREATE TABLE IF NOT EXISTS ops.api_fetch_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR NOT NULL,
    actor_type VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    pipeline_name VARCHAR,
    run_id VARCHAR,
    operation_name VARCHAR NOT NULL,
    content_id INTEGER,
    feed_name VARCHAR,
    target_table VARCHAR,
    method VARCHAR NOT NULL,
    target_host VARCHAR NOT NULL,
    target_path TEXT NOT NULL,
    status VARCHAR NOT NULL,
    http_status INTEGER,
    attempt INTEGER NOT NULL DEFAULT 1,
    max_attempts INTEGER NOT NULL DEFAULT 1,
    elapsed_ms INTEGER NOT NULL,
    rows_returned INTEGER,
    rows_written INTEGER,
    error_type VARCHAR(255),
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
