"""Compile position and trade product rules into standalone SQL files."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from backend.scrapes.clear_street.transactions import TARGET_TABLE_FQN
from backend.scrapes.positions_and_trades.rules.engine.product_lookup import (
    DEFAULT_RULE_SET,
    ProductAliasRule,
    ProductDefinition,
    ProductRuleSet,
    find_product_alias,
)

DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / "generated"
DEFAULT_SOURCE_TABLE = TARGET_TABLE_FQN
DEFAULT_NAV_SOURCE_TABLE = "nav.positions"
DEFAULT_ALIAS_SOURCE = "clear_street"
DEFAULT_NAV_ALIAS_SOURCE = "nav"
DEFAULT_LOG_LEVEL = logging.INFO

LOGGER = logging.getLogger(__name__)

CLEAR_STREET_GENERATED_HEADER = """\
-- Generated by python -m backend.scrapes.positions_and_trades.sql.generator.
-- Source of truth: backend/scrapes/positions_and_trades/rules/data/*.py.
-- Do not edit directly. Update the Python rule catalogues and regenerate this file.
--
-- Purpose: read-only latest MUFG Clear Street trade extract.
-- How to read: CTEs are numbered in dependency order; the final SELECT keeps
-- the legacy export shape.
-- Debugging tip: replace the final SELECT with SELECT * FROM any named CTE to
-- inspect that stage in a SQL editor.
-- Persistence: this script does not create, update, insert, or delete rows.
"""

NAV_GENERATED_HEADER = """\
-- Generated by python -m backend.scrapes.positions_and_trades.sql.generator.
-- Source of truth: backend/scrapes/positions_and_trades/rules/data/*.py.
-- Do not edit directly. Update the Python rule catalogues and regenerate this file.
--
-- Purpose: read-only NAV position query shaping and validation.
-- How to read: CTEs are numbered in dependency order; the final SELECT keeps
-- one operator-friendly mart, check, or drilldown shape.
-- Debugging tip: replace the final SELECT with SELECT * FROM any named CTE to
-- inspect that stage in a SQL editor.
-- Persistence: this script does not create, update, insert, or delete rows.
"""

MONTH_CODE_SQL = """\
case contract_month_number
        when 1 then 'F'
        when 2 then 'G'
        when 3 then 'H'
        when 4 then 'J'
        when 5 then 'K'
        when 6 then 'M'
        when 7 then 'N'
        when 8 then 'Q'
        when 9 then 'U'
        when 10 then 'V'
        when 11 then 'X'
        when 12 then 'Z'
    end"""

SqlCte = tuple[str, str, str]


@dataclass(frozen=True)
class CompileDiagnostics:
    total_product_definitions: int
    total_alias_rules: int
    included_alias_rules: int
    exact_alias_rules: int
    regex_alias_rules: int
    aliases_with_unknown_products: tuple[str, ...]
    exact_alias_self_test_failures: tuple[str, ...]

    @property
    def passed(self) -> bool:
        return not self.aliases_with_unknown_products and not (
            self.exact_alias_self_test_failures
        )


def build_clear_street_trades_mufg_latest_sql(
    source_table: str = DEFAULT_SOURCE_TABLE,
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return the latest MUFG Clear Street trade extract with rule fields."""
    return _with_header(
        "clear_street_trades/mufg/latest.sql",
        _clear_street_trades_mufg_latest_query(source_table, alias_source, rule_set),
        CLEAR_STREET_GENERATED_HEADER,
    )


def build_clear_street_trades_mufg_all_history_sql(
    source_table: str = DEFAULT_SOURCE_TABLE,
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return all-history MUFG Clear Street trade extract with rule fields."""
    header = CLEAR_STREET_GENERATED_HEADER.replace(
        "Purpose: read-only latest MUFG Clear Street trade extract.",
        "Purpose: read-only all-history MUFG Clear Street trade extract.",
    )
    return _with_header(
        "clear_street_trades/mufg/all_history.sql",
        _clear_street_trades_mufg_all_history_query(
            source_table,
            alias_source,
            rule_set,
        ),
        header,
    )


def build_nav_positions_grouped_latest_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return grouped latest NAV positions with product-rule fields."""
    return _with_header(
        "nav_positions/marts/grouped_latest.sql",
        _nav_grouped_latest_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def build_nav_positions_grouped_with_raw_examples_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return grouped latest NAV positions with raw source examples."""
    return _with_header(
        "nav_positions/marts/grouped_with_raw_examples.sql",
        _nav_grouped_with_raw_examples_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def build_nav_positions_account_breakout_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return account-level NAV position breakout query SQL."""
    return _with_header(
        "nav_positions/marts/account_breakout.sql",
        _nav_account_breakout_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def build_nav_positions_rule_exceptions_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return NAV position product-rule exception query SQL."""
    return _with_header(
        "nav_positions/checks/rule_exceptions.sql",
        _nav_rule_exceptions_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def build_nav_positions_grouped_vs_raw_totals_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return NAV grouped-vs-raw total reconciliation SQL."""
    return _with_header(
        "nav_positions/checks/grouped_vs_raw_totals.sql",
        _nav_grouped_vs_raw_totals_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def build_nav_positions_raw_rows_for_group_sql(
    source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> str:
    """Return raw NAV position drilldown query SQL."""
    return _with_header(
        "nav_positions/drilldowns/raw_rows_for_group.sql",
        _nav_raw_rows_for_group_query(source_table, alias_source, rule_set),
        NAV_GENERATED_HEADER,
    )


def _clear_street_trades_mufg_latest_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    return f"""{_clear_street_rule_ctes(source_table, alias_source, rule_set)},
{_clear_street_export_code_ctes()},
{_clear_street_latest_sftp_date_cte()},
{_clear_street_mufg_final_cte(
    latest_only=True,
    title="CTE 14 - final",
    description=(
        "Keeps the raw Clear Street columns first, then appends generated "
        "fields needed by the outbound file."
    ),
)}"""


def _clear_street_trades_mufg_all_history_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    return f"""{_clear_street_rule_ctes(source_table, alias_source, rule_set)},
{_clear_street_export_code_ctes()},
{_clear_street_mufg_final_cte(
    latest_only=False,
    title="CTE 13 - final",
    description=(
        "Keeps the same columns and MUFG give-in/out filter as latest.sql, "
        "but does not restrict results to the latest SFTP trade date."
    ),
)}"""


def _clear_street_export_code_ctes() -> str:
    export_base = dedent(
        """\
trades_with_export_base as (
    select
        trades_with_rules.*,
        trim(
            trailing '.'
            from trim(
                trailing '0'
                from to_char(strike_price_normalized, 'FM999999999.999')
            )
        ) as strike_text,
        case
            when rule_exchange_name = 'IFED' and product_code = 'HHD'
            then product_code || ' B0-IUS'
            when product_code in ('PDP', 'PWA', 'DDP')
            then product_code || ' D0-IUS'
            when
                rule_exchange_name = 'IFED'
                and is_option
                and put_call_code is not null
                and strike_price_normalized is not null
                and futures_month_code_yy is not null
            then product_code || ' ' || futures_month_code_yy || put_call_code
                || round(strike_price_normalized)::integer::text || '-IUS'
            when
                rule_exchange_name = 'IFED'
                and not is_option
                and contract_day is null
                and futures_month_code_yy is not null
            then product_code || ' ' || futures_month_code_yy || '-IUS'
        end as ice_product_code
    from trades_with_rules
)
"""
    )
    export_codes = dedent(
        """\
trades_with_export_codes as (
    select
        trades_with_export_base.*,
        case
            when product_code in ('HP', 'PHH', 'HH', 'H', 'NG') and contract_yyyymm is not null
            then '1|G|XNYM:F:NG:' || contract_yyyymm
            when
                product_code in ('LN', 'PHE')
                and contract_yyyymm is not null
                and put_call_code is not null
                and strike_price_normalized is not null
            then '1|G|XNYM:O:LN:' || contract_yyyymm || ':' || put_call_code || ':' || strike_text
            when
                (
                    product_code in ('LN1', 'LN2', 'LN3', 'LN4', 'LN5')
                    or product_code = 'KN4'
                )
                and contract_yyyymm is not null
                and put_call_code is not null
                and strike_price_normalized is not null
            then '1|G|XNYM:O:KN' || substring(product_code from 3) || ':'
                || contract_yyyymm || ':' || put_call_code || ':' || strike_text
            when product_code in ('G3', 'G4')
            then 'CAL_SPREAD_CME_EXCEL_CODE'
        end as cme_product_code,
        case
            when product_code = 'HP' and bbg_exchange_code = 'ZA' and futures_month_code_y is not null
            then bbg_exchange_code || futures_month_code_y || ' COMDTY'
            when product_code = 'HH' and bbg_exchange_code = 'IW' and futures_month_code_y is not null
            then bbg_exchange_code || futures_month_code_y || ' COMDTY'
            when product_code = 'NG' and bbg_exchange_code = 'NG' and futures_month_code_yy is not null
            then bbg_exchange_code || futures_month_code_yy || ' COMDTY'
            when
                product_code in ('LN', 'PHE')
                and bbg_exchange_code = 'NG'
                and futures_month_code_y is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_y || put_call_code || ' '
                || strike_text || ' COMDTY'
            when
                product_code in ('LN1', 'LN2', 'LN3', 'LN4', 'LN5')
                and futures_month_code_yy is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_yy || put_call_code
                || substring(product_code from 3) || ' ' || strike_text || ' COMB'
            when
                product_code = 'KN4'
                and futures_month_code_yy is not null
                and put_call_code is not null
                and strike_text is not null
            then bbg_exchange_code || futures_month_code_yy || put_call_code
                || substring(product_code from 3) || ' ' || strike_text || ' Comdty'
        end as bbg_product_code
    from trades_with_export_base
)
"""
    )
    return _join_cte_tail(
        (
            "CTE 11 - trades_with_export_base",
            "Formats strike text once and derives ICE codes before CME/BBG "
            "codes reuse those normalized fields.",
            export_base,
        ),
        (
            "CTE 12 - trades_with_export_codes",
            "Adds CME and Bloomberg product codes from normalized contract, "
            "option, strike, and product metadata.",
            export_codes,
        ),
    )


def _clear_street_latest_sftp_date_cte() -> str:
    cte_sql = dedent(
        """\
latest_sftp_date as (
    select max(trade_date_from_sftp) as trade_date_from_sftp
    from source_trades
)
"""
    )
    return _format_cte(
        (
            "CTE 13 - latest_sftp_date",
            "Finds the newest available Clear Street SFTP trade date after "
            "the optional params filter.",
            cte_sql,
        )
    )


def _clear_street_mufg_final_cte(
    *,
    latest_only: bool,
    title: str,
    description: str,
) -> str:
    latest_join = (
        "join latest_sftp_date\n"
        "    on latest_sftp_date.trade_date_from_sftp = trades_with_export_codes.trade_date_from_sftp\n"
        if latest_only
        else ""
    )
    return dedent(
        f"""\
{_sql_comment(title, description)}
final as (
select
    -- Raw Clear Street transaction columns, kept in legacy extract order.
    record_id,
    firm,
    organization,
    account_number,
    account_type,
    currency_symbol,
    rr,
    trade_date,
    buy_sell,
    quantity,
    exchange,
    futures_code,
    symbol,
    contract_year_month,
    prompt_day,
    strike_price,
    put_call,
    security_description,
    trade_price,
    printable_price,
    trade_type,
    order_number,
    security_type_code,
    cusip,
    comment_code,
    give_in_out_code,
    give_in_out_firm_num,
    spread_code,
    open_close_code,
    trace_num_or_unique_identifier,
    round_turn_half_turn_account,
    executing_broker,
    opposing_broker,
    oppos_firm,
    commission,
    comm_act_type,
    fee_amt_1,
    fee_1_atype,
    fee_amt_2,
    fee_2_atype,
    fee_amt_3,
    fee_3_atype,
    brokerage,
    brkrage_atype,
    give_io_charge,
    give_io_atype,
    other_charges,
    other_atype,
    wire_charge,
    wire_chg_atype,
    fee_type_6,
    fee_type_6_atype,
    date,
    case
        when nullif(trim(option_exp_date), '') is null then null
        when trim(option_exp_date) < '0001-01-01' then null
        else option_exp_date
    end as option_exp_date,
    last_trd_date,
    net_amount,
    traded_exchg,
    sub_exchange,
    exchange_name,
    exch_comm_cd,
    multiplication_factor,
    subaccount,
    instr_type,
    cash_settled,
    instrument_description,
    fee_amt_4,
    fee_4_atype,
    fee_amt_5,
    fee_5_atype,
    fee_amt_7,
    fee_7_atype,
    fee_amt_8,
    fee_8_atype,
    fee_amt_9,
    fee_9_atype,
    fee_amt_10,
    fee_10_atype,
    fee_amt_11,
    fee_11_atype,
    fee_amt_12,
    fee_12_atype,
    fee_amt_13,
    fee_13_atype,
    clearing_time_hhmmss,
    settlement_price,
    broker,
    isin,
    mic,

    -- Generated fields used by downstream review/export workflows.
    to_date(trades_with_export_codes.trade_date_from_sftp, 'YYYYMMDD') as sftp_date,
    sftp_upload_timestamp::timestamp as sftp_upload_timestamp,
    'New' as trade_status,
    product_family as product_code_grouping,
    market_name as product_code_region,
    underlying_product_code as product_code_underlying,
    ice_product_code,
    cme_product_code,
    bbg_product_code
from trades_with_export_codes
{latest_join}\
-- MUFG give-in/out firms from the legacy extract.
where give_in_out_firm_num in ('ADU', '905')
order by
    sftp_date desc,
    sftp_upload_timestamp desc,
    product_code_grouping,
    product_code_region
)
select * from final;
"""
    ).strip()


def _nav_grouped_latest_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    group_cols = _nav_group_by_grouping_columns()
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - grouped latest NAV positions",
    "Groups the latest NAV upload by product, contract, option, and strike.",
)}
final as (
    select
        max(nav_date) as nav_date,
        max(sftp_upload_timestamp)::text as latest_upload_at,
        {group_cols},
        string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
        string_agg(distinct account_group, ', ' order by account_group) filter (
            where account_group is not null and account_group <> ''
        ) as account_groups,
        count(distinct fund_code)::integer as fund_count,
        count(distinct account_group)::integer as account_group_count,
        count(distinct account)::integer as account_count,
        count(*)::integer as row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_total,
        sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
        sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
        sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
        sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
        sum(coalesce(quantity_1, 0))::double precision as net_quantity,
        sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity,
        sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
        sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base,
        (
            sum(case when trade_price is not null then trade_price * abs(coalesce(quantity_1, 0)) else 0 end)
            / nullif(sum(case when trade_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
        )::double precision as avg_trade_price,
        (
            sum(case when market_settlement_price is not null then market_settlement_price * abs(coalesce(quantity_1, 0)) else 0 end)
            / nullif(sum(case when market_settlement_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
        )::double precision as avg_settlement_price
    from filtered_positions
    group by
        {group_cols}
)
select * from final;"""


def _nav_grouped_with_raw_examples_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    group_cols = _nav_group_by_grouping_columns()
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - grouped NAV positions with raw examples",
    "Adds source-value examples so product-rule output can be reviewed quickly.",
)}
final as (
    select
        max(nav_date) as nav_date,
        max(sftp_upload_timestamp)::text as latest_upload_at,
        {group_cols},
        string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
        string_agg(distinct account_group, ', ' order by account_group) filter (
            where account_group is not null and account_group <> ''
        ) as account_groups,
        count(distinct fund_code)::integer as fund_count,
        count(distinct account_group)::integer as account_group_count,
        count(distinct account)::integer as account_count,
        count(*)::integer as row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_total,
        sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
        sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
        sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
        sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
        sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
        string_agg(distinct product, ' | ' order by product) filter (
            where product is not null and product <> ''
        ) as raw_products,
        string_agg(distinct type, ' | ' order by type) filter (
            where type is not null and type <> ''
        ) as raw_types,
        string_agg(distinct month_year, ' | ' order by month_year) filter (
            where month_year is not null and month_year <> ''
        ) as raw_month_years,
        string_agg(distinct product_id_internal, ' | ' order by product_id_internal) filter (
            where product_id_internal is not null and product_id_internal <> ''
        ) as raw_product_ids_internal,
        string_agg(distinct client_symbol, ' | ' order by client_symbol) filter (
            where client_symbol is not null and client_symbol <> ''
        ) as raw_client_symbols,
        string_agg(distinct source_1_symbol, ' | ' order by source_1_symbol) filter (
            where source_1_symbol is not null and source_1_symbol <> ''
        ) as raw_source_1_symbols,
        string_agg(distinct source_3_symbol, ' | ' order by source_3_symbol) filter (
            where source_3_symbol is not null and source_3_symbol <> ''
        ) as raw_source_3_symbols,
        string_agg(distinct exchange_name, ' | ' order by exchange_name) filter (
            where exchange_name is not null and exchange_name <> ''
        ) as raw_exchange_names,
        string_agg(distinct call_put, ' | ' order by call_put) filter (
            where call_put is not null and call_put <> ''
        ) as raw_call_puts,
        string_agg(distinct strike_price::text, ' | ' order by strike_price::text) filter (
            where strike_price is not null
        ) as raw_strike_prices,
        string_agg(distinct rule_match_type, ' | ' order by rule_match_type) filter (
            where rule_match_type is not null and rule_match_type <> ''
        ) as rule_match_types,
        string_agg(distinct rule_pattern, ' | ' order by rule_pattern) filter (
            where rule_pattern is not null and rule_pattern <> ''
        ) as rule_patterns,
        string_agg(distinct source_file_name, ' | ' order by source_file_name) filter (
            where source_file_name is not null and source_file_name <> ''
        ) as source_file_names,
        (array_agg(source_file_name order by source_file_name, source_file_row_number))[1] as example_source_file_name,
        (array_agg(source_file_row_number order by source_file_name, source_file_row_number))[1] as example_source_file_row_number,
        min(account_group) as example_account_group,
        min(account) as example_account
    from filtered_positions
    group by
        {group_cols}
)
select * from final;"""


def _nav_account_breakout_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    group_cols = _nav_group_by_grouping_columns()
    account_group_cols = _nav_group_by_grouping_columns("account_grouped")
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - NAV account breakout",
    "Breaks grouped product rows back out by fund, account group, and account.",
)}
account_grouped as (
    select
        max(nav_date) as nav_date,
        max(sftp_upload_timestamp)::text as latest_upload_at,
        {group_cols},
        fund_code,
        account_group,
        account,
        count(*)::integer as row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_account,
        sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity_account,
        sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base_account,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base_account,
        sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base_account
    from filtered_positions
    group by
        {group_cols},
        fund_code,
        account_group,
        account
),
final as (
    select
        account_grouped.*,
        (
            sum(qty_account) over (
                partition by
                    {account_group_cols}
            )
        )::double precision as qty_total
    from account_grouped
)
select * from final;"""


def _nav_rule_exceptions_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - NAV product-rule exceptions",
    "Surfaces unresolved products and contract or option parsing issues.",
)}
final as (
    select
        rule_status,
        product,
        type,
        month_year,
        call_put,
        strike_price,
        product_code,
        product_family,
        market_name,
        contract_yyyymm,
        contract_day,
        count(*)::integer as row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_total,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
        min(source_file_name) as example_source_file_name,
        min(source_file_row_number) as example_source_file_row_number
    from filtered_positions
    where rule_status is distinct from 'ok'
       or product_code is null
       or (coalesce(trim(month_year), '') <> '' and contract_yyyymm is null)
    group by
        rule_status,
        product,
        type,
        month_year,
        call_put,
        strike_price,
        product_code,
        product_family,
        market_name,
        contract_yyyymm,
        contract_day
)
select * from final;"""


def _nav_grouped_vs_raw_totals_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    group_cols = _nav_group_by_grouping_columns()
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - NAV grouped vs raw totals",
    "Reconciles grouped product totals back to the latest raw NAV source rows.",
)}
grouped as (
    select
        {group_cols},
        count(*)::integer as row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_total,
        sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
        sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
        sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
        sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
        sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
        sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
    from filtered_positions
    group by
        {group_cols}
),
grouped_totals as (
    select
        count(*)::integer as grouped_row_count,
        sum(row_count)::integer as grouped_source_row_count,
        sum(qty_total)::double precision as qty_total,
        sum(qty_agr)::double precision as qty_agr,
        sum(qty_moross)::double precision as qty_moross,
        sum(qty_pnt)::double precision as qty_pnt,
        sum(qty_titan)::double precision as qty_titan,
        sum(cost_base)::double precision as cost_base,
        sum(market_value_base)::double precision as market_value_base,
        sum(unrealized_pnl_base)::double precision as unrealized_pnl_base
    from grouped
),
raw_totals as (
    select
        count(*)::integer as raw_row_count,
        sum(coalesce(quantity_1, 0))::double precision as qty_total,
        sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
        sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
        sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
        sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
        sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
        sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
        sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
    from filtered_positions
),
final as (
    select
        grouped_totals.grouped_row_count,
        raw_totals.raw_row_count,
        grouped_totals.grouped_source_row_count,
        grouped_totals.grouped_source_row_count - raw_totals.raw_row_count as row_count_diff,
        grouped_totals.qty_total - raw_totals.qty_total as qty_total_diff,
        grouped_totals.qty_agr - raw_totals.qty_agr as qty_agr_diff,
        grouped_totals.qty_moross - raw_totals.qty_moross as qty_moross_diff,
        grouped_totals.qty_pnt - raw_totals.qty_pnt as qty_pnt_diff,
        grouped_totals.qty_titan - raw_totals.qty_titan as qty_titan_diff,
        grouped_totals.cost_base - raw_totals.cost_base as cost_base_diff,
        grouped_totals.market_value_base - raw_totals.market_value_base as market_value_base_diff,
        grouped_totals.unrealized_pnl_base - raw_totals.unrealized_pnl_base as unrealized_pnl_base_diff
    from grouped_totals
    cross join raw_totals
)
select * from final;"""


def _nav_raw_rows_for_group_query(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    return f"""{_nav_positions_with_rules_ctes(source_table, alias_source, rule_set)},
{_sql_comment(
    "Final select - NAV raw rows for group",
    "Keeps raw rows with derived product fields for drilldown review.",
)}
final as (
    select
        fund_code,
        source_legal_entity,
        source_file_name,
        source_file_row_number,
        nav_date,
        sftp_upload_timestamp,
        broker_name,
        account_group,
        account,
        trade_date,
        product_id_internal,
        product,
        type,
        month_year,
        client_symbol,
        strike_price,
        call_put,
        product_currency_1,
        long_short,
        quantity_1,
        counter_currency_ccy2,
        ccy2_long_short,
        ccy2_quantity_2,
        trade_price,
        multiplier_and_tick_value,
        cost_in_base_currency,
        market_settlement_price,
        market_value_in_base_currency,
        exchange_name,
        source_1_symbol,
        source_3_symbol,
        option_style,
        product_code,
        product_family,
        market_name,
        underlying_product_code,
        contract_yyyymm,
        contract_day,
        put_call,
        strike_price_normalized,
        rule_status,
        rule_priority,
        rule_match_type,
        rule_pattern
    from filtered_positions
)
select * from final;"""


def _nav_positions_with_rules_ctes(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    validated_source_table = _validate_source_table(source_table)

    return _join_ctes(
        (
            "CTE 01 - params",
            "Optional SQL-editor filters. Leave all values null for the "
            "production-style latest NAV view.",
            _nav_params_cte(),
        ),
        (
            "CTE 02 - product_catalog",
            "Embedded product definitions compiled from "
            "rules/data/product_definition_catalog.py.",
            _product_catalog_cte(rule_set.product_definitions),
        ),
        (
            "CTE 03 - product_aliases",
            "NAV product aliases compiled from "
            "rules/data/product_alias_catalog.py.",
            _product_aliases_cte(rule_set.product_aliases, alias_source),
        ),
        (
            "CTE 04 - source_positions",
            "Raw NAV rows with optional fund and NAV-date filters applied.",
            _nav_source_positions_cte(validated_source_table),
        ),
        (
            "CTE 05 - latest_nav_by_fund",
            "Selects the requested NAV date or each fund's latest available date.",
            _nav_latest_nav_by_fund_cte(),
        ),
        (
            "CTE 06 - latest_upload_by_fund",
            "Keeps the latest SFTP upload for the selected NAV date per fund.",
            _nav_latest_upload_by_fund_cte(),
        ),
        (
            "CTE 07 - latest_positions",
            "Limits source rows to the selected latest fund uploads.",
            _nav_latest_positions_cte(),
        ),
        (
            "CTE 08 - normalized_positions",
            "Normalizes product text, option side, contract month, and "
            "daily contract fields.",
            _nav_normalized_positions_cte(),
        ),
        (
            "CTE 09 - rule_matches",
            "Finds the first source-specific product alias for each NAV row.",
            _nav_rule_matches_cte(),
        ),
        (
            "CTE 10 - positions_with_rules",
            "Adds derived product, contract, option, and rule-status fields.",
            _nav_positions_with_rules_cte(),
        ),
        (
            "CTE 11 - filtered_positions",
            "Applies optional product, market, account, status, and search filters.",
            _nav_filtered_positions_cte(),
        ),
    )


def _nav_params_cte() -> str:
    return dedent(
        """\
params as (
    select
        null::date as requested_nav_date,
        null::text as fund_filter,
        null::text as account_group_filter,
        null::text as product_search,
        null::text as product_family_filter,
        null::text as market_name_filter,
        null::text as product_code_filter,
        null::text as rule_status_filter
)"""
    )


def _nav_source_positions_cte(validated_source_table: str) -> str:
    return dedent(
        f"""\
source_positions as (
    select p.*
    from {validated_source_table} as p
    cross join params
    where (params.fund_filter is null or p.fund_code = params.fund_filter)
      and (params.requested_nav_date is null or p.nav_date = params.requested_nav_date)
)"""
    )


def _nav_latest_nav_by_fund_cte() -> str:
    return dedent(
        """\
latest_nav_by_fund as (
    select
        source_positions.fund_code,
        coalesce((select requested_nav_date from params), max(source_positions.nav_date)) as nav_date
    from source_positions
    group by source_positions.fund_code
)"""
    )


def _nav_latest_upload_by_fund_cte() -> str:
    return dedent(
        """\
latest_upload_by_fund as (
    select
        source_positions.fund_code,
        source_positions.nav_date,
        max(source_positions.sftp_upload_timestamp) as sftp_upload_timestamp
    from source_positions
    inner join latest_nav_by_fund latest
        on latest.fund_code = source_positions.fund_code
       and latest.nav_date = source_positions.nav_date
    group by source_positions.fund_code, source_positions.nav_date
)"""
    )


def _nav_latest_positions_cte() -> str:
    return dedent(
        """\
latest_positions as (
    select source_positions.*
    from source_positions
    inner join latest_upload_by_fund latest
        on latest.fund_code = source_positions.fund_code
       and latest.nav_date = source_positions.nav_date
       and latest.sftp_upload_timestamp = source_positions.sftp_upload_timestamp
)"""
    )


def _nav_normalized_positions_cte() -> str:
    return dedent(
        """\
normalized_positions as (
    select
        latest_positions.*,
        upper(regexp_replace(coalesce(latest_positions.product, ''), '[[:space:]]+', ' ', 'g')) as product_norm,
        (
            upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'PUT', 'C', 'P')
            or upper(coalesce(latest_positions.type, '')) like '%OPTION%'
        ) as is_option,
        case
            when upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'C') then 'C'
            when upper(coalesce(latest_positions.call_put, '')) in ('PUT', 'P') then 'P'
            else null
        end as put_call,
        case
            when latest_positions.month_year ~ '^\\s*\\d{1,2}/\\d{1,2}/\\d{4}\\s*$'
            then to_char(to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'), 'YYYYMM')
            when upper(trim(coalesce(latest_positions.month_year, ''))) ~ '^[A-Z]{3}\\d{2}$'
            then to_char(to_date(upper(trim(latest_positions.month_year)), 'MONYY'), 'YYYYMM')
            else null
        end as contract_yyyymm,
        case
            when latest_positions.month_year ~ '^\\s*\\d{1,2}/\\d{1,2}/\\d{4}\\s*$'
            then extract(day from to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'))::integer
            else null
        end as contract_day
    from latest_positions
)"""
    )


def _nav_rule_matches_cte() -> str:
    return dedent(
        """\
rule_matches as (
    select
        normalized_positions.*,
        matched_alias.priority as rule_priority,
        matched_alias.match_type as rule_match_type,
        matched_alias.pattern as rule_pattern,
        matched_alias.product_code as matched_product_code
    from normalized_positions
    left join lateral (
        select product_aliases.*
        from product_aliases
        where (
                (
                    product_aliases.match_type = 'exact'
                    and normalized_positions.product_norm = product_aliases.pattern
                )
                or (
                    product_aliases.match_type = 'regex'
                    and normalized_positions.product_norm ~* product_aliases.pattern
                )
            )
          and (
                product_aliases.option_type is null
                or product_aliases.option_type = case when normalized_positions.is_option then 'option' else 'future' end
            )
        order by product_aliases.priority
        limit 1
    ) matched_alias on true
)"""
    )


def _nav_positions_with_rules_cte() -> str:
    return dedent(
        """\
positions_with_rules as (
    select
        rule_matches.fund_code,
        rule_matches.source_legal_entity,
        rule_matches.source_file_name,
        rule_matches.source_file_row_number,
        rule_matches.nav_date,
        rule_matches.sftp_upload_timestamp,
        rule_matches.broker_name,
        rule_matches.account_group,
        rule_matches.account,
        rule_matches.trade_date,
        rule_matches.product_id_internal,
        rule_matches.product,
        rule_matches.type,
        rule_matches.month_year,
        rule_matches.client_symbol,
        rule_matches.strike_price,
        rule_matches.call_put,
        rule_matches.product_currency_1,
        rule_matches.long_short,
        rule_matches.quantity_1,
        rule_matches.counter_currency_ccy2,
        rule_matches.ccy2_long_short,
        rule_matches.ccy2_quantity_2,
        rule_matches.trade_price,
        rule_matches.multiplier_and_tick_value,
        rule_matches.cost_in_native_currency,
        rule_matches.open_exchange_rate,
        rule_matches.cost_in_base_currency,
        rule_matches.market_settlement_price,
        rule_matches.market_value_in_native_currency,
        rule_matches.close_exchange_rate,
        rule_matches.market_value_in_base_currency,
        rule_matches.sector,
        rule_matches.sub_sector,
        rule_matches.country,
        rule_matches.exchange_name,
        rule_matches.source_1_symbol,
        rule_matches.source_3_symbol,
        rule_matches.one_chicago_symbol,
        rule_matches.fas_level,
        rule_matches.option_style,
        rule_matches.created_at,
        rule_matches.updated_at,
        catalog.product_code,
        catalog.product_family,
        catalog.market_name,
        case when rule_matches.is_option then catalog.underlying_product_code else null end as underlying_product_code,
        catalog.bbg_exchange_code,
        catalog.default_exchange_name,
        rule_matches.contract_yyyymm,
        rule_matches.contract_day,
        rule_matches.put_call,
        case
            when rule_matches.strike_price is null then null
            else round(rule_matches.strike_price::numeric, 3)::double precision
        end as strike_price_normalized,
        case
            when catalog.product_code is null then 'unresolved_product'
            when coalesce(trim(rule_matches.month_year), '') <> '' and rule_matches.contract_yyyymm is null then 'unparsed_contract'
            when rule_matches.is_option and rule_matches.put_call is null then 'option_missing_put_call'
            when rule_matches.is_option and rule_matches.strike_price is null then 'option_missing_strike'
            else 'ok'
        end as rule_status,
        rule_matches.rule_priority,
        rule_matches.rule_match_type,
        rule_matches.rule_pattern
    from rule_matches
    left join product_catalog catalog
        on catalog.product_code = rule_matches.matched_product_code
)"""
    )


def _nav_filtered_positions_cte() -> str:
    return dedent(
        """\
filtered_positions as (
    select positions_with_rules.*
    from positions_with_rules
    cross join params
    where (params.account_group_filter is null or positions_with_rules.account_group = params.account_group_filter)
      and (params.product_family_filter is null or positions_with_rules.product_family = params.product_family_filter)
      and (params.market_name_filter is null or positions_with_rules.market_name = params.market_name_filter)
      and (params.product_code_filter is null or positions_with_rules.product_code = params.product_code_filter)
      and (params.rule_status_filter is null or positions_with_rules.rule_status = params.rule_status_filter)
      and (
            params.product_search is null
            or positions_with_rules.product ilike '%' || params.product_search || '%'
            or positions_with_rules.product_code ilike '%' || params.product_search || '%'
            or positions_with_rules.product_family ilike '%' || params.product_search || '%'
            or positions_with_rules.market_name ilike '%' || params.product_search || '%'
            or positions_with_rules.product_id_internal ilike '%' || params.product_search || '%'
            or positions_with_rules.client_symbol ilike '%' || params.product_search || '%'
            or positions_with_rules.source_1_symbol ilike '%' || params.product_search || '%'
            or positions_with_rules.source_3_symbol ilike '%' || params.product_search || '%'
            or positions_with_rules.account ilike '%' || params.product_search || '%'
        )
)"""
    )


def _nav_grouping_columns(alias: str = "") -> tuple[str, ...]:
    prefix = f"{alias}." if alias else ""
    return (
        f"{prefix}product_code",
        f"{prefix}product_family",
        f"{prefix}market_name",
        f"{prefix}underlying_product_code",
        f"{prefix}contract_yyyymm",
        f"{prefix}contract_day",
        f"{prefix}put_call",
        f"{prefix}strike_price_normalized",
    )


def _nav_group_by_grouping_columns(alias: str = "") -> str:
    return ",\n        ".join(_nav_grouping_columns(alias))


def generated_files(
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    source_table: str = DEFAULT_SOURCE_TABLE,
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    nav_source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    nav_alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> dict[Path, str]:
    """Return generated SQL file paths and contents without writing them."""
    resolved_output_dir = Path(output_dir)
    return {
        resolved_output_dir / "clear_street_trades" / "mufg" / "latest.sql": (
            build_clear_street_trades_mufg_latest_sql(
                source_table,
                alias_source,
                rule_set,
            )
        ),
        resolved_output_dir / "clear_street_trades" / "mufg" / "all_history.sql": (
            build_clear_street_trades_mufg_all_history_sql(
                source_table,
                alias_source,
                rule_set,
            )
        ),
        resolved_output_dir / "nav_positions" / "marts" / "grouped_latest.sql": (
            build_nav_positions_grouped_latest_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
        resolved_output_dir
        / "nav_positions"
        / "marts"
        / "grouped_with_raw_examples.sql": (
            build_nav_positions_grouped_with_raw_examples_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
        resolved_output_dir / "nav_positions" / "marts" / "account_breakout.sql": (
            build_nav_positions_account_breakout_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
        resolved_output_dir / "nav_positions" / "checks" / "rule_exceptions.sql": (
            build_nav_positions_rule_exceptions_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
        resolved_output_dir
        / "nav_positions"
        / "checks"
        / "grouped_vs_raw_totals.sql": (
            build_nav_positions_grouped_vs_raw_totals_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
        resolved_output_dir
        / "nav_positions"
        / "drilldowns"
        / "raw_rows_for_group.sql": (
            build_nav_positions_raw_rows_for_group_sql(
                nav_source_table,
                nav_alias_source,
                rule_set,
            )
        ),
    }


def write_generated_sql(
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    source_table: str = DEFAULT_SOURCE_TABLE,
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    nav_source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    nav_alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> list[Path]:
    """Write generated SQL files and return their paths."""
    files = generated_files(
        output_dir=output_dir,
        source_table=source_table,
        alias_source=alias_source,
        nav_source_table=nav_source_table,
        nav_alias_source=nav_alias_source,
        rule_set=rule_set,
    )
    written: list[Path] = []
    expected_paths = set(files)
    resolved_output_dir = Path(output_dir)
    if resolved_output_dir.exists():
        for stale_path in resolved_output_dir.rglob("*.sql"):
            if stale_path not in expected_paths:
                stale_path.unlink()
    for path, sql in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(sql, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def main(
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    source_table: str = DEFAULT_SOURCE_TABLE,
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    nav_source_table: str = DEFAULT_NAV_SOURCE_TABLE,
    nav_alias_source: str = DEFAULT_NAV_ALIAS_SOURCE,
    log_level: int = DEFAULT_LOG_LEVEL,
) -> int:
    """Generate standalone SQL review files for position and trade rules."""
    _configure_logging(log_level)
    written = write_generated_sql(
        output_dir=output_dir,
        source_table=source_table,
        alias_source=alias_source,
        nav_source_table=nav_source_table,
        nav_alias_source=nav_alias_source,
    )
    clear_street_diagnostics = collect_compile_diagnostics(
        alias_source=alias_source,
        rule_set=DEFAULT_RULE_SET,
    )
    nav_diagnostics = collect_compile_diagnostics(
        alias_source=nav_alias_source,
        rule_set=DEFAULT_RULE_SET,
    )
    _log_compile_summary(
        written=written,
        output_dir=output_dir,
        diagnostics_by_alias_source={
            alias_source: clear_street_diagnostics,
            nav_alias_source: nav_diagnostics,
        },
    )
    return 0


def collect_compile_diagnostics(
    alias_source: str = DEFAULT_ALIAS_SOURCE,
    rule_set: ProductRuleSet = DEFAULT_RULE_SET,
) -> CompileDiagnostics:
    """Return a no-DB rule self-check for generated SQL inputs."""
    products_by_code = rule_set.products_by_code
    included_aliases = _included_aliases(rule_set.product_aliases, alias_source)
    exact_aliases = tuple(
        alias for alias in included_aliases if alias.match_type == "exact"
    )
    regex_aliases = tuple(
        alias for alias in included_aliases if alias.match_type == "regex"
    )
    unknown_products = tuple(
        f"{alias.pattern} -> {alias.exchange_code}"
        for alias in included_aliases
        if alias.exchange_code not in products_by_code
    )

    exact_failures: list[str] = []
    for alias in exact_aliases:
        is_option = alias.option_type == "option"
        match = find_product_alias(
            alias_source,
            alias.pattern,
            is_option=is_option,
            rule_set=rule_set,
        )
        if match is None or match.exchange_code != alias.exchange_code:
            resolved = match.exchange_code if match else None
            exact_failures.append(
                f"{alias.pattern} expected {alias.exchange_code}, got {resolved}"
            )

    return CompileDiagnostics(
        total_product_definitions=len(rule_set.product_definitions),
        total_alias_rules=len(rule_set.product_aliases),
        included_alias_rules=len(included_aliases),
        exact_alias_rules=len(exact_aliases),
        regex_alias_rules=len(regex_aliases),
        aliases_with_unknown_products=unknown_products,
        exact_alias_self_test_failures=tuple(exact_failures),
    )


def _clear_street_rule_ctes(
    source_table: str,
    alias_source: str,
    rule_set: ProductRuleSet,
) -> str:
    validated_source_table = _validate_source_table(source_table)

    return _join_ctes(
        (
            "CTE 01 - params",
            "Optional SQL-editor filters. Leave all values null for the "
            "production-style latest extract.",
            _params_cte(),
        ),
        (
            "CTE 02 - product_catalog",
            "Embedded product definitions compiled from "
            "rules/data/product_definition_catalog.py.",
            _product_catalog_cte(rule_set.product_definitions),
        ),
        (
            "CTE 03 - product_aliases",
            "Source-specific product description aliases compiled from "
            "rules/data/product_alias_catalog.py.",
            _product_aliases_cte(rule_set.product_aliases, alias_source),
        ),
        (
            "CTE 04 - source_trades",
            "Raw Clear Street rows with optional params filters applied.",
            _source_trades_cte(validated_source_table),
        ),
        (
            "CTE 05 - prepared_trades",
            "Chooses the best source product description before normalization.",
            _prepared_trades_cte(),
        ),
        (
            "CTE 06 - normalized_base",
            "Normalizes product text, exchange code, contract month, option "
            "side, strike, exchange name, and cash-adjustment detection.",
            _normalized_base_cte(),
        ),
        (
            "CTE 07 - normalized_trades",
            "Adds contract year/month display fields and option detection.",
            _normalized_trades_cte(),
        ),
        (
            "CTE 08 - contract_trades",
            "Adds futures month codes and daily contract keys.",
            _contract_trades_cte(),
        ),
        (
            "CTE 09 - product_matches",
            "Resolves explicit product codes first, Clear Street futures "
            "description prefixes second, then the highest-priority source alias.",
            _product_matches_cte(),
        ),
        (
            "CTE 10 - trades_with_rules",
            "Produces canonical product fields and rule_status values for "
            "SQL-editor validation.",
            _trades_with_rules_cte(),
        ),
    )


def _join_ctes(*ctes: SqlCte) -> str:
    return "with\n" + _join_cte_tail(*ctes)


def _join_cte_tail(*ctes: SqlCte) -> str:
    return ",\n".join(_format_cte(cte) for cte in ctes)


def _format_cte(cte: SqlCte) -> str:
    title, description, sql = cte
    return f"{_sql_comment(title, description)}\n{sql.strip()}"


def _sql_comment(title: str, *lines: str) -> str:
    comment_lines = [
        "-- -----------------------------------------------------------------------------",
        f"-- {title}",
    ]
    comment_lines.extend(f"-- {line}" for line in lines if line)
    return "\n".join(comment_lines)


def _params_cte() -> str:
    return dedent(
        """\
params as (
    select
        null::date as trade_date_filter,
        null::text as account_number_filter,
        null::text as product_search
)"""
    )


def _product_catalog_cte(definitions: tuple[ProductDefinition, ...]) -> str:
    product_catalog = _product_catalog_values(definitions)
    return dedent(
        f"""\
product_catalog(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
) as (
    values
{product_catalog}
)"""
    )


def _product_aliases_cte(
    aliases: tuple[ProductAliasRule, ...],
    alias_source: str,
) -> str:
    product_aliases = _product_alias_values(aliases, alias_source)
    return dedent(
        f"""\
product_aliases(
    priority,
    source,
    match_type,
    pattern,
    product_code,
    option_type
) as (
    values
{product_aliases}
)"""
    )


def _source_trades_cte(validated_source_table: str) -> str:
    return dedent(
        f"""\
source_trades as (
    select
        t.*
    from {validated_source_table} as t
    cross join params as p
    where
        (
            p.trade_date_filter is null
            or t.trade_date_from_sftp = to_char(p.trade_date_filter, 'YYYYMMDD')
            or t.trade_date = to_char(p.trade_date_filter, 'YYYYMMDD')
        )
        and (
            p.account_number_filter is null
            or t.account_number = p.account_number_filter
        )
        and (
            p.product_search is null
            or upper(coalesce(t.futures_code, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.exch_comm_cd, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.symbol, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.security_description, '')) like '%' || upper(p.product_search) || '%'
            or upper(coalesce(t.instrument_description, '')) like '%' || upper(p.product_search) || '%'
        )
)"""
    )


def _prepared_trades_cte() -> str:
    return dedent(
        """\
prepared_trades as (
    select
        t.*,
        coalesce(
            nullif(trim(t.security_description), ''),
            nullif(trim(t.instrument_description), ''),
            nullif(trim(t.symbol), '')
        ) as rule_product
    from source_trades as t
)"""
    )


def _normalized_base_cte() -> str:
    return dedent(
        """\
normalized_base as (
    select
        p.*,
        nullif(
            upper(regexp_replace(coalesce(p.rule_product, ''), '[[:space:]]+', ' ', 'g')),
            ''
        ) as rule_product_norm,
        upper(
            coalesce(
                nullif(trim(p.futures_code), ''),
                nullif(trim(p.exch_comm_cd), '')
            )
        ) as rule_exchange_code,
        case
            when p.contract_year_month is not null
                and p.contract_year_month <> 0
                and lpad(p.contract_year_month::text, 6, '0') ~ '^(19|20|21)[0-9]{2}(0[1-9]|1[0-2])$'
            then lpad(p.contract_year_month::text, 6, '0')
        end as contract_yyyymm,
        case
            when p.prompt_day between 1 and 31 then p.prompt_day
        end as contract_day,
        case upper(nullif(trim(p.put_call), ''))
            when 'CALL' then 'C'
            when 'C' then 'C'
            when 'PUT' then 'P'
            when 'P' then 'P'
        end as put_call_code,
        case
            when p.strike_price is not null and p.strike_price <> 0
            then round(p.strike_price::numeric, 3)::double precision
        end as strike_price_normalized,
        upper(nullif(trim(p.security_type_code), '')) as security_type_code_norm,
        upper(nullif(trim(p.instr_type), '')) as instr_type_norm,
        case upper(nullif(trim(p.exchange_name), ''))
            when 'NYM' then 'NYME'
            when 'NYME' then 'NYME'
            when 'IFE' then 'IFED'
            when 'IPE' then 'IFED'
            when 'IFED' then 'IFED'
        end as exchange_name_normalized,
        (
            coalesce(p.quantity, 0) = 0
            and coalesce(p.contract_year_month, 0) = 0
            and upper(coalesce(p.security_description, '')) = 'UNITED STATES DOLLAR'
            and upper(coalesce(p.instrument_description, '')) like 'RESID ADJ%'
        ) as is_non_product_cash_adjustment
    from prepared_trades as p
)"""
    )


def _normalized_trades_cte() -> str:
    return dedent(
        """\
normalized_trades as (
    select
        b.*,
        case
            when b.contract_yyyymm is not null
            then left(b.contract_yyyymm, 4)::integer
        end as contract_year,
        case
            when b.contract_yyyymm is not null
            then right(b.contract_yyyymm, 2)::integer
        end as contract_month_number,
        case
            when b.contract_yyyymm is not null
            then left(b.contract_yyyymm, 4) || '-' || right(b.contract_yyyymm, 2)
        end as contract_month,
        (
            b.put_call_code is not null
            or b.security_type_code_norm in ('O', 'OPT', 'OPTION')
            or b.security_type_code_norm like '%OPTION%'
            or b.instr_type_norm in ('O', 'OPT', 'OPTION')
            or b.instr_type_norm like '%OPTION%'
        ) as is_option
    from normalized_base as b
)"""
    )


def _contract_trades_cte() -> str:
    return dedent(
        f"""\
contract_trades as (
    select
        n.*,
        {MONTH_CODE_SQL} as futures_month_code,
        case
            when n.contract_yyyymm is not null and n.contract_day is not null
            then n.contract_yyyymm || lpad(n.contract_day::text, 2, '0')
        end as contract_yyyymmdd
    from normalized_trades as n
)"""
    )


def _product_matches_cte() -> str:
    return dedent(
        """\
product_matches as (
    select
        c.*,
        explicit_catalog.product_code as explicit_product_code,
        explicit_catalog.product_family as explicit_product_family,
        explicit_catalog.market_name as explicit_market_name,
        explicit_catalog.underlying_product_code as explicit_underlying_product_code,
        explicit_catalog.bbg_exchange_code as explicit_bbg_exchange_code,
        explicit_catalog.default_exchange_name as explicit_default_exchange_name,
        prefix_catalog.product_code as prefix_product_code,
        prefix_catalog.product_family as prefix_product_family,
        prefix_catalog.market_name as prefix_market_name,
        prefix_catalog.underlying_product_code as prefix_underlying_product_code,
        prefix_catalog.bbg_exchange_code as prefix_bbg_exchange_code,
        prefix_catalog.default_exchange_name as prefix_default_exchange_name,
        alias_match.alias_product_code,
        alias_match.alias_product_family,
        alias_match.alias_market_name,
        alias_match.alias_underlying_product_code,
        alias_match.alias_bbg_exchange_code,
        alias_match.alias_default_exchange_name,
        alias_match.alias_priority,
        alias_match.alias_match_type,
        alias_match.alias_pattern
    from contract_trades as c
    left join product_catalog as explicit_catalog
        on explicit_catalog.product_code = c.rule_exchange_code
    left join product_catalog as prefix_catalog
        on explicit_catalog.product_code is null
        and not c.is_option
        and prefix_catalog.product_code = substring(
            c.rule_product_norm from '^([A-Z0-9]{1,10})-'
        )
    left join lateral (
        select
            catalog.product_code as alias_product_code,
            catalog.product_family as alias_product_family,
            catalog.market_name as alias_market_name,
            catalog.underlying_product_code as alias_underlying_product_code,
            catalog.bbg_exchange_code as alias_bbg_exchange_code,
            catalog.default_exchange_name as alias_default_exchange_name,
            alias.priority as alias_priority,
            alias.match_type as alias_match_type,
            alias.pattern as alias_pattern
        from product_aliases as alias
        join product_catalog as catalog
            on catalog.product_code = alias.product_code
        where
            explicit_catalog.product_code is null
            and prefix_catalog.product_code is null
            and c.rule_product_norm is not null
            and (
                alias.option_type is null
                or alias.option_type = case when c.is_option then 'option' else 'future' end
            )
            and (
                (
                    alias.match_type = 'exact'
                    and c.rule_product_norm = alias.pattern
                )
                or (
                    alias.match_type = 'regex'
                    and c.rule_product_norm ~* alias.pattern
                )
            )
        order by alias.priority
        limit 1
    ) as alias_match on true
)"""
    )


def _trades_with_rules_cte() -> str:
    return dedent(
        """\
trades_with_rules as (
    select
        m.*,
        coalesce(m.explicit_product_code, m.prefix_product_code, m.alias_product_code)
            as product_code,
        coalesce(
            m.explicit_product_family,
            m.prefix_product_family,
            m.alias_product_family
        ) as product_family,
        coalesce(m.explicit_market_name, m.prefix_market_name, m.alias_market_name)
            as market_name,
        case
            when m.is_option
            then coalesce(
                m.explicit_underlying_product_code,
                m.prefix_underlying_product_code,
                m.alias_underlying_product_code
            )
        end as underlying_product_code,
        coalesce(
            m.explicit_bbg_exchange_code,
            m.prefix_bbg_exchange_code,
            m.alias_bbg_exchange_code
        ) as bbg_exchange_code,
        coalesce(
            m.exchange_name_normalized,
            m.explicit_default_exchange_name,
            m.prefix_default_exchange_name,
            m.alias_default_exchange_name
        ) as rule_exchange_name,
        case
            when m.is_non_product_cash_adjustment
            then 'non_product_cash_adjustment'
            when coalesce(
                m.explicit_product_code,
                m.prefix_product_code,
                m.alias_product_code
            ) is null
            then 'unresolved_product'
            when m.contract_yyyymm is null
            then 'missing_contract_yyyymm'
            when m.is_option and m.put_call_code is null
            then 'option_missing_put_call'
            when m.is_option and m.strike_price_normalized is null
            then 'option_missing_strike'
            else 'ok'
        end as rule_status,
        case
            when m.explicit_product_code is not null then 'explicit'
            when m.prefix_product_code is not null then 'prefix'
            when m.alias_product_code is not null then 'alias'
        end as rule_match_source,
        m.alias_priority as rule_match_priority,
        m.alias_match_type as rule_match_type,
        m.alias_pattern as rule_match_pattern,
        case
            when m.futures_month_code is not null and m.contract_year is not null
            then m.futures_month_code || right(m.contract_year::text, 1)
        end as futures_month_code_y,
        case
            when m.futures_month_code is not null and m.contract_year is not null
            then m.futures_month_code || right(m.contract_year::text, 2)
        end as futures_month_code_yy
    from product_matches as m
)"""
    )


def _product_catalog_values(definitions: tuple[ProductDefinition, ...]) -> str:
    rows = [
        _sql_row(
            definition.exchange_code,
            definition.rule_group,
            definition.rule_region,
            definition.exchange_code_underlying,
            definition.bbg_exchange_code,
            definition.default_exchange_name,
        )
        for definition in definitions
    ]
    return _indent_join(rows, spaces=8)


def _product_alias_values(
    aliases: tuple[ProductAliasRule, ...],
    alias_source: str,
) -> str:
    included_aliases = _included_aliases(aliases, alias_source)
    rows = [
        _sql_row(
            priority,
            alias.source,
            alias.match_type,
            alias.pattern,
            alias.exchange_code,
            alias.option_type,
        )
        for priority, alias in enumerate(included_aliases, start=1)
    ]
    if not rows:
        raise ValueError(f"No product aliases found for source {alias_source!r}.")
    return _indent_join(rows, spaces=8)


def _included_aliases(
    aliases: tuple[ProductAliasRule, ...],
    alias_source: str,
) -> tuple[ProductAliasRule, ...]:
    included_sources = {alias_source, "any"}
    return tuple(alias for alias in aliases if alias.source in included_sources)


def _configure_logging(log_level: int) -> None:
    logging.basicConfig(level=log_level, format="%(levelname)s %(message)s")
    LOGGER.setLevel(log_level)


def _log_compile_summary(
    *,
    written: list[Path],
    output_dir: str | Path,
    diagnostics_by_alias_source: dict[str, CompileDiagnostics],
) -> None:
    resolved_output_dir = Path(output_dir)
    LOGGER.info(
        "Generated %s SQL files in %s",
        len(written),
        resolved_output_dir,
    )
    for path in written:
        LOGGER.info("Wrote %s", path)

    for alias_source, diagnostics in diagnostics_by_alias_source.items():
        LOGGER.info(
            "Rule pseudo-test for %s aliases: %s products, %s/%s aliases included "
            "(%s exact self-tested, %s regex compile-tested).",
            alias_source,
            diagnostics.total_product_definitions,
            diagnostics.included_alias_rules,
            diagnostics.total_alias_rules,
            diagnostics.exact_alias_rules,
            diagnostics.regex_alias_rules,
        )
        if diagnostics.aliases_with_unknown_products:
            LOGGER.warning(
                "Aliases reference unknown products: %s",
                "; ".join(diagnostics.aliases_with_unknown_products),
            )
        if diagnostics.exact_alias_self_test_failures:
            LOGGER.warning(
                "Exact alias pseudo-test failures: %s",
                "; ".join(diagnostics.exact_alias_self_test_failures),
            )
        if diagnostics.passed:
            LOGGER.info(
                "Rule pseudo-test passed for generated %s SQL inputs.",
                alias_source,
            )

    sql_path = resolved_output_dir / "clear_street_trades" / "mufg" / "latest.sql"
    LOGGER.info(
        "Run %s in a SQL editor to inspect the latest MUFG Clear Street extract.",
        sql_path,
    )
    nav_sql_path = resolved_output_dir / "nav_positions"
    LOGGER.info(
        "Run SQL under %s in a SQL editor to inspect NAV grouped/check/drilldown views.",
        nav_sql_path,
    )


def _with_header(filename: str, sql: str, header: str) -> str:
    body = dedent(sql).strip()
    return f"{header}-- File: {filename}\n\n{body}\n"


def _sql_row(*values: object) -> str:
    return "(" + ", ".join(_sql_literal(value) for value in values) + ")"


def _sql_literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _indent_join(rows: list[str], spaces: int) -> str:
    indent = " " * spaces
    return ",\n".join(f"{indent}{row}" for row in rows)


def _validate_source_table(source_table: str) -> str:
    if not re.fullmatch(
        r"[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)?",
        source_table,
    ):
        raise ValueError(
            "source_table must be an unquoted table name or schema-qualified table "
            f"name, got {source_table!r}."
        )
    return source_table


if __name__ == "__main__":
    raise SystemExit(main())
