/*
Initialize the HeliosCTA application database.

Run this while connected to `helios_prod` as `helios_admin`.

This script creates the standard application schemas, creates base tables that
the backend inserts into directly, grants read-only access, and installs
read-only defaults for future objects created by `helios_admin`.
*/

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM helios_readonly;

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('REVOKE ALL ON DATABASE %I FROM PUBLIC', db_name);
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO helios_admin', db_name);
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO helios_readonly', db_name);
END $$;

CREATE SCHEMA IF NOT EXISTS pjm AUTHORIZATION helios_admin;
CREATE SCHEMA IF NOT EXISTS ops AUTHORIZATION helios_admin;
CREATE SCHEMA IF NOT EXISTS alerts AUTHORIZATION helios_admin;

CREATE TABLE IF NOT EXISTS ops.api_fetch_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR NOT NULL,
    actor_type VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    pipeline_name VARCHAR,
    run_id VARCHAR,
    operation_name VARCHAR NOT NULL,
    content_id INTEGER,
    feed_name VARCHAR,
    target_table VARCHAR,
    method VARCHAR NOT NULL,
    target_host VARCHAR NOT NULL,
    target_path TEXT NOT NULL,
    status VARCHAR NOT NULL,
    http_status INTEGER,
    attempt INTEGER NOT NULL DEFAULT 1,
    max_attempts INTEGER NOT NULL DEFAULT 1,
    elapsed_ms INTEGER NOT NULL,
    rows_returned INTEGER,
    rows_written INTEGER,
    error_type VARCHAR(255),
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS alerts.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_key VARCHAR NOT NULL UNIQUE,
    alert_type VARCHAR NOT NULL,
    severity VARCHAR NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    source_system VARCHAR NOT NULL,
    event_time TIMESTAMP NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    recipient_emails JSONB NOT NULL DEFAULT '[]'::jsonb,
    acknowledged_by JSONB NOT NULL DEFAULT '[]'::jsonb,
    email_status VARCHAR NOT NULL DEFAULT 'pending',
    email_attempts INTEGER NOT NULL DEFAULT 0,
    email_claimed_at TIMESTAMPTZ,
    email_claim_token VARCHAR,
    email_claimed_by VARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT alerts_events_email_status_check
        CHECK (email_status IN ('pending', 'sending', 'sent', 'failed', 'suppressed'))
);

CREATE INDEX IF NOT EXISTS idx_api_fetch_log_created_at
    ON ops.api_fetch_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_fetch_log_pipeline
    ON ops.api_fetch_log (provider, operation_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_events_email_status
    ON alerts.events (email_status, email_attempts, event_time);

CREATE INDEX IF NOT EXISTS idx_alerts_events_recent
    ON alerts.events (event_time DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_events_source_time
    ON alerts.events (source_system, event_time DESC);

DO $$
DECLARE
    schema_name text;
BEGIN
    FOR schema_name IN
        SELECT nspname
        FROM pg_namespace
        WHERE nspname !~ '^pg_'
          AND nspname <> 'information_schema'
          AND nspname <> 'public'
        ORDER BY nspname
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO helios_readonly', schema_name);
        EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO helios_readonly', schema_name);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO helios_readonly', schema_name);
    END LOOP;
END $$;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT USAGE ON SCHEMAS TO helios_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT SELECT ON TABLES TO helios_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT USAGE, SELECT ON SEQUENCES TO helios_readonly;
