/*
Initialize the HeliosCTA application database.

Run this while connected to `helios_prod` as `helios_admin`.

This script creates the standard application schemas, creates base tables that
the backend inserts into directly, grants read-only access, and installs
read-only defaults for future objects created by `helios_admin`.
*/

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM helios_readonly;

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('REVOKE ALL ON DATABASE %I FROM PUBLIC', db_name);
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO helios_admin', db_name);
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO helios_readonly', db_name);
END $$;

CREATE SCHEMA IF NOT EXISTS pjm AUTHORIZATION helios_admin;
CREATE SCHEMA IF NOT EXISTS ops AUTHORIZATION helios_admin;
CREATE SCHEMA IF NOT EXISTS alerts AUTHORIZATION helios_admin;

CREATE TABLE IF NOT EXISTS pjm.da_hrl_lmps (
    datetime_beginning_utc TIMESTAMP NOT NULL,
    datetime_beginning_ept TIMESTAMP NOT NULL,
    pnode_id INTEGER NOT NULL,
    pnode_name VARCHAR NOT NULL,
    voltage VARCHAR,
    equipment VARCHAR,
    type VARCHAR,
    zone VARCHAR,
    system_energy_price_da DOUBLE PRECISION,
    total_lmp_da DOUBLE PRECISION,
    congestion_price_da DOUBLE PRECISION,
    marginal_loss_price_da DOUBLE PRECISION,
    row_is_current BOOLEAN NOT NULL,
    version_nbr INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (
        datetime_beginning_utc,
        pnode_id,
        pnode_name,
        row_is_current,
        version_nbr
    )
);

CREATE TABLE IF NOT EXISTS pjm.rt_hrl_lmps (
    datetime_beginning_utc TIMESTAMP NOT NULL,
    datetime_beginning_ept TIMESTAMP NOT NULL,
    pnode_id INTEGER NOT NULL,
    pnode_name VARCHAR NOT NULL,
    voltage VARCHAR,
    equipment VARCHAR,
    type VARCHAR,
    zone VARCHAR,
    system_energy_price_rt DOUBLE PRECISION,
    total_lmp_rt DOUBLE PRECISION,
    congestion_price_rt DOUBLE PRECISION,
    marginal_loss_price_rt DOUBLE PRECISION,
    row_is_current BOOLEAN NOT NULL,
    version_nbr INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (
        datetime_beginning_utc,
        pnode_id,
        pnode_name,
        row_is_current,
        version_nbr
    )
);

CREATE TABLE IF NOT EXISTS ops.api_fetch_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR NOT NULL,
    actor_type VARCHAR NOT NULL,
    provider VARCHAR NOT NULL,
    pipeline_name VARCHAR,
    run_id VARCHAR,
    operation_name VARCHAR NOT NULL,
    content_id INTEGER,
    feed_name VARCHAR,
    target_table VARCHAR,
    method VARCHAR NOT NULL,
    target_host VARCHAR NOT NULL,
    target_path TEXT NOT NULL,
    status VARCHAR NOT NULL,
    http_status INTEGER,
    attempt INTEGER NOT NULL DEFAULT 1,
    max_attempts INTEGER NOT NULL DEFAULT 1,
    elapsed_ms INTEGER NOT NULL,
    rows_returned INTEGER,
    rows_written INTEGER,
    error_type VARCHAR(255),
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ops.data_availability_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR NOT NULL UNIQUE,
    dataset VARCHAR NOT NULL,
    source_system VARCHAR NOT NULL,
    availability_type VARCHAR NOT NULL,
    business_date DATE,
    window_start TIMESTAMPTZ,
    window_end TIMESTAMPTZ,
    scope VARCHAR,
    grain VARCHAR,
    source_table VARCHAR,
    row_count INTEGER,
    entity_count INTEGER,
    period_count INTEGER,
    completeness_status VARCHAR NOT NULL DEFAULT 'unknown',
    run_id VARCHAR,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS alerts.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_key VARCHAR NOT NULL UNIQUE,
    alert_type VARCHAR NOT NULL,
    severity VARCHAR NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    source_system VARCHAR NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    recipient_emails JSONB NOT NULL DEFAULT '[]'::jsonb,
    acknowledged_by JSONB NOT NULL DEFAULT '[]'::jsonb,
    email_status VARCHAR NOT NULL DEFAULT 'pending',
    email_attempts INTEGER NOT NULL DEFAULT 0,
    email_claimed_at TIMESTAMPTZ,
    email_claim_token VARCHAR,
    email_claimed_by VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT alerts_events_email_status_check
        CHECK (email_status IN ('pending', 'sending', 'sent', 'failed', 'suppressed'))
);

ALTER TABLE alerts.events
    ALTER COLUMN event_time TYPE TIMESTAMPTZ
        USING event_time AT TIME ZONE 'UTC',
    ALTER COLUMN created_at TYPE TIMESTAMPTZ
        USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ
        USING updated_at AT TIME ZONE 'UTC';

CREATE INDEX IF NOT EXISTS idx_api_fetch_log_created_at
    ON ops.api_fetch_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_fetch_log_pipeline
    ON ops.api_fetch_log (provider, operation_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_data_availability_events_dataset_date
    ON ops.data_availability_events (dataset, business_date DESC);

CREATE INDEX IF NOT EXISTS idx_data_availability_events_created_at
    ON ops.data_availability_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_data_availability_events_type_status
    ON ops.data_availability_events (
        availability_type,
        completeness_status,
        created_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_alerts_events_email_status
    ON alerts.events (email_status, email_attempts, event_time);

CREATE INDEX IF NOT EXISTS idx_alerts_events_recent
    ON alerts.events (event_time DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_events_source_time
    ON alerts.events (source_system, event_time DESC);

DO $$
DECLARE
    schema_name text;
BEGIN
    FOR schema_name IN
        SELECT nspname
        FROM pg_namespace
        WHERE nspname !~ '^pg_'
          AND nspname <> 'information_schema'
          AND nspname <> 'public'
        ORDER BY nspname
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO helios_readonly', schema_name);
        EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO helios_readonly', schema_name);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO helios_readonly', schema_name);
    END LOOP;
END $$;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT USAGE ON SCHEMAS TO helios_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT SELECT ON TABLES TO helios_readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE helios_admin
    GRANT USAGE, SELECT ON SEQUENCES TO helios_readonly;
