WITH source AS (
    SELECT
        fund_code,
        source_legal_entity,
        source_file_name,
        source_file_row_number,
        nav_date,
        sftp_upload_timestamp,
        broker_name,
        account_group,
        account,
        trade_date,
        product_id_internal,
        product,
        type,
        month_year,
        client_symbol,
        strike_price,
        call_put,
        product_currency_1,
        long_short,
        quantity_1,
        counter_currency_ccy2,
        ccy2_long_short,
        ccy2_quantity_2,
        trade_price,
        multiplier_and_tick_value,
        cost_in_native_currency,
        open_exchange_rate,
        cost_in_base_currency,
        market_settlement_price,
        market_value_in_native_currency,
        close_exchange_rate,
        market_value_in_base_currency,
        sector,
        sub_sector,
        country,
        exchange_name,
        source_1_symbol,
        source_3_symbol,
        one_chicago_symbol,
        fas_level,
        option_style,
        created_at,
        updated_at
    FROM nav.positions
)

SELECT *
FROM source
