-- Table DDL for ops.data_availability_events.
--
-- This file is disabled as a dbt model in dbt_project.yml. It is retained as
-- operator reference SQL only. Read-only dbt credentials cannot run this.
-- Apply it manually with the helios_admin role before scheduling workflows
-- that emit data availability events.

CREATE TABLE IF NOT EXISTS ops.data_availability_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR NOT NULL UNIQUE,
    dataset VARCHAR NOT NULL,
    source_system VARCHAR NOT NULL,
    availability_type VARCHAR NOT NULL,
    business_date DATE,
    window_start TIMESTAMPTZ,
    window_end TIMESTAMPTZ,
    scope VARCHAR,
    grain VARCHAR,
    source_table VARCHAR,
    row_count INTEGER,
    entity_count INTEGER,
    period_count INTEGER,
    completeness_status VARCHAR NOT NULL DEFAULT 'unknown',
    run_id VARCHAR,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
