-- Table DDL for ops.email_notification_outbox.
--
-- This file is disabled as a dbt model in dbt_project.yml. It is retained as
-- operator reference SQL only. Read-only dbt credentials cannot run this.
-- Apply it manually with the helios_admin role before enabling email
-- notification workflows.

CREATE TABLE IF NOT EXISTS ops.email_notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key VARCHAR NOT NULL,
    recipient_email VARCHAR NOT NULL,
    channel VARCHAR NOT NULL DEFAULT 'email',
    dataset VARCHAR,
    source_event_key VARCHAR,
    source_event_id BIGINT,
    subject TEXT NOT NULL,
    body_text TEXT NOT NULL,
    body_html TEXT,
    status VARCHAR NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 6,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_attempt_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    provider VARCHAR,
    provider_message_id VARCHAR,
    last_error_type VARCHAR(255),
    last_error_message TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_email_notification_key_recipient
        UNIQUE (notification_key, recipient_email),
    CONSTRAINT chk_email_notification_status
        CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'dead')),
    CONSTRAINT chk_email_notification_attempts
        CHECK (attempts >= 0 AND max_attempts > 0),
    CONSTRAINT chk_email_notification_channel
        CHECK (channel = 'email')
);
