import { PRODUCT_ALIASES, PRODUCT_DEFINITIONS } from "./productLookup";

export interface NavPositionSqlParams {
  selectedDate?: string | null;
  fund?: string | null;
  accountGroup?: string | null;
  productSearch?: string | null;
  productFamily?: string | null;
  marketName?: string | null;
  productCode?: string | null;
  ruleStatus?: string | null;
}

export interface NavPositionSqlDownload {
  group: "Checks" | "Marts" | "Drilldowns";
  label: string;
  fileName: string;
  relativePath: string;
  sql: string;
}

function sqlText(value: string | null | undefined): string {
  return value === null || value === undefined
    ? "NULL"
    : `'${value.replaceAll("'", "''")}'`;
}

function nullableFilterValue(value: string | null | undefined): string | null {
  const trimmed = value?.trim();
  if (!trimmed || trimmed.toLowerCase() === "all") return null;
  return trimmed;
}

function valuesRows(rows: string[][]): string {
  return rows.map((row) => `    (${row.join(", ")})`).join(",\n");
}

function productCatalogValues(): string {
  return valuesRows(
    PRODUCT_DEFINITIONS.map((definition) => [
      sqlText(definition.exchangeCode),
      sqlText(definition.ruleGroup),
      sqlText(definition.ruleRegion),
      sqlText(definition.exchangeCodeUnderlying),
      sqlText(definition.bbgExchangeCode),
      sqlText(definition.defaultExchangeName),
    ])
  );
}

function navAliasValues(): string {
  return valuesRows(
    PRODUCT_ALIASES.filter((alias) => alias.source === "nav" || alias.source === "any").map(
      (alias, index) => [
        String(index + 1),
        sqlText(alias.matchType),
        sqlText(alias.pattern),
        sqlText(alias.exchangeCode),
        sqlText(alias.optionType ?? null),
      ]
    )
  );
}

function generatedSql(sql: string): string {
  return `-- Generated by npm run sql:nav-positions.
-- Source of truth: frontend/lib/positionsAndTrades/rules/*.json.
-- UI download builder: frontend/lib/positionsAndTrades/navPositionSqlDownloads.ts.
-- Do not edit this file directly. Update the JSON rules and regenerate.

${sql.trim()}
`;
}

function positionsWithRulesCte(params: NavPositionSqlParams): string {
  const selectedDate = nullableFilterValue(params.selectedDate);
  const fund = nullableFilterValue(params.fund);
  const accountGroup = nullableFilterValue(params.accountGroup);
  const productSearch = nullableFilterValue(params.productSearch);
  const productFamily = nullableFilterValue(params.productFamily);
  const marketName = nullableFilterValue(params.marketName);
  const productCode = nullableFilterValue(params.productCode);
  const ruleStatus = nullableFilterValue(params.ruleStatus);

  return `with params as (
  select
    ${sqlText(selectedDate)}::date as requested_nav_date,
    ${sqlText(fund)}::text as fund_filter,
    ${sqlText(accountGroup)}::text as account_group_filter,
    ${sqlText(productSearch)}::text as product_search,
    ${sqlText(productFamily)}::text as product_family_filter,
    ${sqlText(marketName)}::text as market_name_filter,
    ${sqlText(productCode)}::text as product_code_filter,
    ${sqlText(ruleStatus)}::text as rule_status_filter
),
product_catalog as (
  select *
  from (
    values
${productCatalogValues()}
  ) as t(
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    bbg_exchange_code,
    default_exchange_name
  )
),
product_aliases as (
  select *
  from (
    values
${navAliasValues()}
  ) as t(
    priority,
    match_type,
    pattern,
    product_code,
    option_type
  )
),
source_positions as (
  select p.*
  from nav.positions p
  cross join params
  where (params.fund_filter is null or p.fund_code = params.fund_filter)
    and (params.requested_nav_date is null or p.nav_date = params.requested_nav_date)
),
latest_nav_by_fund as (
  select
    source_positions.fund_code,
    coalesce((select requested_nav_date from params), max(source_positions.nav_date)) as nav_date
  from source_positions
  group by source_positions.fund_code
),
latest_upload_by_fund as (
  select
    source_positions.fund_code,
    source_positions.nav_date,
    max(source_positions.sftp_upload_timestamp) as sftp_upload_timestamp
  from source_positions
  inner join latest_nav_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
  group by source_positions.fund_code, source_positions.nav_date
),
latest_positions as (
  select source_positions.*
  from source_positions
  inner join latest_upload_by_fund latest
    on latest.fund_code = source_positions.fund_code
   and latest.nav_date = source_positions.nav_date
   and latest.sftp_upload_timestamp = source_positions.sftp_upload_timestamp
),
normalized_positions as (
  select
    latest_positions.*,
    upper(regexp_replace(coalesce(latest_positions.product, ''), '[[:space:]]+', ' ', 'g')) as product_norm,
    (
      upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'PUT', 'C', 'P')
      or upper(coalesce(latest_positions.type, '')) like '%OPTION%'
    ) as is_option,
    case
      when upper(coalesce(latest_positions.call_put, '')) in ('CALL', 'C') then 'C'
      when upper(coalesce(latest_positions.call_put, '')) in ('PUT', 'P') then 'P'
      else null
    end as put_call,
    case
      when latest_positions.month_year ~ '^\\s*\\d{1,2}/\\d{1,2}/\\d{4}\\s*$'
        then to_char(to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'), 'YYYYMM')
      when upper(trim(coalesce(latest_positions.month_year, ''))) ~ '^[A-Z]{3}\\d{2}$'
        then to_char(to_date(upper(trim(latest_positions.month_year)), 'MONYY'), 'YYYYMM')
      else null
    end as contract_yyyymm,
    case
      when latest_positions.month_year ~ '^\\s*\\d{1,2}/\\d{1,2}/\\d{4}\\s*$'
        then extract(day from to_date(trim(latest_positions.month_year), 'MM/DD/YYYY'))::integer
      else null
    end as contract_day
  from latest_positions
),
rule_matches as (
  select
    normalized_positions.*,
    matched_alias.priority as rule_priority,
    matched_alias.match_type as rule_match_type,
    matched_alias.pattern as rule_pattern,
    matched_alias.product_code as matched_product_code
  from normalized_positions
  left join lateral (
    select product_aliases.*
    from product_aliases
    where (
        (product_aliases.match_type = 'exact' and normalized_positions.product_norm = product_aliases.pattern)
        or (product_aliases.match_type = 'regex' and normalized_positions.product_norm ~* product_aliases.pattern)
      )
      and (
        product_aliases.option_type is null
        or product_aliases.option_type = case when normalized_positions.is_option then 'option' else 'future' end
      )
    order by product_aliases.priority
    limit 1
  ) matched_alias on true
),
positions_with_rules as (
  select
    rule_matches.fund_code,
    rule_matches.source_legal_entity,
    rule_matches.source_file_name,
    rule_matches.source_file_row_number,
    rule_matches.nav_date,
    rule_matches.sftp_upload_timestamp,
    rule_matches.broker_name,
    rule_matches.account_group,
    rule_matches.account,
    rule_matches.trade_date,
    rule_matches.product_id_internal,
    rule_matches.product,
    rule_matches.type,
    rule_matches.month_year,
    rule_matches.client_symbol,
    rule_matches.strike_price,
    rule_matches.call_put,
    rule_matches.product_currency_1,
    rule_matches.long_short,
    rule_matches.quantity_1,
    rule_matches.counter_currency_ccy2,
    rule_matches.ccy2_long_short,
    rule_matches.ccy2_quantity_2,
    rule_matches.trade_price,
    rule_matches.multiplier_and_tick_value,
    rule_matches.cost_in_native_currency,
    rule_matches.open_exchange_rate,
    rule_matches.cost_in_base_currency,
    rule_matches.market_settlement_price,
    rule_matches.market_value_in_native_currency,
    rule_matches.close_exchange_rate,
    rule_matches.market_value_in_base_currency,
    rule_matches.sector,
    rule_matches.sub_sector,
    rule_matches.country,
    rule_matches.exchange_name,
    rule_matches.source_1_symbol,
    rule_matches.source_3_symbol,
    rule_matches.one_chicago_symbol,
    rule_matches.fas_level,
    rule_matches.option_style,
    rule_matches.created_at,
    rule_matches.updated_at,
    catalog.product_code,
    catalog.product_family,
    catalog.market_name,
    case when rule_matches.is_option then catalog.underlying_product_code else null end as underlying_product_code,
    catalog.bbg_exchange_code,
    catalog.default_exchange_name,
    rule_matches.contract_yyyymm,
    rule_matches.contract_day,
    rule_matches.put_call,
    case
      when rule_matches.strike_price is null then null
      else round(rule_matches.strike_price::numeric, 3)::double precision
    end as strike_price_normalized,
    case
      when catalog.product_code is null then 'unresolved_product'
      when coalesce(trim(rule_matches.month_year), '') <> '' and rule_matches.contract_yyyymm is null then 'unparsed_contract'
      when rule_matches.is_option and rule_matches.put_call is null then 'option_missing_put_call'
      when rule_matches.is_option and rule_matches.strike_price is null then 'option_missing_strike'
      else 'ok'
    end as rule_status,
    rule_matches.rule_priority,
    rule_matches.rule_match_type,
    rule_matches.rule_pattern
  from rule_matches
  left join product_catalog catalog
    on catalog.product_code = rule_matches.matched_product_code
),
filtered_positions as (
  select positions_with_rules.*
  from positions_with_rules
  cross join params
  where (params.account_group_filter is null or positions_with_rules.account_group = params.account_group_filter)
    and (params.product_family_filter is null or positions_with_rules.product_family = params.product_family_filter)
    and (params.market_name_filter is null or positions_with_rules.market_name = params.market_name_filter)
    and (params.product_code_filter is null or positions_with_rules.product_code = params.product_code_filter)
    and (params.rule_status_filter is null or positions_with_rules.rule_status = params.rule_status_filter)
    and (
      params.product_search is null
      or positions_with_rules.product ilike '%' || params.product_search || '%'
      or positions_with_rules.product_code ilike '%' || params.product_search || '%'
      or positions_with_rules.product_family ilike '%' || params.product_search || '%'
      or positions_with_rules.market_name ilike '%' || params.product_search || '%'
      or positions_with_rules.product_id_internal ilike '%' || params.product_search || '%'
      or positions_with_rules.client_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_1_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.source_3_symbol ilike '%' || params.product_search || '%'
      or positions_with_rules.account ilike '%' || params.product_search || '%'
    )
)`;
}

function groupingColumns(alias = ""): string[] {
  const prefix = alias ? `${alias}.` : "";
  return [
    `${prefix}product_code`,
    `${prefix}product_family`,
    `${prefix}market_name`,
    `${prefix}underlying_product_code`,
    `${prefix}contract_yyyymm`,
    `${prefix}contract_day`,
    `${prefix}put_call`,
    `${prefix}strike_price_normalized`,
  ];
}

function groupByGroupingColumns(alias = ""): string {
  return groupingColumns(alias).join(",\n    ");
}

export function buildGroupedLatestSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
final as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    ${groupByGroupingColumns()},
    string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
    string_agg(distinct account_group, ', ' order by account_group) filter (
      where account_group is not null and account_group <> ''
    ) as account_groups,
    count(distinct fund_code)::integer as fund_count,
    count(distinct account_group)::integer as account_group_count,
    count(distinct account)::integer as account_count,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(quantity_1, 0))::double precision as net_quantity,
    sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base,
    (
      sum(case when trade_price is not null then trade_price * abs(coalesce(quantity_1, 0)) else 0 end)
      / nullif(sum(case when trade_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
    )::double precision as avg_trade_price,
    (
      sum(case when market_settlement_price is not null then market_settlement_price * abs(coalesce(quantity_1, 0)) else 0 end)
      / nullif(sum(case when market_settlement_price is not null then abs(coalesce(quantity_1, 0)) else 0 end), 0)
    )::double precision as avg_settlement_price
  from filtered_positions
  group by
    ${groupByGroupingColumns()}
)
select * from final;`);
}

export function buildGroupedWithRawExamplesSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
final as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    ${groupByGroupingColumns()},
    string_agg(distinct fund_code, ', ' order by fund_code) as fund_codes,
    string_agg(distinct account_group, ', ' order by account_group) filter (
      where account_group is not null and account_group <> ''
    ) as account_groups,
    count(distinct fund_code)::integer as fund_count,
    count(distinct account_group)::integer as account_group_count,
    count(distinct account)::integer as account_count,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    string_agg(distinct product, ' | ' order by product) filter (
      where product is not null and product <> ''
    ) as raw_products,
    string_agg(distinct type, ' | ' order by type) filter (
      where type is not null and type <> ''
    ) as raw_types,
    string_agg(distinct month_year, ' | ' order by month_year) filter (
      where month_year is not null and month_year <> ''
    ) as raw_month_years,
    string_agg(distinct product_id_internal, ' | ' order by product_id_internal) filter (
      where product_id_internal is not null and product_id_internal <> ''
    ) as raw_product_ids_internal,
    string_agg(distinct client_symbol, ' | ' order by client_symbol) filter (
      where client_symbol is not null and client_symbol <> ''
    ) as raw_client_symbols,
    string_agg(distinct source_1_symbol, ' | ' order by source_1_symbol) filter (
      where source_1_symbol is not null and source_1_symbol <> ''
    ) as raw_source_1_symbols,
    string_agg(distinct source_3_symbol, ' | ' order by source_3_symbol) filter (
      where source_3_symbol is not null and source_3_symbol <> ''
    ) as raw_source_3_symbols,
    string_agg(distinct exchange_name, ' | ' order by exchange_name) filter (
      where exchange_name is not null and exchange_name <> ''
    ) as raw_exchange_names,
    string_agg(distinct call_put, ' | ' order by call_put) filter (
      where call_put is not null and call_put <> ''
    ) as raw_call_puts,
    string_agg(distinct strike_price::text, ' | ' order by strike_price::text) filter (
      where strike_price is not null
    ) as raw_strike_prices,
    string_agg(distinct rule_match_type, ' | ' order by rule_match_type) filter (
      where rule_match_type is not null and rule_match_type <> ''
    ) as rule_match_types,
    string_agg(distinct rule_pattern, ' | ' order by rule_pattern) filter (
      where rule_pattern is not null and rule_pattern <> ''
    ) as rule_patterns,
    string_agg(distinct source_file_name, ' | ' order by source_file_name) filter (
      where source_file_name is not null and source_file_name <> ''
    ) as source_file_names,
    (array_agg(source_file_name order by source_file_name, source_file_row_number))[1] as example_source_file_name,
    (array_agg(source_file_row_number order by source_file_name, source_file_row_number))[1] as example_source_file_row_number,
    min(account_group) as example_account_group,
    min(account) as example_account
  from filtered_positions
  group by
    ${groupByGroupingColumns()}
)
select * from final;`);
}

export function buildAccountBreakoutSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
account_grouped as (
  select
    max(nav_date) as nav_date,
    max(sftp_upload_timestamp)::text as latest_upload_at,
    ${groupByGroupingColumns()},
    fund_code,
    account_group,
    account,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_account,
    sum(abs(coalesce(quantity_1, 0)))::double precision as gross_quantity_account,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base_account,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base_account,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base_account
  from filtered_positions
  group by
    ${groupByGroupingColumns()},
    fund_code,
    account_group,
    account
),
final as (
  select
    account_grouped.*,
    (
      sum(qty_account) over (
        partition by
          ${groupByGroupingColumns("account_grouped")}
      )
    )::double precision as qty_total
  from account_grouped
)
select * from final;`);
}

export function buildRuleExceptionsSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
final as (
  select
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day,
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    min(source_file_name) as example_source_file_name,
    min(source_file_row_number) as example_source_file_row_number
  from filtered_positions
  where rule_status is distinct from 'ok'
     or product_code is null
     or (coalesce(trim(month_year), '') <> '' and contract_yyyymm is null)
  group by
    rule_status,
    product,
    type,
    month_year,
    call_put,
    strike_price,
    product_code,
    product_family,
    market_name,
    contract_yyyymm,
    contract_day
)
select * from final;`);
}

export function buildGroupedVsRawTotalsSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
grouped as (
  select
    ${groupByGroupingColumns()},
    count(*)::integer as row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
  from filtered_positions
  group by
    ${groupByGroupingColumns()}
),
grouped_totals as (
  select
    count(*)::integer as grouped_row_count,
    sum(row_count)::integer as grouped_source_row_count,
    sum(qty_total)::double precision as qty_total,
    sum(qty_agr)::double precision as qty_agr,
    sum(qty_moross)::double precision as qty_moross,
    sum(qty_pnt)::double precision as qty_pnt,
    sum(qty_titan)::double precision as qty_titan,
    sum(cost_base)::double precision as cost_base,
    sum(market_value_base)::double precision as market_value_base,
    sum(unrealized_pnl_base)::double precision as unrealized_pnl_base
  from grouped
),
raw_totals as (
  select
    count(*)::integer as raw_row_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(case when lower(coalesce(fund_code, '')) = 'agr' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_agr,
    sum(case when lower(coalesce(fund_code, '')) = 'moross' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_moross,
    sum(case when lower(coalesce(fund_code, '')) = 'pnt' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_pnt,
    sum(case when lower(coalesce(fund_code, '')) = 'titan' then coalesce(quantity_1, 0) else 0 end)::double precision as qty_titan,
    sum(coalesce(cost_in_base_currency, 0))::double precision as cost_base,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base,
    sum(coalesce(market_value_in_base_currency, 0) - coalesce(cost_in_base_currency, 0))::double precision as unrealized_pnl_base
  from filtered_positions
),
final as (
  select
    grouped_totals.grouped_row_count,
    raw_totals.raw_row_count,
    grouped_totals.grouped_source_row_count,
    grouped_totals.grouped_source_row_count - raw_totals.raw_row_count as row_count_diff,
    grouped_totals.qty_total - raw_totals.qty_total as qty_total_diff,
    grouped_totals.qty_agr - raw_totals.qty_agr as qty_agr_diff,
    grouped_totals.qty_moross - raw_totals.qty_moross as qty_moross_diff,
    grouped_totals.qty_pnt - raw_totals.qty_pnt as qty_pnt_diff,
    grouped_totals.qty_titan - raw_totals.qty_titan as qty_titan_diff,
    grouped_totals.cost_base - raw_totals.cost_base as cost_base_diff,
    grouped_totals.market_value_base - raw_totals.market_value_base as market_value_base_diff,
    grouped_totals.unrealized_pnl_base - raw_totals.unrealized_pnl_base as unrealized_pnl_base_diff
  from grouped_totals
  cross join raw_totals
)
select * from final;`);
}

export function buildRawRowsForGroupSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
final as (
  select
    fund_code,
    source_legal_entity,
    source_file_name,
    source_file_row_number,
    nav_date,
    sftp_upload_timestamp,
    broker_name,
    account_group,
    account,
    trade_date,
    product_id_internal,
    product,
    type,
    month_year,
    client_symbol,
    strike_price,
    call_put,
    product_currency_1,
    long_short,
    quantity_1,
    counter_currency_ccy2,
    ccy2_long_short,
    ccy2_quantity_2,
    trade_price,
    multiplier_and_tick_value,
    cost_in_base_currency,
    market_settlement_price,
    market_value_in_base_currency,
    exchange_name,
    source_1_symbol,
    source_3_symbol,
    option_style,
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    contract_yyyymm,
    contract_day,
    put_call,
    strike_price_normalized,
    rule_status,
    rule_priority,
    rule_match_type,
    rule_pattern
  from filtered_positions
)
select * from final;`);
}

export function buildProductRuleCoverageSql(params: NavPositionSqlParams = {}): string {
  return generatedSql(`${positionsWithRulesCte(params)},
final as (
  select
    fund_code,
    product,
    type,
    month_year,
    contract_yyyymm,
    contract_day,
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    rule_status,
    rule_match_type,
    rule_pattern,
    count(*)::integer as row_count,
    count(distinct account)::integer as account_count,
    sum(coalesce(quantity_1, 0))::double precision as qty_total,
    sum(coalesce(market_value_in_base_currency, 0))::double precision as market_value_base
  from filtered_positions
  group by
    fund_code,
    product,
    type,
    month_year,
    contract_yyyymm,
    contract_day,
    product_code,
    product_family,
    market_name,
    underlying_product_code,
    rule_status,
    rule_match_type,
    rule_pattern
)
select * from final;`);
}

export const buildProductRuleExceptionsSql = buildRuleExceptionsSql;
export const buildProductRuleDetailSql = buildRawRowsForGroupSql;
export const buildNormalizedPositionsGroupedSql = buildGroupedLatestSql;

export function buildNavPositionSqlDownloads(
  params: NavPositionSqlParams = {}
): NavPositionSqlDownload[] {
  return [
    {
      group: "Marts",
      label: "Grouped Latest",
      fileName: "grouped_latest.sql",
      relativePath: "marts/grouped_latest.sql",
      sql: buildGroupedLatestSql(params),
    },
    {
      group: "Marts",
      label: "Grouped + Raw Examples",
      fileName: "grouped_with_raw_examples.sql",
      relativePath: "marts/grouped_with_raw_examples.sql",
      sql: buildGroupedWithRawExamplesSql(params),
    },
    {
      group: "Marts",
      label: "Account Breakout",
      fileName: "account_breakout.sql",
      relativePath: "marts/account_breakout.sql",
      sql: buildAccountBreakoutSql(params),
    },
    {
      group: "Checks",
      label: "Rule Exceptions",
      fileName: "rule_exceptions.sql",
      relativePath: "checks/rule_exceptions.sql",
      sql: buildRuleExceptionsSql(params),
    },
    {
      group: "Checks",
      label: "Grouped vs Raw Totals",
      fileName: "grouped_vs_raw_totals.sql",
      relativePath: "checks/grouped_vs_raw_totals.sql",
      sql: buildGroupedVsRawTotalsSql(params),
    },
    {
      group: "Drilldowns",
      label: "Raw Rows For Group",
      fileName: "raw_rows_for_group.sql",
      relativePath: "drilldowns/raw_rows_for_group.sql",
      sql: buildRawRowsForGroupSql(params),
    },
  ];
}
